### ISSUE TITLE
Reflective/shiny models

### ISSUE THREAD

**Issue by liquidmetalrob** [kovacsv/Online3DViewer#10]
I can't get models to appear reflective/shiny. I have a model that is shiny when I load it in the Windows 3D model program but not on here. Is it possible?

**Comment by kovacsv** [comment]
Can you please provide an example file?

**Comment by liquidmetalrob** [comment]
zbox.obj:

  mtllib z.mtl
  v -0.5 -0.5 0.5
  v -0.5 -0.5 -0.5
  v -0.5 0.5 -0.5
  v -0.5 0.5 0.5
  v 0.5 -0.5 0.5
  v 0.5 -0.5 -0.5
  v 0.5 0.5 -0.5
  v 0.5 0.5 0.5
  usemtl 21
  f 1 2 3 4
  f 3 7 6 2
  f 4 8 7 3
  f 5 6 7 8
  f 1 2 6 5
  f 8 4 1 5

z.mtl:

  newmtl 21
  illum 2
  Ka 0.79  0.10  0.035
  Kd 0.79  0.10  0.035
  Ks 0.3500 0.3500 0.3500

**Comment by kovacsv** [comment]
As far as I know shininess is driven by the Ns parameter in the mtl file. The 3D viewer in windows shows every obj model as very shiny, but I'm not sure that this is the correct visualization for them.

**Comment by kovacsv** [comment]
It seems like the speciality of the windows 3d viewer, so I close this one.
