### ISSUE TITLE
onFinished function's timing on texture loading

### ISSUE THREAD

**Issue by nikita-fuchs** [kovacsv/Online3DViewer#100]
Hey, on obj files with lots of huge textures, the "loading" dialog disappears before all the textures are loaded entirely. (I'm asking for a public file I can hand you for repro right now). What essentially happens right now is that the 3d model almost freezes until all textures are loaded, which takes a while on my macbook pro late 2017. Here is a screenshot of the files, just as a hint for now: 

![image](https://user-images.githubusercontent.com/11761828/126486780-0165a444-c77d-4995-b689-062fc23243b1.png)

**Comment by kovacsv** [comment]
It works like this by design, so you can work with the model while textures are loading in the background. I think it's possible to wait for all textures to load before showing a model, but currently I don't plan to implement this behavior.

**Comment by nikita-fuchs** [comment]
This behaviour is okay, in practice though our testing model freezes entirely and the view cannot be moved, so therefore I would need some sort of function to at least display some indicator, till everything is loaded and usable.

**Comment by kovacsv** [comment]
An example file set would help a lot  to reproduce the issue.

**Comment by nikita-fuchs** [comment]
Hey, are you able to reproduce with this example ? https://mega.nz/file/QAsAUBLa#nG53MUU1VnT8cloYV0aZF2ufvAhIM-8R_eGDT7E-AbQ

**Comment by kovacsv** [comment]
Yes, I can reproduce the issue now.

There are a few things that you can do to prevent lagging:
- Reduce texture size (it doesn't make sense to use such a huge texture for web visualization).
- Make texture size (width and height) power of two. For visualization this is needed to make everything work properly. If you have textures with non power of two sides than the viewer will automatically resize them, and it takes a lot of time.

Maybe it's possible to remove this power of two resizing from the viewer, but I have to investigate if it breaks anything.

**Comment by kovacsv** [comment]
Created an issue (#105) for the investigation.

**Comment by kovacsv** [comment]
With the fix of #105 the performance is much better, but it can be further optimized by decreasing the size of the textures.

**Comment by nikita-fuchs** [comment]
thank you ! Yes, we have a lot of optimisation happening in the backend of course, but unfortunately that kind of stuff is what out target audience is coming around with in the first place, so we need to deal with that unfortunately.

**Comment by nikita-fuchs** [comment]
hey, I'm still experiencing quite some heavy loading time on the repro in the latest release, am I doing something wrong or is this the best optimisation possible for now ? (no bad blood, just checking 😜 ) could this theoretically be improved somehow in the future? with additional help of someone or something ?

**Comment by kovacsv** [comment]
One way is to lower the size of the textures. Another way could be to show progress dialog while all textures are loaded (this needs some programming, of course).

**Comment by nikita-fuchs** [comment]
By lowering the texture size you mean doing it on the creator's side, right ? This is something those poor guys and girls can't do with their programs yet...

A load indicator would greatly help improving the user experience, people with high quality exports can't tell whether it's not their browser that simply froze ;) 

Will you be available for some reasoning about access to state and event functions some time later or so?

**Comment by kovacsv** [comment]
I've created this issue to handle the situation:
Hide progress dialog only when all textures are loaded #108
