### ISSUE TITLE
Self-host viewer with Tree-view and Details side panels included

### ISSUE THREAD

**Issue by revelation12** [kovacsv/Online3DViewer#104]
Hi @kovacsv,

Thanks for making this great repository.

I am interested in self-hosting a 3D viewer that includes the tree-view (and its functionality), the main viewer, and the details side panels for a particular .obj + .mtl file. 

I read your post which describes how to self-host the main viewer. (https://github.com/kovacsv/Online3DViewer/wiki/Use-the-Viewer-on-Your-Website). This is great, but it doesn't seem to include the tree-view and details side panels.

I also tried the various sandbox examples, but none seem to have these additional side panels.

Do you have any recommendations on how to approach efficiently building this out?

Thanks!

**Comment by kovacsv** [comment]
I would go this way:
- Clone the repository.
- Run `npm install` and then `npm run build`.
- Now the whole distributable website code should be in the `build/final/website` folder.

Open `index.html`, and set the location hash programmatically after the website initialization code. Something like this:
```js
$(window).on ('load', function () {
    let website = new OV.Website ({
        headerDiv : $('#header'),
        toolbarDiv : $('#toolbar'),
        mainDiv : $('#main'),
        introDiv : $('#intro'),
        navigatorDiv : $('#main_navigator'),
        sidebarDiv : $('#main_sidebar'),
        viewerDiv : $('#main_viewer'),
        fileInput : $('#open_file')
    });
    website.Load ();

    // set location hash to your self-hosted files so the website will load them automatically
    window.location.hash = 'model=../test/testfiles/obj/hundred_cubes.obj,../test/testfiles/obj/hundred_cubes.mtl';
});
```

**Comment by evancollins1** [comment]
Thanks! When executing the code you sent above, my local port webpage visually pauses at "Loading Model". The following error is produced:

Uncaught TypeError: newFileList.FillFromFileUrls is not a function
    at OV.Importer.LoadFiles (importer.js:359)
    at OV.Importer.LoadFilesFromUrls (importer.js:285)
    at OV.ThreeModelLoader.LoadFromUrlList (threemodelloader.js:25)
    at OV.Website.LoadModelFromUrlList (website.js:189)
    at OV.Website.OnHashChange (website.js:224)
    at OV.HashHandler.OnChange (hashhandler.js:77)


Any recommendations?

**Comment by revelation12** [comment]
Thanks! When executing the code you sent above, my local port webpage visually pauses at "Loading Model". The following error is produced:

Uncaught TypeError: newFileList.FillFromFileUrls is not a function
at OV.Importer.LoadFiles (importer.js:359)
at OV.Importer.LoadFilesFromUrls (importer.js:285)
at OV.ThreeModelLoader.LoadFromUrlList (threemodelloader.js:25)
at OV.Website.LoadModelFromUrlList (website.js:189)
at OV.Website.OnHashChange (website.js:224)
at OV.HashHandler.OnChange (hashhandler.js:77)

Any recommendations?

**Comment by kovacsv** [comment]
That's really strange, it works fine for me. Are you using a web server or just open local html?

**Comment by evancollins1** [comment]
Thanks - it works now. It was an issue with the root directory. The above code you sent works as you stated.

**Comment by revelation12** [comment]
Thanks - it works now. It was an issue with the root directory on my end. Your code works above as stated.

**Comment by kovacsv** [comment]
Cool, I'm glad it works.
