### ISSUE TITLE
Hide progress dialog only when all textures are loaded

### ISSUE THREAD

**Issue by kovacsv** [kovacsv/Online3DViewer#108]

**Comment by nikita-fuchs** [comment]
I guess it just needs to move https://github.com/kovacsv/Online3DViewer/blob/master/website/o3dv/loader.js#L51 to line 55 ? 
If there could be some per-texture loading callback we could even have a loading bar maybe ? :)

**Comment by kovacsv** [comment]
Done in 0.7.19.
