### ISSUE TITLE
Add support for Collada files

### ISSUE THREAD

**Issue by kovacsv** [kovacsv/Online3DViewer#109]

**Comment by GitHubDragonFly** [comment]
This is intended only as a suggestion.

There are 4 viewers that I bothered creating, one of which is DAE (Collada), and can be found [here](https://github.com/GitHubDragonFly/HTML_CSS_JS_Flask). They can be previewed online with some limitations.

If, inside my project, you can find any idea or any code that you could use to speed-up updating your project then feel free to do it. Everything is open source and MIT licensed so you wouldn't need any permission.

I wouldn't be looking to contribute to your project in any other way than already mentioned, but do find it neat looking and exactly what everybody should be using to preview 3D models.

**Comment by kovacsv** [comment]
Thanks for the suggestion. As I see you use the ColladaLoader provided by three.js, and this is exactly what I'm planning to use.  :) I'm happy to hear your experiences with the ColladaLoader.

**Comment by GitHubDragonFly** [comment]
One more thing that you could pay attention to is `child.material.skinning = true;`.

The browser was throwing bunch of errors for files that had it set to `false` so I forced it to be 'true' all the time.

**Comment by GitHubDragonFly** [comment]
Just an FYI,

I did make some more changes to my project and GLTF and DAE viewers will now run each detected animation separately.
A button with letter "A" will show the current running animation as "Ax" (where x goes from 0 to animation count - 1) and will continue changing them with each click.

**Comment by kovacsv** [comment]
Done in 0.7.19.
