### ISSUE TITLE
Loading model by url is not working

### ISSUE THREAD

**Issue by tomerel22** [kovacsv/Online3DViewer#115]
Which file can work with url?
I tried to display a model by running a server that by his url a fbx model will be downloaded
it worked but the option to load model by his url is not working with any url/
Thanks!

**Comment by kovacsv** [comment]
Loading models from url works if the host server enables CORS requests. You can find the details with GitHub and DropBox examples here: https://3dviewer.net/info/index.html#loading_models_server

**Comment by tomerel22** [comment]
my server enables CORS requests.
the server is flask server that send the requested file by some url

**Comment by kovacsv** [comment]
Maybe I can tell more if you provide the url.

**Comment by tomerel22** [comment]
This is part of the code
from flask import Flask, render_template, send_file
from flask_cors import CORS, cross_origin

app = Flask(__name__)
cors = CORS(app)
app.config['CORS_HEADERS'] = 'Content-Type'



@app.route("/get_fbx")
@cross_origin()
def get_binary_file(): send_file("C:/Users/erel/Desktop/fbx/example.fbx", as_attachment=True, attachment_filename="try.fbx")

**Comment by tomerel22** [comment]
The url send the fbx model to the client and download the file at the computer.
There aren't error messages, the viewer just say "No importable file found. You can open obj, 3ds, stl, ply, gltf, glb, 3dm, fbx, and off files.
"

**Comment by GitHubDragonFly** [comment]
@tomerel22

Try removing `as_attachment=True, attachment_filename="try.fbx"` parts and just send the file.

You can also check screenshots in my [HTML_CSS_JS_Flask](https://github.com/GitHubDragonFly/HTML_CSS_JS_Flask) project to see how I used `Flask` with my viewers.

I just tried the [Online 3D Viewer](https://3dviewer.net/) which did open this URL:  `http://localhost:5000/static/Images/gltf/dragonfly.gltf`

**Comment by tomerel22** [comment]
Thanks!
