### ISSUE TITLE
How to run the website locally?

### ISSUE THREAD

**Issue by 96lives** [kovacsv/Online3DViewer#116]
Hello,

I'm a graduate student at South Korea.

First of all I would like to thank you very much for this project!
The work is by far the most convenient 3D mesh visualizer with exceptional rendering quality :) 
Really, the site is far more convenient at visualizing day-to-day obj files compared to cloudcompare / meshlab.

I use this all the time at school, and I would like to use this website at home, but I can't enter the website for some reason at home.
I think my ip is blocked for some reason..

It would mean very much to me if I could run the site locally on my Mac book, but I can't figure out how. 
I have ran the `npm run build` you wrote on your developers manual, but I can't figure out how to run `npm start`.
The `package.json` file does not seem to include `start` options.
Any advice on how to run the code locally? 

I'm quite novice on frontend programming

**Comment by kovacsv** [comment]
Hey, you just have to start a local web server and then you can use the site from localhost. I'll add `npm start`, but until that you can run `npx http-server` from the root directory, and then open `http://localhost:8080/website` in your browser.

**Comment by 96lives** [comment]
Thanks for the quick reply!

**Comment by kovacsv** [comment]
`npm start` is available now in the latest version.
