### ISSUE TITLE
"Invalid header information" when loading a PLY file

### ISSUE THREAD

**Issue by sivaranjanija** [kovacsv/Online3DViewer#118]
Hi,

Thank you for developing Online 3D Viewer.
 
I am using this tool to render a PLY file as attached. But it fails saying :
![image](https://user-images.githubusercontent.com/66548230/129553548-e7b4029d-7214-42aa-a6d4-406c96cab9c7.png)

Additional information: This attached PLY file is generated by exporting a .bin to .ply in CloudCompare, and this PLY file is visualized in CloudCompare and CCViewer.
[Test.zip](https://github.com/kovacsv/Online3DViewer/files/6991850/Test.zip)

Thank you.

**Comment by kovacsv** [comment]
I've created a separate issue for color handling: #119

**Comment by kovacsv** [comment]
This model doesn't contain any faces, only vertices. I've created a new issue for supporting point clouds (#120).

**Comment by sivaranjanija** [comment]
Sure, thank you for the response.

**Comment by kovacsv** [comment]
Done in 0.7.21.

**Comment by sivaranjanija** [comment]
Thank you!
