### ISSUE TITLE
Can't load 3ds file with multiple meshes

### ISSUE THREAD

**Issue by zen253230** [kovacsv/Online3DViewer#12]
Hello and thank you for your great work!

BUT whenever the 3ds file has more than one object only the first one is displayed.

And exporting to STL removes any color and last common choice OBJ is not a binary format

Thanks again !

**Comment by kovacsv** [comment]
Hi!

It should work (or at least I've seen it working once). It would be a big help if you could provide an example 3ds file to check the issue.

**Comment by zen253230** [comment]
Thank you very much for your quick answer!

Here is the link to the file
https://wetransfer.com/downloads/dbe292b9909786f1e0caef855f76b4db20190625124434/6647f16ff6cb9aaf7c8b8c43e771c03920190625124434/1527ae

The file opens correctly with open3mod

**Comment by kovacsv** [comment]
Ok, I've found the problem. In your 3ds files there are 8 meshes. As far as I know every mesh should have a unique name in a 3ds file, but all of your meshes called "1". So the import process keeps only one of them.

I can make a workaround in the import process, but it takes some time. Until that the best you can do is to have all of your meshes different names.

**Comment by zen253230** [comment]
ok! I'll check this point.

Thanks for solving this issue!

**Comment by kovacsv** [comment]
You welcome! :)

**Comment by AraHaan** [comment]
If it was me I would warn them and tell them ``This model has multiple meshes but all are named "%s". Are you sure you want it imported like this?`` And then if they press ``No`` work around it somehow.

**Comment by kovacsv** [comment]
It should work in the new version. Please let me know if it doesn't.
