### ISSUE TITLE
racing conditions on callback function

### ISSUE THREAD

**Issue by nikita-fuchs** [kovacsv/Online3DViewer#126]
Hey, when passing this callback function: 

```
var website = new OV.Website ({


      headerDiv : $('#header'),
      toolbarDiv : $('#toolbar'),
      mainDiv : $('#main'),
      introDiv : $('#intro'),
      navigatorDiv : $('#main_navigator'),
      sidebarDiv : $('#main_sidebar'),
      viewerDiv : $('#main_viewer'),
      fileInput : $('#open_file'),
eventHandler : (type, parameters) => {
        if (type === 'model_loaded') {
     
            console.log("website:", website)
            console.log("website.model:", website.model)

        }
```

`website.model` will be logged as null, although funny enough, `website` will contain the data already.

If I give it a little more time though, like 
```
console.log("website:", this.website)
            setTimeout(() => {
              console.log("website.model:", this.website.model)
              
            }, 10);
```

then `website.model` logs fine. Do you know where this might be coming from ? Maybe that callback was placed some bad place in the viewer's code ? Although it feels like it's really only fired once things are loaded. but there must be some weird timing issue somewhere maybe ? 10 ms timeout delay means things are just a few ticks off maybe, altough I didn't test with larger models yet.

**Comment by kovacsv** [comment]
Done in 0.7.22.
