### ISSUE TITLE
fileObject not written on hot-reloaded model

### ISSUE THREAD

**Issue by nikita-fuchs** [kovacsv/Online3DViewer#129]
When loading another model into the editor from a URL, inside the loaded file the `fileObject` is undefined:

`website.modelLoader.GetImporter().GetFileList().GetFiles()[0]` shows: 

![image](https://user-images.githubusercontent.com/11761828/131197101-b329c040-975a-4e41-91af-99270267f485.png)

I wouldn't mind, if I wouldn't need it to determine the file size :/

**Comment by kovacsv** [comment]
There can be two sources for a file:
- If it comes from file open or drag and drop, than the `fileObject` member contains the original file object.
- If it comes from a url, than the `fileUrl` member contains the original url.

After the files are loaded, the `content` member will contain the content regardless of the source:
- If the `format` is `OV.FileFormat.Binary`, then the `content` is an arraybuffer.
- If the `format` is `OV.FileFormat.Text`, then the `content` is a string.
