### ISSUE TITLE
save viewer camera position

### ISSUE THREAD

**Issue by sagbarak** [kovacsv/Online3DViewer#13]
Hi Viktor! Thank you for the repository! 
I want to have an option to save the camera position to local storage, so after refreshing the page the model will appear from the same angle. 
I didn't understand how the convert function works so I can save the viewer to json and load it again. 

will appreciate your help on this one.
Thanks!

**Comment by kovacsv** [comment]
Hi!

I would modify the importerviewer.js file:
https://github.com/kovacsv/Online3DViewer/blob/master/website/include/importerviewer.js

The camera position is hard coded in this file so I think if you save your camera position to local storage, that should be loaded in the Init function of the ImporterViewer class.

The big question is when to save the mouse position. I would register a mouse move event handler, and save the current position of the mouse to local storage.

Hope it helps!

**Comment by sagbarak** [comment]
Thank you for your reply! 
the camera position value is a JSM.coord type, I have to turn it into json (and then string) in order to save it to local storage, when I get the json from the local storage which one of the convert functions should I use (and how?) to convert the json back to JSM.coord?

**Comment by kovacsv** [comment]
There is no built-in function to convert it to JSON and back so you have to do it manually like this:

```js
// to JSON
var jsonData = {
    eye : [camera.eye.x, camera.eye.y, camera.eye.z]
};

// from JSON
camera.eye = new JSM.Coord (jsonData.eye[0], jsonData.eye[1], jsonData.eye[2]);
```

**Comment by sagbarak** [comment]
Thank you so much!

**Comment by sagbarak** [comment]
So after struggling with it for a few days the next question is, from where do I get the current position?
I can create a mouse event when when pressing on the viewer element, but I searched all over and it doesn't seem to save the current position in it.

**Comment by sagbarak** [comment]
Hi :)
So I succeed saving the camera position, except of the zoom..
where can I find the zoom value in the viewer element?
and if I add this value to the viewerSettings will the viewer element get it as well?
Thanks

**Comment by kovacsv** [comment]
Hi!

There is no such thing as "zoom" stored in the viewer. When you zoom in, the eye position of the camera just moves towards the center position. So if you store eye, center, and up vectors from the camera, you will have everything to restore the previous view.

**Comment by sagbarak** [comment]
I did save those three values and the position remain the same but in the default size/zoom.
are you sure there isn't a value we are missing?

**Comment by kovacsv** [comment]
Ok, then its maybe the automatic fit in window after the model is loaded. You should remove `FitInWindow` call from the `ShowAllMeshes` function in the `importerviewer.js` file.

**Comment by sagbarak** [comment]
yes! that was the solution.
Thank you so much! :)

**Comment by kovacsv** [comment]
cool! :)
