### ISSUE TITLE
Feature Request- Ability to auto detect and load models from zip files

### ISSUE THREAD

**Issue by hey24sheep** [kovacsv/Online3DViewer#136]
Feature Request
Ability to load a `.zip` or `.rar` file which can auto-detect the model/texture files and returns list of files.

Loading files one by one (especially in case of loading textures from another folder or multiple directories) sometimes fails or refreshes the view. This way we can just upload a zip and auto load models of any type.

**Comment by hey24sheep** [comment]
To handle `.zip` we can use [zipjs](https://github.com/gildas-lormeau/zip.js#readme). To handle all compressed formats, we could use [uncompressjs](https://github.com/workhorsy/uncompress.js) (but it isn't maintained anymore)

**Comment by kovacsv** [comment]
According to the statistics users try to load zip files all the time, I haven't seen any other compressed formats yet. I've created a solution for zip files using [fflate](https://github.com/101arrowz/fflate), and it seems working.

**Comment by hey24sheep** [comment]
I see, I have seen that some people have texture in .rar formats within a zip/rar but this is awesome too. Thanks 👍🏼

**Comment by kovacsv** [comment]
Done in 0.7.22.
