### ISSUE TITLE
Embedding several instances on the same webpage

### ISSUE THREAD

**Issue by zen253230** [kovacsv/Online3DViewer#14]
Hello !

I have a request maybe an already implemented enhancement.

Would it be or is it already possible to embed directly the viewer on a html page?

In this case is it possible to have several instances of the viewer in the same web page to render simultaneously different 3d graphics?

In fact we would shift with a button from page view to full screen mode similar to existing default mode.

I know almost nothing to Javascript. So please be patient...

Thank you !

**Comment by kovacsv** [comment]
Have you checked this page:
https://github.com/kovacsv/Online3DViewer/blob/master/embeddable/multiple.html

I think it does exactly what you want to achieve.

**Comment by zen253230** [comment]
Exactly what I want !

Thank you very much!!!

**Comment by zen253230** [comment]
One question: if I specify a width greater than ~500 it doesn't apply, and yet height is taken into account whatever its value.
Any suggestion?
Thank you!

**Comment by kovacsv** [comment]
It seems working for me. You have to specify both the width and height. Can you send a demo file what doesn't work for you?

**Comment by zen253230** [comment]
Sorry indeed it works perfectly.

I forgot I had quite a wider screen resolution than what I expected so I couldn't see clearly the results.

Thank you for your answer and once more congratulations for this great tool !

**Comment by kovacsv** [comment]
I'm glad it works for you :)
