### ISSUE TITLE
Use the Viewer on Your Website with a toolbar and side menus

### ISSUE THREAD

**Issue by nczirjak-acdh** [kovacsv/Online3DViewer#148]
Hi,

the plugin is awesome, i have just one question/request.

Inside the wiki page the example is simple (https://github.com/kovacsv/Online3DViewer/wiki/Use-the-Viewer-on-Your-Website),  but it does not have a toolbar and side menus. Is there any chance for a toolbar with this version? For me this solution would be better when i can define the model url inside the div and not in the window.location.hash

thanks!

**Comment by kovacsv** [comment]
Currently there is no way to embed the engine with all the toolbars and sidebars. The closest possible solution I can think of is to embed the whole built website in an iframe to your page. In this case you can specify model urls in the iframe url code.

**Comment by nczirjak-acdh** [comment]
thanks!
