### ISSUE TITLE
Feature Request - Create modular packages out of Website

### ISSUE THREAD

**Issue by hey24sheep** [kovacsv/Online3DViewer#149]
Website is a lot more detailed and featureful. It is hard to keep up in the code and know how the feature is implemented or the data is used for example, to get Navigator feature I have to go through multiple nested functions and then decouple HTML generating functions to just understand how it all works. 

So, instead of having coupled functions and UI generating functions they should be divided into Data APIs/Modules and then HTML generating funcs. For example - LoadModel (API/Engine) => (send data) => NavigatorModule or API => (get data of all layers) => (process/generate HTML).

**Comment by hey24sheep** [comment]
@kovacsv no, I'm sorry if you felt that way but I'm not saying write better code. You have a done a fabulous and awesome job and I do not in anyway undermining or degrading your work. What I mean is like people make plugins for ThreeJs. Just like that we can make Navigator, export, etc as Plugins instead of just features in website.

**Comment by kovacsv** [comment]
No worries, I see your point :) Writing a new importer or exporter is easy and well documented, but at the moment I don't plan to provide clean API-s for every functionality. Maybe at some point in the future...
