### ISSUE TITLE
Set pivot point in rotation

### ISSUE THREAD

**Issue by SerFerBla** [kovacsv/Online3DViewer#166]
Good afternoon,
I'm creating some animations but I'm having difficulties controlling the rotations of the meshes.
 
I am modifying the _rotation_ property of the meshes and I can successfully rotate them but I don't know how to set the pivot point for the rotation to control how they should rotate, not just the angle...

I'm currently doing:
`objectToRotate.rotation.x=Math.PI/2` 
and it rotates 90 degrees but with respect to a distant point...

What is the best approach for doing this? Is there a way to set the coordinates of the pivot point?

Thanks in advance,
Sergio Fernández

**Comment by kovacsv** [comment]
As far as I know three.js doesn't have pivot point. Usually the best way is to do your transformation in three steps, and create a transformation matrix based on these steps:
- Move the element to the pivot point.
- Do the transformation.
- Move the element back to it's original position.

**Comment by SerFerBla** [comment]
> As far as I know three.js doesn't have pivot point. Usually the best way is to do your transformation in three steps, and create a transformation matrix based on these steps:
> 
> * Move the element to the pivot point.
> * Do the transformation.
> * Move the element back to it's original position.

Thanks for your answer! 
Moving the mesh will ruin my rotation animation (tween) but I'll do that if that's the best way. Please, if there's a better way to rotate the meshes let me know :)

Have a nice day and keep up the great work!
