### ISSUE TITLE
I can't access to file relative to the root folder

### ISSUE THREAD

**Issue by PacoM93** [kovacsv/Online3DViewer#17]
Hi, 
I'm opening the index.html on my browser and it look like this:

<img width="1392" alt="Captura de Pantalla 2019-08-30 a la(s) 15 15 19" src="https://user-images.githubusercontent.com/32820659/64051635-fb864a80-cb38-11e9-8d7b-986882a85599.png">

`file:///Users/francisco/File%20Maker/Online3DViewer-master/website/index.html`

but when I tried enter to the file directly like this:

`file:///Users/francisco/File%20Maker/Online3DViewer-master/website/index.html/#testfiles/cube.3ds`

Nothing happened! I get a white page.

Can you help me? 
Please :)

**Comment by kovacsv** [comment]
Hi!

First, your url is wrong, you don't need the `/` sign after index.html. Second, it will work only if you have a web server. Browsers don't allow requests in offline mode.

Hope it helps,
Viktor
