### ISSUE TITLE
[QUESTION] Automatically load model

### ISSUE THREAD

**Issue by SerFerBla** [kovacsv/Online3DViewer#170]
Good morning,
I have a really basic question about automatically loading a model when opening the viewer. 
I was using /index.html#model=mymodel.fbx to automatically do it but, for some reason it sometimes fails so I want to specify the model in the index.html file. What's the best way to do it?

In https://github.com/kovacsv/Online3DViewer/wiki/Use-the-Viewer-on-Your-Website, it is mentioned to use
`    <div class="online_3d_viewer"
        style="width: 800px; height: 600px;"
        model="testfiles/obj/hundred_cubes.obj,testfiles/obj/hundred_cubes.mtl"
        camera="3,1,2,0,0,0,0,0,1"
        defaultcolor="200,0,0"
        backgroundcolor="200,200,200">
    </div>`

but I'm currently not loading the viewer like this, I'm using what you provide in your index.html file. How should I specify the model n my case? 

Best regards

**Comment by kovacsv** [comment]
You can do it after the `website.Load ();`.

By setting location hash:
```js
window.location.hash = 'model=assets/models/solids.obj,assets/models/solids.mtl';
```

Or by calling a website function directly:
```js
let settings = new OV.ImportSettings ();
website.LoadModelFromUrlList ([
    'assets/models/solids.obj',
    'assets/models/solids.mtl',
], settings);
```

**Comment by SerFerBla** [comment]
Thanks @kovacsv! I was had tried the loadmodelfromurllist function but I wasn't sure if this was the correct way. 
I close the issue :)
