### ISSUE TITLE
add callbacks to even handler(s)

### ISSUE THREAD

**Issue by nikita-fuchs** [kovacsv/Online3DViewer#171]
in `src/app/viewer/Online3DViewer/website/o3dv/js/website.js` , the drag n drop feature currently works like:

```js
window.addEventListener ('drop', (ev) => {
            ev.stopPropagation ();
            ev.preventDefault ();
            if (ev.dataTransfer.files.length > 0) {
                this.eventHandler.HandleEvent ('model_load_started', { source : 'drop' });
                this.LoadModelFromFileList (ev.dataTransfer.files);
            }
        }, false);
 ```

If the loading of the file was a callback of the handleEvent, one would have a more granular control over which files would be loaded or handled otherwise if they are not supported by the editor. Or maybe I want to "block"  people from using fbx files. Or I want to preprocess them before loading them:

```js
window.addEventListener ('drop', (ev) => {
            ev.stopPropagation ();
            ev.preventDefault ();
            if (ev.dataTransfer.files.length > 0) {
                this.eventHandler.HandleEvent ('model_load_started', { source : 'drop', files: ev.dataTransfer.files }, this.LoadModelFromFileList);
            }
        }, false);
```

and when initialising the website:

```js
...
      eventHandler : (type, parameters, loadModel) => {
        if (type === 'model_load_started') {
                  if (parameters.files[0].extension == "jpg") {
         doSomethingTheEditorCan't() // e.g. generate 3d file from static image using our backend
         } else {
         loadModel(parameters.files[0]); // all fine here
         }
        }
```

**Comment by kovacsv** [comment]
I think I understand what you would like to achieve, but I don't think it's a good idea to make the website behavior dependent on the event handlers. If someone forgets to call the callback, the website will stop to work.

On the other hand, there is a solution for the mentioned use case:
- You can remove the FBX loader from the list of importers from outside.
- You can write a jpg importer, and add it from outide (https://github.com/kovacsv/Online3DViewer/wiki/Implement-a-New-Importer).

**Comment by nikita-fuchs** [comment]
Yeah I understand the concerns. Maybe we can go a middle way at least for the non-supported file types: An event handler function for unsupported file types and a setting to suppress the automatic error dialog ? This keeps the editor working and hands down handling unsupported things quickly and easily to the dev.

**Comment by kovacsv** [comment]
As a workaround you can handle the `model_load_failed` event, and call `website.HidePopups ()` to hide the error dialog.
