### ISSUE TITLE
GENERAL QUESTION: Are Sketchfab Free models supported?

### ISSUE THREAD

**Issue by inglesuniversal** [kovacsv/Online3DViewer#172]
Can I add a custom skybox to the viewer?

Thanks

**Comment by kovacsv** [comment]
Could you please add some details to your questions? What do you mean by the support of free Sketchfab models? Do you want to add custom skybox on the website, or you want to code it yourself?

**Comment by kovacsv** [comment]
Closing this, because no clarification arrived.
