### ISSUE TITLE
Adjust viewer viewport size

### ISSUE THREAD

**Issue by nikita-fuchs** [kovacsv/Online3DViewer#173]
When resizing the viewer viewport solely through CSS, the view is distorted:
![image](https://user-images.githubusercontent.com/11761828/143415444-d9dd990f-6fd9-4d0d-9d3b-49fca13ee7b9.png)

When adding or removing elements on any side of the editor and thus affecting the maximal available space for the viewport, is there a function to (re)set the viewport to the newly available space?

**Comment by kovacsv** [comment]
For WebGL visualizations is not enough to resize the canvas, you have to resize the WebGL viewport, too. It is done in the `Resize` function of the `Website` class. So if you would like to have a custom layout, I don't think that's possible without modifying the `Resize` function.

**Comment by nikita-fuchs** [comment]
wouldn't it be possible to adjust the function to get the size of the element that's supposed to encapsulate the viewport, and adjust the viewport's size accordingly ? Then wrap that in a event listener for window resizing.

That given, the viewport would always have the correct size. Currently, I can't update the viewer because I need to hardcode the viewport size. Or can I utilise the bespoke function and get the values to pass it simply myself ?

**Comment by kovacsv** [comment]
At the moment I don't see how could this work automatically. So at the moment your only option is to modify the `Resize` function according to your layout.

**Comment by kovacsv** [comment]
I don"t think that automatic resize is achievable, so I close this one for now.
