### ISSUE TITLE
Failed to load FBX textures

### ISSUE THREAD

**Issue by tomerel22** [kovacsv/Online3DViewer#178]
Can't load fbx files with rgb\rgba\dds textures.
Is it possile to fix it?

**Comment by kovacsv** [comment]
Could you please attach an example file?

**Comment by tomerel22** [comment]
Sure, I'll search and attach here.
But is it supposed to load rgb with fbx file?

**Comment by kovacsv** [comment]
The FBX importer is a third-party solution, I don't know all the internals. With an example file it would be much easier to check.

**Comment by tomerel22** [comment]
[Trash.zip](https://github.com/kovacsv/Online3DViewer/files/7668533/Trash.zip)
example - fbx file with rgb textures

**Comment by tomerel22** [comment]
Is it possible?

**Comment by kovacsv** [comment]
I've check, and the FBX imported doesn't handle RGB files, so you have to convert them to some other format. Supperted texture fromats: bmp, jpg, png, tif or tga.

**Comment by tomerel22** [comment]
Thanks!

**Comment by tomerel22** [comment]
I've tried to convert it to jpg and png but it doesn't recognize it as part of the fbx textures.

**Comment by kovacsv** [comment]
The FBX file refers to these textures by name (black.rgb and green_3.rgb), so simply converting them to jpg won't work. You have to resave your FBX file to refer to the new textures with the proper extension (e.g. black.png and green_3.png).
