### ISSUE TITLE
Pan function

### ISSUE THREAD

**Issue by whiteonion** [kovacsv/Online3DViewer#18]
Hi, Love the app you made <3 just amazing.

Could you please consider adding a PAN function? Really, that's really important, to be able to view a 3d model , you need two things. One is to zoom in and out (which you have), and the other is to PAN, so - move the center of the screen around (move thru the object). It's a really really really basic option and the lack of which kind of makes your app unusable for real life situations. Which is a shame, since it's a really amazingly well done and simple app to use

Please consider adding a PAN option, (PAN, move, call it what you want), It's a must have feature to be able to really use the app properly.

Thanks! :)

**Comment by kovacsv** [comment]
Right mouse button :)

**Comment by whiteonion** [comment]
Figured it out haha … tnx :D 


On September 27, 2019 at 4:59:07 PM, Viktor Kovacs (notifications@github.com) wrote:

Right mouse button :)
