### ISSUE TITLE
3dviewer.net cannot open glTF models from GitHub release URLs

### ISSUE THREAD

**Issue by lassoan** [kovacsv/Online3DViewer#186]
First of all thank you for this phenomenal software! We plan to use this for sharing anatomical atlases for medical education.

The live demo site works great, but I cannot seem to use it with glTF files stored as GitHub release assets. Storing models as release assets is nice because there is no network bandwidth limit, files can be very large, and the files are stored separately from the source code.

Example:

This URL does not work ("Something went wrong. Failed to load file for import." error is displayed):
https://3dviewer.net/#model=https://github.com/PerkLab/SlicerOpenAnatomy/releases/download/SampleData/SPL-Abdominal-Atlas.gltf

The same file can be viewed in this URL:
https://3dviewer.net#model=https://raw.githubusercontent.com/lassoan/Test/master/SPL-Abdominal-Atlas.gltf

It would be also nice if the download URL style would work, too (but this is not that important because we can manually create the raw.githubusercontent.com URLs). For example, this URL does not work ("Something went wrong. Failed to load file for import." error is displayed):
https://3dviewer.net#model=https://github.com/lassoan/Test/raw/master/SPL-Abdominal-Atlas.gltf

**Comment by GitHubDragonFly** [comment]
If you open the browser's console window it will show you the exact error:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://github.com/PerkLab/SlicerOpenAnatomy/releases/download/SampleData/SPL-Abdominal-Atlas.gltf. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

GitHub does allow accessing RAW files as in your second URL.

**Comment by kovacsv** [comment]
@GitHubDragonFly is right, this is a typical CORS issue. You should figure out how to generate a url from releases that allows CORS requests.

**Comment by kovacsv** [comment]
For the second part of the question, github urls are automatically converted now to a usercontent url, but it happens behind the open url dialog. I've created #188 to make it work automatically everywhere.

**Comment by lassoan** [comment]
Thanks for all the answers and the Github url conversion fix.

Is the inability to load from `https://github.com/(organization)/(project)/releases/download/(releasename)/(filename)` URL a 3dviewer.net server configuration issue? Would you need to set the server configuration to allow loading of mesh files from such URLs? Could this be enabled or there a specific reason why this would be unsafe or hard to do?

**Comment by kovacsv** [comment]
No, CORS requests should be allowed on the server where the model is stored (in this case on the GitHub server). So it has nothing to do with the 3dviewer.net configuration, it seems that GitHub doesn't allow CORS requests to the files in releases (or at least not with the url you mentioned).

More details about CORS: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by lassoan** [comment]
Thanks a lot for the explanation.

Probably this is trivial for web developers, but it may make sense to spell it out in the FAQ for people who just wants to use the viewer.

**Comment by kovacsv** [comment]
Since the release access is not a viewer issue, and the other one is handled in a different issue, I close this one.
