### ISSUE TITLE
How to set Free Orbit to the default mode

### ISSUE THREAD

**Issue by Slicerfan** [kovacsv/Online3DViewer#187]
After initializing the viewer, how to set Free Orbit to the default mode and how to modify the code

**Comment by kovacsv** [comment]
You can access `Viewer` objects after initializing them. You can see the details here in the Customization section: https://github.com/kovacsv/Online3DViewer/wiki/Use-the-Viewer-on-Your-Website

After you have the viewer object, call the `viewer.SetFixUpVector (true/false);` function.

**Comment by Slicerfan** [comment]
> You can access `Viewer` objects after initializing them. You can see the details here in the Customization section: https://github.com/kovacsv/Online3DViewer/wiki/Use-the-Viewer-on-Your-Website
> 
> After you have the viewer object, call the `viewer.SetFixUpVector (true/false);` function.

I'm very sorry, I don't know much about scripts, can you tell me specifically where should I put this code?I believe this is a very easy thing for you

**Comment by kovacsv** [comment]
Do you want to use the whole website, or just embed the engine as a viewer?

**Comment by Slicerfan** [comment]
> Do you want to use the whole website, or just embed the engine as a viewer?

I just want to use the entire website as an offline viewer to facilitate the viewing of local models. Then every time after loading the model, I need to adjust the free orbit separately.

**Comment by kovacsv** [comment]
You can do this by this modification in the `website.js` file:

```diff
diff --git a/website/o3dv/js/website.js b/website/o3dv/js/website.js
index 0660d1a..93b2659 100644
--- a/website/o3dv/js/website.js
+++ b/website/o3dv/js/website.js
@@ -521,13 +521,14 @@ OV.Website = class
             this.viewer.FlipUpVector ();
         });
         AddSeparator (this.toolbar, ['only_on_model']);
-        AddRadioButton (this.toolbar, this.eventHandler, ['fix_up_on', 'fix_up_off'], ['Fixed up vector', 'Free orbit'], 0, ['only_on_model'], (buttonIndex) => {
+        AddRadioButton (this.toolbar, this.eventHandler, ['fix_up_on', 'fix_up_off'], ['Fixed up vector', 'Free orbit'], 1, ['only_on_model'], (buttonIndex) => {
             if (buttonIndex === 0) {
                 this.viewer.SetFixUpVector (true);
             } else if (buttonIndex === 1) {
                 this.viewer.SetFixUpVector (false);
             }
         });
+        this.viewer.SetFixUpVector (false);
         AddSeparator (this.toolbar, ['only_full_width', 'only_on_model']);
         AddButton (this.toolbar, this.eventHandler, 'export', 'Export model', ['only_full_width', 'only_on_model'], () => {
             let exportDialog = new OV.ExportDialog ({
```

**Comment by Slicerfan** [comment]
Thank you very much !

**Comment by Slicerfan** [comment]
> You can do this by this modification in the `website.js` file:
> 
> ```diff
> diff --git a/website/o3dv/js/website.js b/website/o3dv/js/website.js
> index 0660d1a..93b2659 100644
> --- a/website/o3dv/js/website.js
> +++ b/website/o3dv/js/website.js
> @@ -521,13 +521,14 @@ OV.Website = class
>              this.viewer.FlipUpVector ();
>          });
>          AddSeparator (this.toolbar, ['only_on_model']);
> -        AddRadioButton (this.toolbar, this.eventHandler, ['fix_up_on', 'fix_up_off'], ['Fixed up vector', 'Free orbit'], 0, ['only_on_model'], (buttonIndex) => {
> +        AddRadioButton (this.toolbar, this.eventHandler, ['fix_up_on', 'fix_up_off'], ['Fixed up vector', 'Free orbit'], 1, ['only_on_model'], (buttonIndex) => {
>              if (buttonIndex === 0) {
>                  this.viewer.SetFixUpVector (true);
>              } else if (buttonIndex === 1) {
>                  this.viewer.SetFixUpVector (false);
>              }
>          });
> +        this.viewer.SetFixUpVector (false);
>          AddSeparator (this.toolbar, ['only_full_width', 'only_on_model']);
>          AddButton (this.toolbar, this.eventHandler, 'export', 'Export model', ['only_full_width', 'only_on_model'], () => {
>              let exportDialog = new OV.ExportDialog ({
> ```

Thank you very much !

**Comment by kovacsv** [comment]
You're welcome! 👍

**Comment by zanovis** [comment]
Hey @kovacsv, what do you think about changing the default orbit to Free Orbit for the hosted version of 3DViewer? It's a bit more intuitive than Fixed Vector Orbit and I think would improve the user experience.

**Comment by zanovis** [comment]
Or could Free/Fixed Orbit be in user preferences/cookies?

**Comment by kovacsv** [comment]
It's a matter of personal preference, I like the fixed up version better. But that's a good idea to store it in cookies so it will be preserved between sessions. I'll do it for the next release: #425.
