### ISSUE TITLE
Automatically render picture

### ISSUE THREAD

**Issue by tomerel22** [kovacsv/Online3DViewer#190]
Can I use the code to export a rendering image automatically when the model is loaded?

**Comment by kovacsv** [comment]
Do you want to use the whole website, or just embed the engine?

**Comment by tomerel22** [comment]
Just embed the engine.

**Comment by kovacsv** [comment]
You can access the viewer instances after initialization. The png export code should look something like this:
```js
OV.Init3DViewerElements (function (viewers) {
    let firstViewer = viewers[0].viewer;

    // get image data as url
    let url = firstViewer.GetImageAsDataUrl (800, 600);

    // save image data to file
    OV.DownloadUrlAsFile (url, 'model.png');
});
```

**Comment by kovacsv** [comment]
Hope the answer helped, feel free to reopen the issue if you have further questions.
