### ISSUE TITLE
Detect "Dirty" or "Pristine" state of the engine

### ISSUE THREAD

**Issue by cax-tech** [kovacsv/Online3DViewer#197]
Hi,

Is there a way to detect if the loaded 3d model is not panned, rotated or zoomed? I would like to display a "reset view" button only if the user has modifed the camera. Is this currently possible?

**Comment by kovacsv** [comment]
Hi, There is no API at the moment for this. As a workaround you can add some event listeners to your canvas.

It's sure that the user did some navigation in one of these cases:
- Mouse move happens while a mouse button is down.
- A mouse wheel event happens.
- Touch move happens.

**Comment by cax-tech** [comment]
Much thanks! This should work! Will close this for now. I'll re-open this with doubts if I am really stuck. For now, looks straightforward.
