### ISSUE TITLE
fbx files

### ISSUE THREAD

**Issue by IgorBim** [kovacsv/Online3DViewer#198]
When I upload a colored fbx file it becomes black and white. Why?

**Comment by kovacsv** [comment]
Please attach the problematic file to help checking the issue.

**Comment by IgorBim** [comment]
Here it is.

    On Tuesday, December 28, 2021, 04:33:43 PM GMT+3, Viktor Kovacs ***@***.***> wrote:  
 
 


Please attach the problematic file to help checking the issue.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kovacsv** [comment]
I can't see any attachments, please try to attach it on GitHub.

**Comment by IgorBim** [comment]
For some reason github refuses to accept zip files.

    On Tuesday, December 28, 2021, 04:48:24 PM GMT+3, Viktor Kovacs ***@***.***> wrote:  
 
 


I can't see any attachments, please try to attach it on GitHub.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kovacsv** [comment]
Try to upload it on GitHub, and not by replying to the e-mail.

**Comment by IgorBim** [comment]
Again and again, for some reason github refuses to accept zip files.
And it does not accept fbx files too.

**Comment by kovacsv** [comment]
Then try dropbox, or any other file sharing service.

**Comment by kovacsv** [comment]
Closing this since no file arrived.
