### ISSUE TITLE
3dviewer.net as a 3d pastebin?

### ISSUE THREAD

**Issue by d33tah** [kovacsv/Online3DViewer#2]
It would be great if one could upload a file (or point to it) and have it loaded automatically, sort of like 3d version of pastebin or imgur. Is this doable?

**Comment by kovacsv** [comment]
Good idea, I will think about it, but it seems to be a huge project :)

By the way you can use the viewer with self-hosted models. Take a look at the embeddable folder where you can find examples on it.

**Comment by d33tah** [comment]
Huge? Why would it be? Most of the code seems to already be there, the only thing left would be to have a way to load files from some external URL.

**Comment by kovacsv** [comment]
Yes, its true. But I think this solution should store the models in its own server, so the server side should be implemented. But yes, maybe not huge, just big :)

**Comment by d33tah** [comment]
How about adding the first step of not worrying about hosting and just pulling the resource from somewhere else? Would it be big as well?

**Comment by d33tah** [comment]
One could delegate this problem to the hoster - just have the user enter a URL that works over cross-origin ;)

**Comment by kovacsv** [comment]
I'll give it a try. If you interested, feel free to callaborate on this task.

**Comment by kovacsv** [comment]
It seems working now :)
http://3dviewer.net#https://cdn.rawgit.com/kovacsv/Online3DViewer/9e9ca71d/website/testfiles/cube.3ds
