### ISSUE TITLE
Ability to specify extension when the extension is not part of the url

### ISSUE THREAD

**Issue by agusmdev** [kovacsv/Online3DViewer#202]
Hi, I'm trying to render .gltf objects from ipfs, but the engine can't process the file. Although it can process exactly the same file from another source:
E.g: 
it works correctly here: https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/DamagedHelmet/glTF-Embedded/DamagedHelmet.gltf
it doesn't work here: https://ipfs.io/ipfs/QmVzbVRXNr46NRhkjifUjxGj9KcfXUiMYvHTxYcW2h74A4
But when I get those links from the browser, both are exactly the same.

P.S: I don't think this is a CORS issue

**Comment by agusmdev** [comment]
Well I figured it out, it is an extension problem, the engine does not know how to read my file since the filename/extension is not in the URL, to solve this I hardcoded "gltf" as a default value when it can't infer the extension, but it could be great to somehow have the option for sending the extension before rendering the object

**Comment by ahmedsadman** [comment]
Hello @kovacsv, for production use cases, it's not always possible to have the extension in the download file URL. I have a project where we're trying to use this library and this is a major obstacle. We can have another variant for `LoadModelFromUrl` where we can specify the extension alongside the model URL. If possible, please look into this with a higher priority. Thank you.

**Comment by kovacsv** [comment]
From the next release it will be possible to provide file names along with urls:
```js
let inputFiles = [
    new OV.InputFile ('hundred_cubes.obj', OV.FileSource.Url, '../../test/testfiles/obj/hundred_cubes_noext_obj'),
    new OV.InputFile ('hundred_cubes.mtl', OV.FileSource.Url, '../../test/testfiles/obj/hundred_cubes_noext_mtl')
];
viewer.LoadModelFromInputFiles (inputFiles);
```
