### ISSUE TITLE
Detect if 3d model is rendered

### ISSUE THREAD

**Issue by dbinoj** [kovacsv/Online3DViewer#203]
Hi,

Thank you for your work on this.

I am using embeded viewer engine in my page. I would like to run some javascript code once the 3d object is loaded, rendered and displayed to the user. Can you please help me on how do I listen to this event? I have small to large 3d objects so putting it on a timer is not an option.

**Comment by kovacsv** [comment]
At the moment it's not possible, but you can grab the code for embedding, and modify it as you want. Just use this code in your website, and modify the `onModelFinished` function:
https://github.com/kovacsv/Online3DViewer/blob/master/source/viewer/embeddedviewer.js

**Comment by dbinoj** [comment]
I was using the minnified release js so this was not possible. Was wondering if we could listen to this "onModelFinished" from .viewer of the OV object.

The crude workaround I did was to poll `dom_element.viewer.renderer.info.render.calls`. Calls became non-zero the moment something was rendered on screen.

I will try using the source code and modifying it as that seems "less hacky" than my crude solution :)

**Comment by kovacsv** [comment]
You can use the minified code, and add this one in your own javascript, so the original class will be rewritten with your version. Or you can rename it to anything you want and use it.

**Comment by dbinoj** [comment]
Understood! Thanks!
