### ISSUE TITLE
Script loading ignores base URL

### ISSUE THREAD

**Issue by nikita-fuchs** [kovacsv/Online3DViewer#205]
This used to work in the past. But now if the webpage is deployed somewhere with a base URL, lazy-loaded scripts won't load. Example:

The URL of a failing request is
`https://storage.googleapis.com/libs//three_loaders/fflate.min.js` , whereas the correct path for this script would be `https://storage.googleapis.com/d-pipeline-307710.appspot.com/staging/web-static/libs/three_loaders/fflate.min.js`, so the whole base URL `d-pipeline-307710.appspot.com/staging/web-static` is missing in the path of the failing request.

It's a bit strange also that the double slashes in the wrong URL are after libs, not after .com as it should be when simply removing the base URL.

**Comment by kovacsv** [comment]
You can set the external libs location by modifying the value of the `ExternalLibLocation` variable. Maybe this is missing in your case. For example:
```js
OV.ExternalLibLocation = '../libs';
```

**Comment by nikita-fuchs** [comment]
Thanks, tweaking around with that did the trick for me.
