### ISSUE TITLE
Running the app

### ISSUE THREAD

**Issue by tomerel22** [kovacsv/Online3DViewer#207]
How can I running the app when I download him to my server? 
I'm writing in the cmd:
1.npm install 
2.npm start
I don't get the 3d viewer net

**Comment by kovacsv** [comment]
What happens when you open `http://localhost:8080/website` in your browser?
https://github.com/kovacsv/Online3DViewer/wiki/Set-Up-the-Development-Environment

**Comment by tomerel22** [comment]
![image](https://user-images.githubusercontent.com/80748720/149179843-fb24f1b9-6f2c-49c3-8ce0-1a1a107bfaab.jpeg)![image](https://user-images.githubusercontent.com/80748720/149179882-f3cc5b15-6bf3-4e81-a42c-3ad3be7eb943.jpeg)![image](https://user-images.githubusercontent.com/80748720/149179936-a112aabf-d7be-42f9-b944-8c65761ec635.jpeg)

**Comment by kovacsv** [comment]
That's strange. What about `http://127.0.0.1:8080/website/`?

**Comment by tomerel22** [comment]
Same😅
![image](https://user-images.githubusercontent.com/80748720/149180825-3ca21e7e-b6b6-4591-be92-6afcef51956e.jpeg)

**Comment by kovacsv** [comment]
Maybe it's something with your http-server installation? Try deleting the `node-modules` folder, and running `npm install` again.

**Comment by tomerel22** [comment]
Thanks!
