### ISSUE TITLE
PNG Transparency

### ISSUE THREAD

**Issue by A2va** [kovacsv/Online3DViewer#21]
With some file containing a transparency it happens
![image](https://user-images.githubusercontent.com/49582555/70346967-ca1bca00-185f-11ea-8ccf-1451f497ec48.png)
Is it possible to correct that?

**Comment by kovacsv** [comment]
Can you please provide the files so I can check it?

**Comment by A2va** [comment]
These are these files

[Files.zip](https://github.com/kovacsv/Online3DViewer/files/3935324/Files.zip)

**Comment by kovacsv** [comment]
There is a quick workaround. Set the relevant materials slightly transparent so it will be rendered as a transparent surface. Put the following line in the mtl file:
```
d 0.99
```

With this I get the following result:
![image](https://user-images.githubusercontent.com/2034315/112746181-9cefaf80-8fad-11eb-948b-79efddbafcfa.png)

**Comment by A2va** [comment]
Ok, thanks for your tip !
