### ISSUE TITLE
Chrome version ifc viewer

### ISSUE THREAD

**Issue by tomerel22** [kovacsv/Online3DViewer#211]
Is it possible to fix the problem that the web-ifc doesn't support Chrome V68?
Thanks!

**Comment by kovacsv** [comment]
Chrome V68 is three years old, I don't have plans to support such an old browser.

**Comment by tomerel22** [comment]
So do you have an idea what can I do for supporting chrome 68?

**Comment by kovacsv** [comment]
Do you see any error messages in the browser console?

**Comment by tomerel22** [comment]
No, the app just leaves the model loading screen

**Comment by kovacsv** [comment]
I'm sure that some error messages appear in the browser console. Try to open developer tools in your browser, and check the console.

**Comment by tomerel22** [comment]
Uncaught (in promise) RunTimeError: memory access out of bounds 
 at wasm-function[843]:34
 at wasm-functions[506]:1
 at Modules.__wasm_calls_ctors

**Comment by kovacsv** [comment]
Seems like it has something to do with webassembly support in that ancient version of Chrome. Since web-ifc is completely webassembly-based, I don't think there is a solution. The only way is to update Chrome.
