### ISSUE TITLE
Layer names not visible 3MF

### ISSUE THREAD

**Issue by petrsoudek** [kovacsv/Online3DViewer#213]
**Describe the bug**
There is "No Name" instead the layer name when loading a model via 3mf format

**To Reproduce**
Load any 3mf file

**Screenshots**
<img src="https://user-images.githubusercontent.com/73063058/151148681-848cdeac-48f7-42c8-81f2-4781de9118cc.png" width="300">

**Comment by kovacsv** [comment]
It's already merged, so it will arrive with the next three.js update.
