### ISSUE TITLE
Unable to load model from URL

### ISSUE THREAD

**Issue by sumu327** [kovacsv/Online3DViewer#215]
**Describe the bug**
Unable to load model from URL

**Screenshots**
![1644560772(1)](https://user-images.githubusercontent.com/97350430/153546215-a07b2d74-9490-404b-95bf-467c0b9a09da.png)

**Comment by kovacsv** [comment]
Probably a CORS issue, see the FAQ for details:
https://3dviewer.net/info/faq.html

**Comment by sumu327** [comment]
I'm at 3dviewer Net using the link provided by the official document, it still can't be loaded
Everything was normal when I tested yesterday, but not when I tested today
![image](https://user-images.githubusercontent.com/97350430/153552851-31407a83-3379-4c1f-a23e-42f943d4a932.png)
![image](https://user-images.githubusercontent.com/97350430/153552893-42ce5727-ce75-44b5-9473-2461390a096d.png)

**Comment by kovacsv** [comment]
Please try to do a clean refresh of the page (Ctrl+Click Refresh button on Chrome, Ctrl+F5 on Firefox).
