### ISSUE TITLE
Displaying ifc 4

### ISSUE THREAD

**Issue by tomerel22** [kovacsv/Online3DViewer#217]
Hi! I'm trying to display some ifc 4 models, the viewer doesn't display the walls of the models. 
I can display ifc 2x3 model but ifc 4 doesn't work well.
![image](https://user-images.githubusercontent.com/80748720/153746661-60907c4d-8bd8-4697-90ba-74220a3ba192.jpeg)

**Comment by kovacsv** [comment]
Most probably a [web-ifc](https://github.com/tomvandig/web-ifc) issue, I recommend to report it there.
