### ISSUE TITLE
Embed Viewer - Missing mesh on 3dm file

### ISSUE THREAD

**Issue by Kaaly** [kovacsv/Online3DViewer#223]
I have an issue when i embed the viewer engine in my own website.

I follow exactly this wiki : https://github.com/kovacsv/Online3DViewer/wiki/Embed-the-Viewer-Engine

I tried with "hundred_cubes.obj" file and it work fine on my own website.

But when i tried with my own file i got this error : 
Failed to import model. (The model doesn't contain any meshes.)

Firstly, i think my file was wrong but i tried exactly the same file on https://3dviewer.net/ and it work fine.

File : https://www.dropbox.com/s/6ipuoqguxyineh8/test.3dm?dl=0
Test on 3dviewer.net : https://3dviewer.net/#model=https://www.dropbox.com/s/6ipuoqguxyineh8/test.3dm?dl=0

Any idea why this file is working on 3dviewer.net but not on my own website ?

**Comment by kovacsv** [comment]
Yes, the error message could be better in this case. The engine probably doesn't find the rhino loader library. I extended the documentation on how to resolve this.

Please check the end of this document:
https://github.com/kovacsv/Online3DViewer/wiki/Embed-the-Viewer-Engine

**Comment by Kaaly** [comment]
Nice it's working now, thanks for your quick answer
