### ISSUE TITLE
How can I embe the viewer engine in my Vue project

### ISSUE THREAD

**Issue by irongiants** [kovacsv/Online3DViewer#232]
hi guys,
I want use this 3dviewer engine in my project based Vue2.6.10,
How to write the code in my vue file?
Obviously it doesn't work to code like below:
`<template>
  <div id="viewer"
  ></div>
</template>
<script>
import * as THREE from 'o3dv_0.8.9/three.min'
import { OV } from 'o3dv_0.8.9/o3dv.min'

export default {
  name: '3Dviewer',
  mounted() {
    window.addEventListener('load', () => {
      // get the parent element of the viewer
      let parentDiv = document.getElementById('viewer')

      // initialize the viewer with the parent element and some parameters
      let viewer = new OV.EmbeddedViewer(parentDiv, {
        camera: new OV.Camera(
          new OV.Coord3D(-1.5, -3.0, 2.0),
          new OV.Coord3D(0.0, 0.0, 0.0),
          new OV.Coord3D(0.0, 0.0, 1.0)
        ),
        backgroundColor: new OV.Color(255, 255, 255),
        defaultColor: new OV.Color(200, 200, 200),
        edgeSettings: {
          showEdges: false,
          edgeColor: new OV.Color(0, 0, 0),
          edgeThreshold: 1,
        },
        environmentMap: [
          '/website/assets/envmaps/grayclouds/posx.jpg',
          '/website/assets/envmaps/grayclouds/negx.jpg',
          '/website/assets/envmaps/grayclouds/posy.jpg',
          '/website/assets/envmaps/grayclouds/negy.jpg',
          '/website/assets/envmaps/grayclouds/posz.jpg',
          '/website/assets/envmaps/grayclouds/negz.jpg',
        ],
      })
      // load a model providing model urls
      viewer.LoadModelFromUrls([
        '../../test/testfiles/obj/hundred_cubes.obj',
        '../../test/testfiles/obj/hundred_cubes.mtl',
      ])
    })
  }, 
}
</script>`
 

best regards

**Comment by kovacsv** [comment]
What do you mean by "doesn't work"? What happens? Do you see any error messages in the browser control?

**Comment by irongiants** [comment]
> What do you mean by "doesn't work"? What happens? Do you see any error messages in the browser control?
tks for comment.
if my code like this :
import * as THREE from 'o3dv_0.8.9/three.min'
import { OV } from 'o3dv_0.8.9/o3dv.min'
then the build error is  :
 ERROR  Failed to compile with 1 errors                                                                    


 error  in ./node_modules/o3dv_0.8.9/o3dv.min.js

Module parse failed: Unexpected token (1:5947)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. S
ee https://webpack.js.org/concepts#loaders
> var OV=(()=>{var vi=Object.defineProperty;var On=Object.getOwnPropertyDescriptor;var Bn=Object.getOwnPropertyNames;var
 Ln=Object.prototype.hasOwnProperty;var Un=(s,e)=>{for(var t in e)vi(s,t,{get:e[t],enumerable:!0})},zn=(s,e,t,r)=>{if(e&
&typeof e=="object"||typeof e=="function")for(let i of Bn(e))!Ln.call(s,i)&&i!==t&&vi(s,i,{get:()=>e[i],enumerable:!(r=O
n(e,i))||r.enumerable});return s};var _n=s=>zn(vi({},"__esModule",{value:!0}),s);var kn={};Un(kn,{AddCoord2D:()=>Yi,AddC
oord3D:()=>Br,AddDiv:()=>bn,AddDomElement:()=>Bi,ArrayBufferToAsciiString:()=>Zi,ArrayBufferToUtf8String:()=>J,ArrayToCo
...

I guess the two js files are not  modularized  as ES6 moduls ,so I can not use 'import'  to import them.

**Comment by xunchangchang** [comment]
I put files such as occt-import-js.js into the public folder

![image text](https://user-images.githubusercontent.com/87689435/161369453-a9c6b205-466a-41fc-9d55-57c9b7e860cb.png)

![image text](https://user-images.githubusercontent.com/87689435/161369480-8eee9344-1c5c-48c1-88d4-afea0ef1d09a.png)

**Comment by kovacsv** [comment]
Yes, the problem here probably is that the build is not an ES6 module. I've created #238 to resolve this.

In the meantime you can probably use `require` to load the module. Here is some experiment I've done before with this solution: https://github.com/kovacsv/Online3DViewer/blob/master/sandbox/node_example/example.js

**Comment by irongiants** [comment]
I see,Thanks a lot!
