### ISSUE TITLE
STP import: Incomplete display of meshes names and colors

### ISSUE THREAD

**Issue by xunchangchang** [kovacsv/Online3DViewer#237]
![image text](https://user-images.githubusercontent.com/87689435/161369194-f6ace8fe-f44d-4904-b492-0b7ad1792e2c.png)
![image text](https://user-images.githubusercontent.com/87689435/161369230-28c69b7b-f437-4807-9de3-2a60a04cad80.png)

**Comment by xunchangchang** [comment]
And I found that the mesh that can't get the name can't get its color

**Comment by kovacsv** [comment]
Could you please attach the step file?

**Comment by kovacsv** [comment]
I close this since no response arrived.
