### ISSUE TITLE
"Something went wrong" when uploading STP file

### ISSUE THREAD

**Issue by chriskuech** [kovacsv/Online3DViewer#239]
**Describe the bug**

Attempting to upload certain .stp files yields this screenshot below.

**To Reproduce**

Unfortunately, while I can confirm the site works for some STP files, I legally cannot share the one that it fails on. Let me know if there's anything I can do to help identify the repro.

**Expected behavior**

The .stp file renders like the others.

**Screenshots**

<img width="478" alt="image" src="https://user-images.githubusercontent.com/3680671/161587684-aea0d3da-a000-4bb4-b964-5214a64a3283.png">

**Comment by kovacsv** [comment]
Could you please attach the stp file?

**Comment by chriskuech** [comment]
> I legally cannot share the one that it fails on
Unfortunately, no.  Is there any more error throwing or logging you can add and I can send you the resulting info?

**Comment by kovacsv** [comment]
Do you see any errors in the browser console?

**Comment by kovacsv** [comment]
Hard to say anything without the file itself. My best guess that it is an assembly file that references other files, and currently assemblies are not supported.

**Comment by chriskuech** [comment]
Is there anything I can Ctrl+F for in the file to prove/disprove this?

**Comment by kovacsv** [comment]
Try searching for `.stp` or `.step` in the file to see if it references other files.

**Comment by chriskuech** [comment]
I'm not finding any references like that.  In the header, I see a `FILE_SCHEMA`... could the kind of unresolvable reference you're looking for?

<img width="476" alt="image" src="https://user-images.githubusercontent.com/3680671/163475392-393cba81-d88c-4617-839d-d6b6c57e85a9.png">

**Comment by kovacsv** [comment]
Sorry, I don't think I can manage to solve the issue without the file. Please try to reproduce the issue with a simplified example that you can share.

**Comment by chriskuech** [comment]
Is it possible that, rather than seeing an exception that would be logged, we are hitting a timeout?

The problematic file is 74MB?
