### ISSUE TITLE
Load File Hash URL Method Not Working

### ISSUE THREAD

**Issue by 6Hat** [kovacsv/Online3DViewer#24]
First of all, thank you for the fantastic project! I am having issues loading files using the hash method. Maybe because I am using localhost in testing? Here is an example I am trying:
file:///C:/Users/fybin/Desktop/CEASEFIRE_CFF800ULarchitecture350/Online3DViewer-master/Online3DViewer-master/website/index.html/#testfiles/CFF.3ds

Thank you for your help!

**Comment by kovacsv** [comment]
Hi 6Hat,

Yes, it's because you are using localhost. For security reasons browsers don't allow you to load a file from a different location. Install some kind of web server for testing.

Regards,
Viktor

**Comment by 6Hat** [comment]
Thank you for your help! Sorry to be dense, I am still missing something. Here it is live with both the fully qualified url:
https://ceasefire.com/Assets/3DViewer/website/index.html/#https://ceasefire.com/Assets/3DViewer/website/testfiles/CFF.3ds
And the relative:
https://ceasefire.com/Assets/3DViewer/website/index.html/#testfiles/CFF.3ds

**Comment by kovacsv** [comment]
For me the file doesn't exist so I can't check, but probably I see the error now. Please try to delete the '/' character after index.html like this:

https://ceasefire.com/Assets/3DViewer/website/index.html#testfiles/CFF.3ds
