### ISSUE TITLE
glB material import not displaying correctly

### ISSUE THREAD

**Issue by zaknelson64** [kovacsv/Online3DViewer#248]
Materials imported from glB file with 8 materials using Base Color, Normal, and Occlusion roughness Metallic textures appear overexposed and over saturated. This has been tested in both Chrome and Edge. Model looks fine on glB import into Unity or Blender.

File: https://drive.google.com/file/d/1scyAtCzVLw8_aQv4mHDQY5JIV8jK6mnI/view?usp=sharing

Online3D Viewer:
![image](https://user-images.githubusercontent.com/103941500/163814193-9aa39fe3-5b41-4e78-95d0-c459315e3b02.png)

Unity(Ignore model changes, just note texture changes):
![image](https://user-images.githubusercontent.com/103941500/163814102-90e697ad-598b-4526-b27b-029870d4cbfa.png)

**Comment by kovacsv** [comment]
Could you please attach a glb file to reproduce the issue?

**Comment by zaknelson64** [comment]
This file was exported using Blender's built in glTF exporter with textures made using substance designer. I didn't the file in my post originally because Github doesn't allow attaching glB files. 

Here's a link to the file on google drive:
https://drive.google.com/file/d/1scyAtCzVLw8_aQv4mHDQY5JIV8jK6mnI/view?usp=sharing

**Comment by kovacsv** [comment]
The problem was that the model contains vertex colors, but it wasn't handled properly. Now it looks much better, the fix is planned for the next release.

![image](https://user-images.githubusercontent.com/2034315/164051505-537b1df8-10b1-4b04-ab69-21e0b1ed59b2.png)

**Comment by zaknelson64** [comment]
What can be done to ensure vertex colors are handled properly when exporting? Is it in the shader setup? Some of the vertexes were not assigned vertex color

**Comment by kovacsv** [comment]
I'm not familiar with Blender, but I think if you remove all vertex colors it will look good in the viewer even without this fix.

**Comment by zaknelson64** [comment]
Thanks for the info. So currently no solution that includes vertex colors?

**Comment by zaknelson64** [comment]
Thank you for the info.
