### ISSUE TITLE
show off file

### ISSUE THREAD

**Issue by jiangyanjavawin** [kovacsv/Online3DViewer#25]
Hello sir,Thanks for your code,I study your code for several day,but i still don't know how to show stable off file,and not load off file.If you have any idea,please let me know,Thank you very much.

**Comment by kovacsv** [comment]
Hello! Please clarify a bit what you would like to achieve. For me off files works the same as other file formats: https://3dviewer.net/#testfiles/prism.off

Please note that only textual off files are supported, binary off doesn't work at the moment.

**Comment by jiangyanjavawin** [comment]
hello sir,the issue i faced is I want to change the canvas's sourcefile value by js,here is my js code,

		function Onchange(){
			var canvas = document.getElementById ('fullscreen');
			canvas.sourcefiles = "testfiles/prim.off";
		}
		
here is the canvas code.
<canvas id="fullscreen" class="3dviewer" sourcefiles="" width="200" height="200"></canvas>
when i run by this is work,<canvas id="fullscreen" class="3dviewer" sourcefiles=""testfiles/prim.off"" width="200" height="200"></canvas>
but i want to get the sourcefile's value by js,Do you have any solution?Thank you very much.

**Comment by kovacsv** [comment]
In the rewritten version I don't think it's relevant anymore. Please see the [developer documentation](https://github.com/kovacsv/Online3DViewer/wiki/Use-the-Viewer-on-Your-Website) on how to use it now, and let me know if I can help you achieve your goal.
