### ISSUE TITLE
Hi, how to show model information like model size on the models

### ISSUE THREAD

**Issue by WangQingye** [kovacsv/Online3DViewer#250]
thanks very much for this project, its help me a lot. and I have a question is that how can I show  the model information like model size on the models, like on X axis or Y axis ?

**Comment by kovacsv** [comment]
If you are using the website, you can just find it on the details panel:
![image](https://user-images.githubusercontent.com/2034315/164492195-ed529642-aa92-4cd9-b278-1045aade3d28.png)

**Comment by WangQingye** [comment]
> If you are using the website, you can just find it on the details panel: ![image](https://user-images.githubusercontent.com/2034315/164492195-ed529642-aa92-4cd9-b278-1045aade3d28.png)

thanks for the anwser. I found the infomations in the demo website. And now I am using the viewer in my own website, so where can I get the infomation? or which function in viewer instance can I use? thanks!

**Comment by kovacsv** [comment]
See this issue for details: #241
