### ISSUE TITLE
Make File Upload Possible in the Embedded Viewer

### ISSUE THREAD

**Issue by callum-gander** [kovacsv/Online3DViewer#253]
**Describe the solution you'd like**

I want to be able to upload files to the embedded viewer with the FileReader API, not using URLs. 

I've been trying to run the embedded viewer so that our customers upload their files, it displays each of our customers' models, calculates the volume and surface area for each and then taks a screenshot for each thumbnail. It works IF I set the model url to be one that already exists in public, e.g. ['/3dm-test.3dm'] but when I try to add a file API url, no matter how I try to convert my file, using URL.createObjectURL, reader.readAsArrayBuffer, reader.readAsDataURL, nothing works. 

I've seen mention of CORs in some of your responses but I may be mixing this up with other similar issues, I don't understand how CORs would be an issue, the od3v and three minified files are coming from my server, not a different origin.

From what I understand from the code and some of the issues I've seen, the embedded viewer is only capable of loading from Model URLs. The website seems to contain more methods than the embedded viewer, as seen in the code as well as the simple fact I can drop files into the demo website and it works fine.

 **I may have missed something so please correct me if there are existing ways to do this but could we please have the file reader methods to load models in the embedded viewer? this would enable files to be viewed by the client without having to upload a model to our server. This is crucial for our business and we'll happily start sponsoring the project if this is done**

**Comment by kovacsv** [comment]
There is no easy solution at the moment. Now I've added the `LoadModelFromFileList` function to the embedded viewer which can load files from a dialog or drag&drop. [See an example here.](https://github.com/kovacsv/Online3DViewer/blob/dev/sandbox/embed_selfhost_code_file.html)

It's available on the `dev` branch, so you can wait for the next release or [build the lib](https://github.com/kovacsv/Online3DViewer/wiki/Set-Up-the-Development-Environment) from the `dev` branch.

**Comment by callum-gander** [comment]
I built it from the dev branch and the first time I loaded the page with the viewer, it worked and the LoadModelFromFileList method is available on the viewer object. However, after a refresh, it vanishes and is as if it reverted to the previous version? I'm really not sure how this is happening, any ideas how this might be fixed?
