### ISSUE TITLE
Volume not calculated

### ISSUE THREAD

**Issue by RBELLUCO** [kovacsv/Online3DViewer#256]
**Describe the bug**
Volume not calculated, in the old 3dviewer version it was correct

**To Reproduce**
attached .STL compressed
[alfa147.zip](https://github.com/kovacsv/Online3DViewer/files/8641825/alfa147.zip)

**Expected behavior**
76.09 mm / 164.16 mm / 64.83 mm - **Volume: 182.59cm3**

**Screenshots**
![error](https://user-images.githubusercontent.com/105065861/167163717-354374e9-fb9d-48fa-a8ef-8ea360d4272f.png)

**Comment by kovacsv** [comment]
Volume can only be calculated for strictly closed meshes (only contains closed bodies, watertight, every polygon's orientation is correct according to the neighbour polygons). This model contains planar faces, so volume can't be calculated.

![model (1)](https://user-images.githubusercontent.com/2034315/167298785-356ab683-ff58-4a09-b6c1-9273556e710c.png)

What do you mean by "old 3dviewer"? Maybe this can help me investigating why it worked before.

**Comment by RBELLUCO** [comment]
Hi Viktor
I'm sorry, I got confused :(
Previously I used viewstl (another project)  and volume with same file was
calculated correctly
example: https://www.viewstl.com/classic/
Can this help you to understand if there is actually an error in the .obj
file or if it really is a bug?
Best Regards
Riccardo.

Il giorno dom 8 mag 2022 alle ore 15:38 Viktor Kovacs <
***@***.***> ha scritto:

**Comment by RBELLUCO** [comment]
Perfect!
thankyou

Il giorno lun 9 mag 2022 alle ore 17:57 Viktor Kovacs <
***@***.***> ha scritto:
