### ISSUE TITLE
MeshesPanel is displayed as a tree

### ISSUE THREAD

**Issue by xunchangchang** [kovacsv/Online3DViewer#257]
hey,You have only traversed the bottom mesh, some model meshes have a parent-child structure, and the meshes displayed by MeshesPanel can also be displayed in a tree form.
I want to know how the MeshesPanel is displayed in a tree structure when the meshes object in the json object parsed by stp has a parent-child structure. Hope to get your help.

**Comment by kovacsv** [comment]
Meshes panel can show the tree hierarchy when the model contains hierarchical data. In case of step files there is a limitation in occt-import-js that it can't read the tree structure at the moment: https://github.com/kovacsv/occt-import-js/issues/3
