### ISSUE TITLE
Send event after viewer drawn

### ISSUE THREAD

**Issue by mbulhoes** [kovacsv/Online3DViewer#26]
Would it be possible or even good idea to have the JSM.ConvertURLListToJsonData .onFinish function in LoadOnline3DModels to send an event after the viewer.Draw() call?  Would help clients track when the canvas is about to be shown.

**Comment by kovacsv** [comment]
I think it's possible and makes sense. Feel free to open a pull request!

**Comment by kovacsv** [comment]
I think it's not relevant in the current version, because the code is completely restructured.
