### ISSUE TITLE
Unable To Open STEP File After Embed the Viewer Engine To My Website

### ISSUE THREAD

**Issue by Yashpreet0** [kovacsv/Online3DViewer#262]
I have tried to Embed the Viewer Engine To My Website to view step files but it is not working for me due to an issue "Failed to import model. (Failed to load occt-import-js.)". In the console, I was getting "GET http://localhost/3dView/null 404 (Not Found)". I used the following code.

<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title>Online 3D Viewer</title>
    <script type="text/javascript" src="assets/three.min.js"></script>
    <script type="text/javascript" src="assets/o3dv.min.js"></script>
    <script type='text/javascript'>
        OV.Init3DViewerElements ();
    </script>
</head>
<body>
    <div class="online_3d_viewer"
        style="width: 800px; height: 600px;"
        model="include/sample02.step"
        camera="3,1,2,0,0,0,0,0,1"
        defaultcolor="200,0,0"
        backgroundcolor="200,200,200"
        edgesettings="off,0,0,0,1">
    </div>
</body>
</html>

I tried to fix it by importing "occt-import-js.js" but it did not work.

<script type="text/javascript" src="assets/occt-import-js.js"></script>

Can you please suggest to me how to fix this?

**Comment by kovacsv** [comment]
Probably you need to set up the location of external libraries. You can read the details at the end of this document: https://github.com/kovacsv/Online3DViewer/wiki/Embed-the-Viewer-Engine

**Comment by Yashpreet0** [comment]
Thanks for your response. I have tried this, and it is working fine for another file extension(HTC_Vive_Headset.bin, HTC_Vive_Headset.gltf) but not for the file(.step), I want to work.  

Also, I am unable to understand why it requires 2 files like the following

<div class="online_3d_viewer"
        style="width: 800px; height: 600px;"
        model="include/HTC_Vive_Headset.bin, include/HTC_Vive_Headset.gltf"
        camera="3,1,2,0,0,0,0,0,1"
        defaultcolor="200,0,0"
        backgroundcolor="200,200,200"
        edgesettings="off,0,0,0,1">
    </div>

I have only 1 file that is *.step. 
Is it possible to view with only this file?

**Comment by Yashpreet0** [comment]
Ok, I have got the point and thanks for your support
