### ISSUE TITLE
navigatormeshespanel display tree structure

### ISSUE THREAD

**Issue by heyongdong** [kovacsv/Online3DViewer#263]
Hey! I want to display the tree structure in the left menu. What format should THE STP file be transmitted after parsing?
![image](https://user-images.githubusercontent.com/23169050/167588070-f13d3c66-580e-42f1-a08f-422f2543903a.png)

![image](https://user-images.githubusercontent.com/23169050/167588071-0b242d9a-8a27-4310-8cbe-32c3d4a4d6e1.png)

Hope to get your help

**Comment by kovacsv** [comment]
It's a limitation of [occt-import-js](https://github.com/kovacsv/occt-import-js) that it can't read the tree structure from stp files: https://github.com/kovacsv/occt-import-js/issues/3
