### ISSUE TITLE
change default model color

### ISSUE THREAD

**Issue by RBELLUCO** [kovacsv/Online3DViewer#264]
Hi, when I upload 3d model, default color is gray
How to change color (rgb o hex) whithout push any button?
Thanks.

**Comment by kovacsv** [comment]
It's kind of a hidden feature, but you can specify the default color as an url parameter. For example:
https://3dviewer.net/index.html#model=assets/models/solids.obj$defaultcolor=200,0,0

**Comment by RBELLUCO** [comment]
Ok, but how can set defaultcolor when I use preview (when upload a file)?


Il dom 15 mag 2022, 09:06 Viktor Kovacs ***@***.***> ha
scritto:

**Comment by kovacsv** [comment]
What do you mean by preview?

**Comment by RBELLUCO** [comment]
When I use "drag & drop" and view render 3D.

Il dom 15 mag 2022, 14:12 Viktor Kovacs ***@***.***> ha
scritto:

**Comment by kovacsv** [comment]
If you set a color once, the browser will remember it so you don't have to set it each you use the site.

**Comment by kovacsv** [comment]
I hope the previous answer helped.

**Comment by RBELLUCO** [comment]
Perfect, but can i force color (by code) whithout set it manually?

Il dom 15 mag 2022, 14:15 Viktor Kovacs ***@***.***> ha
scritto:
