### ISSUE TITLE
ES6 Module for embedded viewer and NPM package

### ISSUE THREAD

**Issue by callum-gander** [kovacsv/Online3DViewer#266]
**Describe the solution you'd like**
The ability to download the embedded viewer as a package from NPM

Having to load the viewer and the required loaders as scripts from our public folder isn't ideal, especially given how important this viewer is for our project. We've encountered problems with it purely due to the fact that loading scripts this way doesn't meld well with the rest of our app and can create weird bugs. 

It would be a lot easier to install from NPM and import into the file where it's needed. It would also enable the possibility for intellisense and autocomplete rather than having to trawl through the source code for the specific method that's needed or console.log the viewer and look for the method there. Finally, it will help the project gain traction and reduce onboarding barriers. This 3D viewer is miles above all the others I looked at building our project, not having it available as an ES6 module feels like a waste

Not sure how it needs to be done but I'm happy to help if you want an extra pair of hands with this

**Comment by kovacsv** [comment]
I totally agree with you, and I've tried to put together a very first beta npm package. Please try it out, and let me know what you think:
https://www.npmjs.com/package/online-3d-viewer

**Comment by callum-gander** [comment]
Just downloaded it and tested it out. Works perfectly, just needed to add the Init3DViewerElements() method as you said and it works the exact same, no bugs so far. Thanks again
