### ISSUE TITLE
website index.html does nto seem to work

### ISSUE THREAD

**Issue by yvanblanchard** [kovacsv/Online3DViewer#269]
Hello,
when running the website index web page (html), nothing is dispalyed (Firefox, Windows 10). Using code version of today (2022/05/25).
It works with code from forked branch of Springtiger.

thank you.

**Comment by kovacsv** [comment]
Hope this helps: https://github.com/kovacsv/Online3DViewer/wiki/Set-Up-the-Development-Environment

**Comment by yvanblanchard** [comment]
Thank you for your reply !
ANyway, after installing and runnin, I get a black window in Viewer (Firefox borwser on Win10):

![image](https://user-images.githubusercontent.com/63931618/170487845-4659bdc7-c6bf-4cca-b5e3-e4b6e31fff36.png)

**Comment by kovacsv** [comment]
That's strange, it works for me.
- Does it work in Chrome?
- Does the live website work (https://3dviewer.net)?
- Is your Firefox updated to the latest version?

**Comment by yvanblanchard** [comment]
Hello,
It seems to work fine now after rebooting.. simple graphics issue I guess.
Thank you for your help.
