### ISSUE TITLE
Failed to open file. Maybe something is wrong with your file - File works when uploading through the interface, though?

### ISSUE THREAD

**Issue by d1m3ch** [kovacsv/Online3DViewer#27]
When trying to load a file using #folder/file.3ds method the error message "Failed to open file. Maybe something is wrong with your file." is shown.  Although, that same file loads fine if using the interface to upload.  

Using both URL and local to load the file does not work.  Permissions on the uploaded file is the same as in the examples folder.

Loading example files does work.  

Files i'm unable to load are files exported from Sketchup.  

Is there some trick i need to do to make these files work?

**Comment by kovacsv** [comment]
Have you tried it on a web server, or locally? For security reasons file loading from url doesn't work without a web server. Maybe that's the case.

**Comment by d1m3ch** [comment]
wah you reply so fast!  It's on a webserver and it's live.  Here are the links.  

3d.baystone.com#models/qg.3ds

link to file (on separate server): http://file.baystone.com/models/qg.3ds

**Comment by kovacsv** [comment]
Ok, so the file is on other web server. In this case you have to use full url:
http://3d.baystone.com/#http://file.baystone.com/models/qg.3ds

Its still doesn't work, because you have to enable cross origin requests in your file server.

**Comment by d1m3ch** [comment]
but shouldnt it work locally?  I did upload the file to the local server and try to load using the root method.  
3d.baystone.com#models/qg.3ds links to a folder /models/qg.3ds (not the separate folder).  I only uploaded to the second server to try and see if i would load via URL.

**Comment by kovacsv** [comment]
The models folder should be next to, something like this:
- index.html
- models
  - gq.3ds

**Comment by d1m3ch** [comment]
Yeap, that's exactly how it's setup.  
![image](https://user-images.githubusercontent.com/58269553/90169964-338b9b00-dd54-11ea-8008-5983e3f21d11.png)

**Comment by kovacsv** [comment]
That's strange, it seems working with the testfiles folder: http://3d.baystone.com/#testfiles/cube.3ds

**Comment by d1m3ch** [comment]
yeah, i even have the qg.3ds in the testfiles folder and set the permission and ownership exactly the same, still doesnt work

**Comment by kovacsv** [comment]
I think something is wrong with your web server. I tried to access the files directly:
- http://3d.baystone.com/testfiles/cube.3ds - works
- http://3d.baystone.com/models/qg.3ds - doesn't work

**Comment by d1m3ch** [comment]
ok checking
