### ISSUE TITLE
Section view feature

### ISSUE THREAD

**Issue by yvanblanchard** [kovacsv/Online3DViewer#271]
It would be very useful to have a section view feature in your Website viewer, such as this one ; with 'sliding' control to adjust the cutting plane location, and section 'hashing' rendering for solids/volumes.
![image](https://user-images.githubusercontent.com/63931618/170871829-4fc2c6ad-ba62-4ebc-9743-545e98e7152b.png)

**Comment by thomasjamatomics** [comment]
I vote for the same. 
I would even like to help implement and test this feature. We could start with 3 simple buttons, that cut in the three orthogonal planes through zero and a flip plane button and an offset textbox.

**Comment by yvanblanchard** [comment]
Duplicates with #91

**Comment by kovacsv** [comment]
Duplicate, I close this one.
