### ISSUE TITLE
Color-map image loading and display

### ISSUE THREAD

**Issue by yvanblanchard** [kovacsv/Online3DViewer#273]
Hello,
would it be possible to support loading and display scalar data values (mapped on mesh) as color (heat) image ?
I have a set of data (per mesh node or by triangle facet Id) and would likt to apply colors on it in viewer (like with VTK,..).
Maybe already possible using existing material data structure set ?
Thank you

![image](https://user-images.githubusercontent.com/63931618/170940595-dc9e0163-7007-44de-b18e-231d3ebff234.png)

**Comment by kovacsv** [comment]
This is outside of the scope of this viewer.
