### ISSUE TITLE
Unable to use website index.html file with npm http-server

### ISSUE THREAD

**Issue by zen253230** [kovacsv/Online3DViewer#274]
Hello !
Sorry to ask maybe a newbie question!
Starting with 0.8.4 I was unable to use online3dviewer with my Firefox as was formerly the case even through a http server
So I successfully installed npm package which launches http-server.
BUT
when browsing to website directory I get following error:

`C:\Users\XXXXX\nodejs\Online3DViewer-0.8.13\node_modules\http-server\lib\core\index.js:246`
`          stream = Readable.from(bytes)`
`                            ^`

`TypeError: Readable.from is not a function`
`    at serve (C:\Users\XXXXX\nodejs\Online3DViewer-0.8.13\node_modules\http-server\lib\core\index.js:246:29)`
`    at fs.stat (C:\Users\XXXXX\nodejs\Online3DViewer-0.8.13\node_modules\http-server\lib\core\index.js:419:13)`
`    at FSReqCallback.oncomplete (fs.js:160:5)`
`npm ERR! code ELIFECYCLE`
`npm ERR! errno 1`
`npm ERR! online-3d-viewer@0.8.13 start: `http-server``
`npm ERR! Exit status 1`
`npm ERR!`
`npm ERR! Failed at the online-3d-viewer@0.8.13 start script`

Is index.html supposed to be different?
Thank you very much!

**Comment by kovacsv** [comment]
Here is an example of using the node module:
https://github.com/kovacsv/Online3DViewerExample

Let me know if this works for you.

**Comment by zen253230** [comment]
Thank you very much for your quick answer!

Unfortunately, it doesn't work with node.js : http-server starts and displays root folder content.
Then clicking on any file or directory has no effect : server is neither responding nor showing any error, just not displaying anything but staying busy.
Progress is it does not disconnect as was the case. I'm using win32 node.js version.

Embedded browser package works perfectly but isn't there a way to show menus to select files to open or export?

**Comment by zen253230** [comment]
Precisely I have following error : "GET /website/" Error (404): "Not found"

**Comment by zen253230** [comment]
That's right !
I had a message about Python complaining it can't find `python.exe`
And yet python environment variable is set and I already ran `npm config set python C:\XXXX\python.exe`
No luck for me !

**Comment by kovacsv** [comment]
Seems like a computer setup problem, and not a problem with the library.
