### ISSUE TITLE
Rendered model looks darker compared to website

### ISSUE THREAD

**Issue by ahmedsadman** [kovacsv/Online3DViewer#276]
Code

```javascript
modelViewer.current = new OV.EmbeddedViewer(parentDiv, {
  camera: new OV.Camera(
    new OV.Coord3D(-1.5, -3.0, 2.0),
    new OV.Coord3D(0.0, 0.0, 0.0),
    new OV.Coord3D(0.0, 0.0, 1.0)
  ),
  backgroundColor: new OV.Color(255, 255, 255),
  defaultColor: new OV.Color(200, 200, 200),
  edgeSettings: {
    showEdges: false,
    edgeColor: new OV.Color(0, 0, 0),
    edgeThreshold: 1,
  },
  environmentMap: [
    '/static/model-viewer/envmaps/fishermans_bastion/posx.jpg',
    '/static/model-viewer/envmaps/fishermans_bastion/negx.jpg',
    '/static/model-viewer/envmaps/fishermans_bastion/posy.jpg',
    '/static/model-viewer/envmaps/fishermans_bastion/negy.jpg',
    '/static/model-viewer/envmaps/fishermans_bastion/posz.jpg',
    '/static/model-viewer/envmaps/fishermans_bastion/negz.jpg',
  ],
  onModelLoaded: () => {},
});
```

DamagedHelmet.glb render (my render trial):
![Screenshot 2022-06-06 at 1 11 13 PM](https://user-images.githubusercontent.com/11042267/172113204-47b4277f-958f-4721-ba1b-5b3297e8fc63.png)

DamagedHelmet.glb render (rendered in 3dviewer.net):
![Screenshot 2022-06-06 at 1 14 24 PM](https://user-images.githubusercontent.com/11042267/172113660-2abdc34c-9cf0-4edc-a0e0-15a820a7e80e.png)

Mine looks much darker compared to the one rendered in the website. How do I improve the lighting here? Also, the mouse movements are not responding properly, it seems the object is moving in correspondence of a fixed focal point.

**Comment by ahmedsadman** [comment]
@kovacsv  ^

**Comment by kovacsv** [comment]
1. The darker model is probably an environment map issue. Make sure that your environment map files exist in the given location (relative to the html page).
2. Camera works fine based on the camera settings you provided. Delete the camera parameter if you would like to fit the model to the window.

**Comment by kovacsv** [comment]
I've just realized that the documentation was outdated for the enironment map parameter. Please check this document, and update the parameter, and then it should work: https://github.com/kovacsv/Online3DViewer/wiki/Embed-the-Viewer-Engine

**Comment by ahmedsadman** [comment]
Yep, the doc was outdated. The new param structure worked as expected. Thank you
