### ISSUE TITLE
A demo for importing gltf with vue?

### ISSUE THREAD

**Issue by happy505** [kovacsv/Online3DViewer#283]
hi, i am a new with three.js and javascript and vue.. i can use official gltfLoader of three.js to load a gltf  with vue now, i wish you can make a demo to load a gltf and return the gltf.scene by using your custom loader with vue, because the display effect of yours is better than three.js loader, please, best wishes

**Comment by happy505** [comment]
![01](https://user-images.githubusercontent.com/39258679/174824205-2818a3ad-1217-4d3c-a05b-991c49264241.png)
![02](https://user-images.githubusercontent.com/39258679/174824218-12d069d5-4868-43c6-afa6-6e752d519db9.png)

as you see.. it is terrible in image 01

**Comment by kovacsv** [comment]
I'm not familiar with vue, but this tutorial helps you embedding the engine in any webpage:
https://github.com/kovacsv/Online3DViewer/wiki/Embed-the-Viewer-Engine
