### ISSUE TITLE
Adding a ground plane 

### ISSUE THREAD

**Issue by callum-gander** [kovacsv/Online3DViewer#289]
**Describe the solution you'd like**
Is it possible to add a ground plane to the model? We're displaying CAD models for manufacturing and customers are used to seeing the models with a ground plane and have requested it from us. I've looked through the embedded viewer object and can't seem to see an option, but maybe I'm missing something. If there is already an option, where would it be? If there's not, is there a way to add this as a feature?

**Comment by kovacsv** [comment]
It's not possible at the moment. Of course, it can be part of the model, but there is no feature to generate it automatically.

**Comment by callum-gander** [comment]
Thank you for your response, that makes sense. If I did a pull request to add this feature, would it be something you'd accept? If so, is there any potential guidance you could offer for you'd suggest this feature might be added? If you don't have any, I'm sure I could put something together, it'd just be best to do it the way you'd ideally like it

**Comment by callum-gander** [comment]
Thanks for the detailed reply, I'll give this ago when I have some free time in the next few weeks. Just to clarify, so you'd only accept this as a pull request if it was fully integrated with the website and not just if it was implemented only in the engine?

**Comment by kovacsv** [comment]
It's ok to do it in the engine, but it should be done in a way that can be used from the website. I would take a look at edge settings, because it should be very similar. I would introduce these settings:
- On/off state of the ground plane.
- Color of the ground plane.

**Comment by callum-gander** [comment]
In hindsight, this isn't a priority to us right now, so I don't think we'll contribute this now. We may come back to this later and implement it, but we may never do this. This may still be helpful if someone else has this issues and has the time to contribute
