### ISSUE TITLE
Upper limit of data size

### ISSUE THREAD

**Issue by daviddu2020** [kovacsv/Online3DViewer#29]
hello Kovacvs, I have one question, what is the upper limit of data size? I have tried to open a file about 700mb with this tool, it finally crash or nothing shows.
Look forward yo your reply, thank you!

**Comment by kovacsv** [comment]
Do you see any messages in the browser console?

**Comment by daviddu2020** [comment]
> Do you see any messages in the browser console?
In firefox, 
uncaught exception: out of memory
![Snipaste_2020-09-15_14-17-20](https://user-images.githubusercontent.com/71243620/93172879-42ec7280-f75e-11ea-91df-ed296c91f703.png)

**Comment by kovacsv** [comment]
Ok, that explains everything :)

Your model is just too big for the browser. I don't know any workaround, try to lower the size of your model.

**Comment by daviddu2020** [comment]
OK，thank you.
