### ISSUE TITLE
volume problem - not calculated

### ISSUE THREAD

**Issue by RBELLUCO** [kovacsv/Online3DViewer#290]
**Describe the bug**
volume problem - not calculated

**To Reproduce**
upload file.stl (from file.zip) and calculate volume
result: -

**Screenshots**
![image](https://user-images.githubusercontent.com/105065861/177560769-de31cd59-ac08-4f88-9fcb-4d33bec682cf.png)
[file.zip](https://github.com/kovacsv/Online3DViewer/files/9055100/file.zip)

Best Regards

**Comment by paireks** [comment]
Hey @RBELLUCO, is your mesh closed for 100%?

**Comment by paireks** [comment]
Hey @RBELLUCO, I checked your model in Rhino to see if it's closed mesh, and it reports me, that it's not indeed:
![2022-07-09_11h36_45](https://user-images.githubusercontent.com/47977819/178100274-78e8e538-610c-4beb-b4ad-06fcc8d03d4b.png)

In fact after some examination I think there is a chance that here is some issue:
![image](https://user-images.githubusercontent.com/47977819/178100344-bdbdf75c-25c8-467a-bfc8-4dbc39dc7fdc.png)

**Comment by RBELLUCO** [comment]
Ok, the volume calculation problem is caused by micro errors on closed mesh. is It possible to ignore this/them (perhaps by reporting it) and proceed with the calculation of the volume of the object? Thank you.

**Comment by paireks** [comment]
For Online 3d Viewer I guess it would require implementing additional feature that would detect Non-Manifold errors, and preview them in a viewer at the first place. Often modelling software have such tools to detect these issues, as it takes a lot of effort for modellers to make their geometries manifold for e.g. fabrication purposes. You can check some details regarding it here: https://sinestesia.co/blog/tutorials/non-manifold-meshes-and-how-to-fix-them/

Right now e.g. Blender can help you with it:
![2022-07-09_15h12_21](https://user-images.githubusercontent.com/47977819/178107847-808ad8d8-c9f5-4db1-8d31-7b9fc0897ba3.png)

**Comment by kovacsv** [comment]
Thank @paireks for the answer and the check. You are right, the volume can't be calculated because the mesh is not 2-manifold. The used volume calculation method (signed tetrahedrons) works only with 2-manifold meshes, otherwise the result doesn't make any sense. It can be close to reality, but can be completely wrong.

**Comment by RBELLUCO** [comment]
thank @paireks @kovacsv for answers :)

Could it be possible, once the volume problem has been detected, call a specific function (also manually) to perform an approximate calculation of the volume? I am available for any suggestions that may help me to bypass and fix error files (not 2-manifold) in micro errors on closed mesh.

Thank you.

**Comment by RBELLUCO** [comment]
Hi @paireks @kovacsv 
is it possibile integrate a separate script for fix "non manifold file" like this? (simple and very fast)
https://www.nanodlp.com/repair-3d-stl-file/
Exist a paid/free script/service that can be integrated via API or whatever?
Thank you.

**Comment by paireks** [comment]
Hey @RBELLUCO, maybe CGAL (https://www.cgal.org/index.html) has some fixing mesh capabilities. Don't know if there is some JS open-source library that does that, as JS library should probably fit Online 3D Viewer best for this task. Normally fixing is most of the time part of the modelling process. So I'm not sure if modelling tools fits Online 3D Viewer which is a viewer, that's up to Viktor to decide too I guess :)

**Comment by kovacsv** [comment]
This is outside of the scope of Online 3D Viewer at the moment.
