### ISSUE TITLE
3dm files not working in embedded NPM Module

### ISSUE THREAD

**Issue by callum-gander** [kovacsv/Online3DViewer#292]
I didn't realise this was a bug until now but 3dm files won't work in the npm version of the embedded viewer. I'm getting the error "Failed to import model. (Failed to load rhino3dm.)." 3dm files loaded when I had all the embedded viewer files and external libs in my public folder but since switching to the npm module version of the embedded viewer these no longer work. Not sure if it's just me experiencing this issue, the local node module does have the rhino3dm files in /libs/loaders so I'm not sure if there's some sort of internal error with this. Any advice?

**Comment by kovacsv** [comment]
For performance reasons some libraries are delay loaded (like rhino3dm or occt-import-js). These libraries can't be packed automatically if you use a bundler, so you have to serve them separately.

See this repo for example where the libs and environment maps are copied to the final folder during build: https://github.com/kovacsv/Online3DViewerExamples/blob/main/use_as_es6_module

**Comment by callum-gander** [comment]
Thanks, that makes sense. Using Next.js, I just serve them in a libs folder in public and then as in the example you gave set the external lib location to that folder and everything works perfectly. Thanks again
