### ISSUE TITLE
Error occurs when npm run build_dev is executed

### ISSUE THREAD

**Issue by hehexxxgo** [kovacsv/Online3DViewer#295]
![err](https://user-images.githubusercontent.com/94695071/180753384-a65f0da8-9693-4a8f-b5fc-a662bef0af09.png)
npm@6.14.15
node@v14.17.6
Request help
Thanks

**Comment by kovacsv** [comment]
Did you try to run the script from the root directory of the repository? Do you have python 3 installed?

**Comment by hehexxxgo** [comment]
> 您是否尝试从存储库的根目录运行脚本？你安装了python 3吗？

Thank you for your suggestion. Python3 is not installed

**Comment by kovacsv** [comment]
Hope that solved the problem.
