### ISSUE TITLE
LoadModelFromUrlList fails to load file "No importable file found"

### ISSUE THREAD

**Issue by callum-gander** [kovacsv/Online3DViewer#299]
This is the rough way my code looks
```
            OV.SetExternalLibLocation("libs");
            OV.Init3DViewerElements();
            let viewer = new OV.EmbeddedViewer(parentDiv.current, {
                camera: new OV.Camera(
                    new OV.Coord3D(-10.5, -30.0, 20.0),
                    new OV.Coord3D(0.0, 0.0, 0.0),
                    new OV.Coord3D(0.0, 0.0, 1.0)
                ),
                backgroundColor: new OV.Color(249, 249, 249),
                defaultColor: new OV.Color(200, 200, 200),
                edgeSettings: {
                    showEdges: false,
                    edgeThreshold: 1,
                },
                environmentMap: [
                    "../website/assets/envmaps/grayclouds/posx.jpg",
                    "../website/assets/envmaps/grayclouds/negx.jpg",
                    "../website/assets/envmaps/grayclouds/posy.jpg",
                    "../website/assets/envmaps/grayclouds/negy.jpg",
                    "../website/assets/envmaps/grayclouds/posz.jpg",
                    "../website/assets/envmaps/grayclouds/negz.jpg",
                ],
                onModelLoaded: () => {
                    setDirection();
                    openDetails();
                },
            });
            viewerRef.current = viewer;
            viewer.LoadModelFromUrlList([fullFile.url]);
```
Ideally, this would just load the model from the URL. The URL is a standard download URL for firebase storage, it works fine on it's own to download the file and can also be fetched fine using Axios. Using LoadModelFromFileList works fine for locally uploaded files as below
```
                viewerRef.current = viewer;
                var dt = new DataTransfer();
                dt.items.add(file);
                var file_list = dt.files;
                viewer.LoadModelFromFileList(file_list);
```
But I need to grab a previously uploaded file from firebase and load it into the viewer to edit and as described LoadModelFromUrlList isn't working. Is there a work around for this or is there something I'm missing as to why this isn't working? Thanks in advance

**Comment by kovacsv** [comment]
Usually it's caused by a CORS issue. Please check the browser console if there is any CORS issue.

**Comment by callum-gander** [comment]
Sorry, to clarify, I've resolved the CORS issue, it's not this. The file downloads to the client fine, the viewer just states "No importable file found". The file type is an STL and the file loads in correctly when using FileList and drag and drop

**Comment by kovacsv** [comment]
Another possible problem can be that the url has some other parameters after the file name, like
```
https://mysite.com/myfile.stl?param1=1&param2=2
````

**Comment by callum-gander** [comment]
This is an example URL 
`https://firebasestorage.googleapis.com/v0/b/ino-creative.appspot.com/o/users%2F39%2FChicken%2FPeaceful%20Green%20Cockroach%20(RENAME%20ME)%2FsI003SimonLewisJewelleryPearEarringsB22166618YellowPT2?alt=media&token=007cfc90-a40e-4db4-816f-cbdd48576d5a` 
Would this cause issues? If so, how and what can be done to fix this?

**Comment by kovacsv** [comment]
Yes, the file type is detected based on the url, and this url doesn't contain the file name and extension. There is a solution for this, check out this example: https://github.com/kovacsv/Online3DViewer/blob/master/sandbox/embed_selfhost_noextension.html.

**Comment by callum-gander** [comment]
This worked perfectly, thank you!
