### ISSUE TITLE
Begin with a Default File

### ISSUE THREAD

**Issue by coldTaZZer** [kovacsv/Online3DViewer#3]
Hi kovacsv,

Your work is very useful, but I've got a problem with a very specific case. I would like to know if there is a possibility to use the 3dviewer with a default file loaded with the page as your example of JSModeler demonstration with the cuboid? My file is stored on my server and have a specific href to direct access.

**Comment by kovacsv** [comment]
Hi,

You can define a default file as location hash, like this:
http://3dviewer.net#https://cdn.rawgit.com/kovacsv/Online3DViewer/9e9ca71d/website/testfiles/cube.3ds

It also works with relative locations on the server. If you don't want to use location hash, you can call the `ProcessFiles` function of the `ImporterApp` instance with an array of file urls.

**Comment by coldTaZZer** [comment]
Thank you for the hand! It was useful

**Comment by kovacsv** [comment]
You welcome :)
