### ISSUE TITLE
Add mesh name as info during dotbim export

### ISSUE THREAD

**Issue by MennoMekes** [kovacsv/Online3DViewer#301]
The 3D viewer is great! simple, fast and easy!
I miss one thing, that is the mesh-name in the dotbim export.

Meshes that are imported from an .obj file are named.
In my case I downloaded 3D buildings from 3dbag.nl

When exporting to dotbim, the meshes get exported correct but the 'info' is empty:

        {
            "mesh_id": 1296,
            "type": "Other",
            "color": {
                "r": 200,
                "g": 200,
                "b": 200,
                "a": 255
            },
            "vector": {
                "x": 0,
                "y": 0,
                "z": 0
            },
            "rotation": {
                "qx": 0,
                "qy": 0,
                "qz": 0,
                "qw": 1
            },
            "guid": "0c5c66e7-8762-4dca-b1eb-f7f8cd8466f9",
            "info": {}
        },

If the 'name' would be added to the exported meshes, the objects can be traced back to the origin instead of being just geometry.
I realise it depends greatly on the imported file. The one I imported was an .obj
If I import an Ifc and export that to dotbim I get a lot more information

```
 {
            "mesh_id": 327,
            "type": "Other",
            "color": {
                "r": 255,
                "g": 255,
                "b": 255,
                "a": 255
            },
            "vector": {
                "x": 0,
                "y": 0,
                "z": 0
            },
            "rotation": {
                "qx": 0,
                "qy": 0,
                "qz": 0,
                "qw": 1
            },
            "guid": "5b77b258-a92c-40e1-bc22-46b247139e1d",
            "info": {
                "Roughness": "304,80",
                "Manufacturer": "-",
                "Category": "Walls",
                "Reference": "22_metalstud_250",
                "Description": "binnenwand: metalstud",
                "Combustible": "False",
                "IsExternal": "False",
                "LoadBearing": "False",
                "ExtendToStructure": "False",
                "Ifc: dragend/niet dragend": "False",
                "dim: lengte": "6.950,00",
                "dim: wandhoogte": "2.970,00",
                "dim: wanddikte": "250,00",
                "dim: Volume": "5,16",
                "Ifc: Entiteit": "IfcWallStandardCase",
                "Ifc: Enumeratie": "STANDARD",
                "Info: Description": "binnenwand: metalstud",
                "Info: Manufacturer": "-",
                "Info: Model": "totaal 250mm",
                "Info: Type Comments": "brandwerend / geluidwerend"
            }
        },
```

The meshes om this imported ifc are all called 'Mesh' with an added 5-digit integer.

On both exports the mesh-name is not exported.
I think it would be an added value to improve interoperabilty between the diffeerent formats from the same origin.

**Comment by kovacsv** [comment]
This is more like a dotbim exporter issue, let's continue here: https://github.com/kovacsv/dotbim-archicad/issues/4.

**Comment by MennoMekes** [comment]
The workflow I try to achieve is getting 3D buildings in Revit where the obejcts get the same name as the mesh-name that is in the obj-file. I guess I might as well use the obj-file to do this as the way the geometry is describes is very similar.
I wanted to use dotbim because I want to use it more. and since your viewer exports to dotbim I thought the export from the 3D viewer to dotbim could get the 'name' in the info.

**Comment by kovacsv** [comment]
Oh, sorry, it was a misunderstanding from my side, I thought you are talking about the dotbim exporter for Archicad. 🙂
