### ISSUE TITLE
Online 3D Viewer Logo features when embedded...

### ISSUE THREAD

**Issue by nc-fox** [kovacsv/Online3DViewer#302]
I think it'd be a great feature if when this application is embedded on other sites the Logo that is seen in the lower corner of the viewer, could be edited. My reasoning would be to match the color or theme that site might be using.

I understand the reasoning of having it permanent in the lower corner and even if the logo must stay, it'd be nice if it was editable within gray scale or a lower opacity until hovered over.

**Comment by kovacsv** [comment]
You can self-host the engine, and in this case you won't have the logo: https://github.com/kovacsv/Online3DViewer/wiki/Embed-the-Viewer-Engine.
