### ISSUE TITLE
RegExpParser error when trying to embed viewer

### ISSUE THREAD

**Issue by joaolongo** [kovacsv/Online3DViewer#304]
Hello, I am trying to embed the viewer on my react single-spa application, and when I try to import, and set the lib folder, the following error happens:

![image](https://user-images.githubusercontent.com/2637270/192009106-219ac77b-c560-43cc-8f2c-d84904228585.png)

Right now, my code is as simple as:

```
import * as OV from 'online-3d-viewer';
import { useEffect } from 'react';

export default function Root(props) {
  useEffect(() => {
    OV.SetExternalLibLocation("libs");
  }, []);

  return <section>{props.name} is mounted!</section>;
}
```

I am using typescript to write my react apps.

**Comment by kovacsv** [comment]
There is no solution at the moment to use the engine from React, but there is a "collector" ticket for this: https://github.com/kovacsv/Online3DViewer/issues/318.
