### ISSUE TITLE
Use viewer to showcase files

### ISSUE THREAD

**Issue by warudin** [kovacsv/Online3DViewer#31]
We'd like to use Online3DViewer on the website of a client, to show 3D files of their fysical products. Is this possible?

I can't figure out a way to feed Online3DViewer a specific file, instead of giving the user the option to upload a file.

**Comment by kovacsv** [comment]
There are several options:
- Refer to a file on an external server (CORS should be enabled): https://3dviewer.net/#https://cdn.rawgit.com/kovacsv/Online3DViewer/9e9ca71d/website/testfiles/cube.3ds
- Host the viewer on your server, and refer files with relative locations: https://3dviewer.net/#testfiles/cube.3ds
- Check out the embeddable demo: https://github.com/kovacsv/Online3DViewer/blob/master/embeddable/multiple.html

**Comment by warudin** [comment]
Thanks, that information did the trick for me!

**Comment by kovacsv** [comment]
Great!
