### ISSUE TITLE
Gltf file with VALUE_NOT_IN_RANGE not opening

### ISSUE THREAD

**Issue by zen253230** [kovacsv/Online3DViewer#311]
Hello !

I've got following problem when loading following gltf
[Commodore64.zip](https://github.com/kovacsv/Online3DViewer/files/9696190/Commodore64.zip)
**The file doese not open**
glTF-Validator indicates multiple errors. I believe the decisive ones are VALUE_NOT_IN_RANGE

**To Reproduce**
open the file

**Expected behavior**
the file would load even with its specification errors and without the texture file

Thank you !

**Comment by kovacsv** [comment]
Usually I'm not optimizing for invalid files, but in this case it doesn't have any texture coordinates, and it could be handled easily.

**Comment by kovacsv** [comment]
![model](https://user-images.githubusercontent.com/2034315/194911639-05f5c062-67b8-43d9-bdd5-97c05d71a0b3.png)

**Comment by zen253230** [comment]
Thank you very much!
