### ISSUE TITLE
allow uploading/loading multiple 3d files

### ISSUE THREAD

**Issue by khimaros** [kovacsv/Online3DViewer#313]
FreeCAD assemblies support linking objects across files.

it seems that o3dv already allows you to upload multiple files, but it requires you to pick a single file to display.

this is a blocker for multi-file support in #312 but shouldn't block single-file assemblies.

**Comment by kovacsv** [comment]
This is literally the first issue (#1) created for Online 3D Viewer six years ago. 😅

It would be great to implement this, but it doesn't really block the FreeCAD assembly import. It's possible to load the referenced files in one round. The complexity here is much more in the fact that the referenced files has the same extension, so it's not trivial to detect the "main" file.

**Comment by khimaros** [comment]
would it be okay to let the user choose the main file?

that would be fine for my use case, i think.

**Comment by khimaros** [comment]
also, fine to mark this as a dupe. sorry for that!
