### ISSUE TITLE
Provide engine as a React Component

### ISSUE THREAD

**Issue by aymanhab** [kovacsv/Online3DViewer#318]
Great work. In the current day and age however, most web-development is built on frameworks that mix and match libraries/components and React seems like a commonly used such framework. Are you aware of any efforts to convert any/all parts of Online3DViewer website or engine to React Components for easy integration? Thank you.

**Comment by kovacsv** [comment]
Unfortunately I'm not familiar with React, but if you have the capacity to figure out how to use the npm package from a React Component, an example is very welcome here: https://github.com/kovacsv/Online3DViewerExamples.

**Comment by callum-gander** [comment]
I've done this for my project, I'll create a working example for this next week

**Comment by callum-gander** [comment]
Not quite what you asked for, but here are some examples of how you can use 3D Viewer as a React component https://github.com/callum-gander/online-3d-viewer-next-js. I may help turn the engine into a self-contained single React component at some point, but for now, this should help provide some examples for those who want to use the 3D viewer with React. Is there anyway I can add some of this to the documentation?

**Comment by kovacsv** [comment]
@callum-gander, it's awesome, thanks for your work. I think that the best place for this code and documentation is the https://github.com/kovacsv/Online3DViewerExamples repository. I would put it in a `use_as_react_component` folder. Could you please open a pull request there?

**Comment by aymanhab** [comment]
Thanks @callum-gander 👍 excellent work.

**Comment by Aarbel** [comment]
Thanks a lot for all this work @callum-gander.

@kovacsv i would be really great to provide more npm package documentation to help everyone is this viewer, and any loader api helpers ( life ifcjs for example)

**Comment by Aarbel** [comment]
Package size optimisation would also be very welcome, importing online-3d-viewer is very too big for pwas, as all the code is imported

**Comment by Aarbel** [comment]
I think globally online-3d-viewer should get a re-written in typescript to be both imported in raw html, and SPAs (React, Vue, Angular apps)

**Comment by Aarbel** [comment]
You can add a forth one @kovacsv: 
- rewrite Online 3d Viewer to help modules bundeling (like lodash) to avoid too big bundles function of online-3d-viewer usage

**Comment by kovacsv** [comment]
#331
