### ISSUE TITLE
Dirty Context/Racing Condition when embedding 3d viewer

### ISSUE THREAD

**Issue by dsibilio** [kovacsv/Online3DViewer#32]
I'm working on a website and trying to use the embeddable version of the 3D Viewer in order to show some models with textures (obj+mtl+tex as PNG).
I've pretty much followed the embeddable/fullscreen approach, by adding the following event listeners in my index.html:

```javascript
  <script type="text/javascript" src="assets/js/online3dembedder.js"></script>
  <script type="text/javascript">
    function OnResize() {
      var canvas = document.getElementById('3dcanvas');
      if (canvas != undefined) {
        canvas.width = document.body.clientWidth * 0.7;
        canvas.height = document.body.clientHeight * 0.7;
      }
    }

    function OnLoad() {
      OnResize();
      LoadOnline3DModels();
    }

    window.addEventListener('load', OnLoad, true);
    window.addEventListener('resize', OnResize, true);
    window.addEventListener('reloadCanvas', OnLoad, true);
  </script>
```

The `reloadCanvas` event is a custom event I'm dispatching whenever a new model is selected by the user. The user does not actually own the model files as they're hosted on my website, they just select a logical entity from a list and this triggers the canvas reload with new, different sourcefiles.

Almost all the time when performing this operation I can see there is some problem _(might be dirty context more than anything else)_ with what seems to be loading textures, as they're either applied wrongly to the model or what appears to be a previous texture is being used instead of the current one - _this doesn't happen as soon as the new model is loaded, but only when the user zooms in/out of the model or rotates the model around_.
When this happens the following is logged on the console:

```WebGL: INVALID_OPERATION: uniformMatrix4fv: location is not from current program
three.min.js:543 WebGL: INVALID_OPERATION: uniformMatrix4fv: location is not from current program
v @ three.min.js:543
three.min.js:562 WebGL: INVALID_OPERATION: uniformMatrix4fv: location is not from current program
v @ three.min.js:562
WebGL: INVALID_OPERATION: uniform3f: location not for current program
WebGL: INVALID_OPERATION: uniform1f: location not for current program
[...]
three.min.js:558 WebGL: too many errors, no more errors will be reported to the console for this context.
v @ three.min.js:558
```

Most likely for my use-case i need some cleanup operations being performed on the viewer side when `reloadCanvas` is being consumed? Sadly, I could not find any examples related to reloading canvas+switching models in embedded scenario, but I assume these changes would have to be made in the `online3dembedder.js` file.

**Bug preview**: https://i.imgur.com/3w5ufGE.png
**Website to replicate the bug** _(just fiddle around selecting different models and it will happen once u rotate/zoom in on the new model):_ https://mhw-model-viewer.web.app/
**Project sourcecode**: https://github.com/dsibilio/mhw-models-viewer

_P.S.: Amazing work on the library! Ty very much for making this open-source 🥳 I'm also available for discussing this anywhere else you may see fit (eg. Discord or similar) for faster feedback and then report here once we get to the solution!_ 👋

**Comment by kovacsv** [comment]
Model loading happens in the background, and there is a redraw call after each texture is loaded. It seems that while your new model is loading in the background, the old model is still visible on the canvas.

So the problem is that your canvas has two different WebGL contexts open at the same time.

I see two directions to resolve this:
- The correct solution would be to rewrite the `LoadOnline3DModels` function to use the same instance of `JSM.ThreeViewer` for every reload, and make a `RemoveMeshes` call on the viewer each time a new model is loaded.
- As a workaround, I would try to create a new canvas (and remove the old one) every time you would like to show a new model, and call the `LoadOnline3DModels` function. In this case the old model won't affect the new one.

**Comment by dsibilio** [comment]
Hi @kovacsv ,

thanks for the tips. I went on to implement the first solution in my website and everything seems to be working fine at the moment. Textures are fine and the WebGL warnings aren't logged anymore. 👍 

For me the issue can be closed, unless you see value in adding an example under the embeddable section showing the model reload capability re-using the same canvas.

**Comment by kovacsv** [comment]
I'm glad it works!
