### ISSUE TITLE
TypeError: Failed to execute 'shaderSource' on 'WebGL2RenderingContext': parameter 1 is not of type 'WebGLShader'.

### ISSUE THREAD

**Issue by callum-gander** [kovacsv/Online3DViewer#320]
When using the embedded viewer and spinning up multiple instances of the embedded viewer, the following error occasionally appears on Chrome

```
TypeError: Failed to execute 'shaderSource' on 'WebGL2RenderingContext': parameter 1 is not of type 'WebGLShader'.
```

**Comment by kovacsv** [comment]
There is a limitation on the number of WebGL contexts on a single page (16 or something like that). Is it possible that you reached this limit?

**Comment by callum-gander** [comment]
That'd definitely explain it, I'll have to limit the amount of files they can drop in at any one time. Thank you!
