### ISSUE TITLE
Context and Closure Memory Leaks

### ISSUE THREAD

**Issue by callum-gander** [kovacsv/Online3DViewer#321]
After examining a heap snapshot, I've noticed very high memory usage (see the photos below). For context with the screenshots, there's maybe 8-10 large (30-100mb) files having their volumes calculated then their instances removed so that all that remains is the volume and surface area stored separately. 

![image](https://user-images.githubusercontent.com/29778187/198002826-5e9c910b-9c11-4bc5-8baa-44d6bb615562.png)

I'm fairly certain this is due to me incorrectly tearing down and removing the DOM element containing the EmbeddedViewer and it's WebGL canvas. I think it may be due to what's spoken about here https://stackoverflow.com/questions/37072303/how-to-free-and-garbage-collect-a-webgl-context where the Javascript GC will sometimes not correctly garbage collect WebGL Canvas Contexts if there are event listeners attached to the element, but I'm guessing here, not sure at all. Using memory-stats.js, when the files are initially loaded into the embedded viewers, the memory spikes, as to be expected, but then it will drop only slightly and persist at a level much higher than the baseline when it should drop almost completely back down as little is saved beyond just the volume and surface area and all the canvases and WebGL contexts should be destroyed. As you can see below, the vast majority of the closure and context retained sizes are from the EmbeddedViewer or related objects

![image](https://user-images.githubusercontent.com/29778187/198004118-cb496925-8e73-446b-8f50-28d0668c5001.png)

![image](https://user-images.githubusercontent.com/29778187/198004255-1b1bb558-a4f6-4bf6-9d8d-04c06e4e4cd8.png)

How my code works is an EmbeddedViewer instance is spun up and held in a React useRef hook. The file is then loaded into that viewer, the volume is calculated and once it's calculated, a signal is sent to the parent component to remove that component. The React useEffect cleanup function, see below, then handles removing the canvas and the context in the following way: the canvas is grabbed, it's WebGL context is lost using the WebAPI, and then the React ref containing the DOM element containing the EmbeddedViewer and canvas is set to null, and the component as a whole is torn down. This should mean the EmbeddedViewer is completely removed, right? If so, then why is the memory footprint still so high? I'm guessing the likely reason is that I'm doing something wrong in the teardown. Do you have any suggestions as to what this might be? What else could be causing this?   
```
return () => {
     // Remove the WebGL context
     const gl = viewerRef.current.canvas.getContext("webgl2");
     gl.getExtension("WEBGL_lose_context").loseContext();
     // Remove the ref containing the DOM element containing the EmbeddedViewer
     viewerRef.current = null;
};
```

**Comment by callum-gander** [comment]
So I have a partial solution, but it feels messy and it feels like there should be a cleaner way of doing it, but it definitely works and causes the GC to remove all the ArrayBuffers, EmbeddedViewer instances and WebGL contexts within 10ish seconds and return the memory to it's original level

```
delete viewerRef.current.model;
viewerRef.current.viewer.renderer.resetState();
viewerRef.current.viewer.Clear();
delete viewerRef.current.viewer;
const gl = viewerRef.current.canvas.getContext("webgl2");
gl.getExtension("WEBGL_lose_context").loseContext();
const tempClone = viewerRef.current.canvas.cloneNode(true);
viewerRef.current.canvas.parentNode.replaceChild(
    tempClone,
    viewerRef.current.canvas
 );
 viewerRef.current = null;

**Comment by callum-gander** [comment]
Just double checking before I close this issue, any advice on this?

**Comment by kovacsv** [comment]
I prefer to keep this open since it would be good to have a clean-up function provided by the library.

**Comment by kovacsv** [comment]
@callum-gander I've added a `Destroy` function to the `EmbeddedViewer`. Still not perfect, but it's much better now.
