### ISSUE TITLE
Calculate Minimum Bounding Box

### ISSUE THREAD

**Issue by jlserrano** [kovacsv/Online3DViewer#324]
I have verified that the x,y,z values vary depending on the position of the object, we need these values to be the same regardless of the angle or position of the object, can we do that with this viewer?

**Comment by kovacsv** [comment]
What x, y, z values? What do you mean by position and angle of the object?

**Comment by kovacsv** [comment]
Ok, it's more clear now. The size is measured along the x, y, z axis since there is no extra information in the model about the orientation. Detecting the orientation and minimum size of the model is a complex thing, and way outside of the scope of Online 3D Viewer.

You can use the measure tool though to measure the distance of parallel faces.

**Comment by jlserrano** [comment]
Tks. 
Can you evaluate the implementation of this feature. 
Its posible? 
Obviously we can contribute as needed. 
Regards
--
José Luis Serrano López - DIRECTOR miércoles, 30 noviembre 2022, 07:13p. m. +01:00 de Viktor Kovacs  ***@***.*** :

**Comment by paireks** [comment]
Hey @jlserrano 
Probably you are talking about this: https://en.wikipedia.org/wiki/Minimum_bounding_box_algorithms
Even many huge modelling software do not offer such built-in option, and people have to create their own plugins or scripts to obtain these dimensions, e.g. here for Blender someone had to create his own addon: https://www.youtube.com/watch?v=sTZ2Hbnu7Tc
It's also good to notice that it's kind of optimization problem, so depending how you will try to approach it, you will get different box with different sizes. You can see it in that addon video, that you have many options how to approach this. Just adding 2 cents to discussion how complex it is :)

**Comment by jlserrano** [comment]
tks again.

Of course it's not easy, if it were easy anyone could do it..jjjjjj

I understand that you are not interested in developing this option in the viewer, as I was saying, we could provide financing for this modification.

can you evaluate it?

or maybe you are not interesting.

i will understand.

regards.

**Comment by jlserrano** [comment]
ups. all big 3d software we use can calculate correctly x,y,z dimensions regardles object position. One adicional problem.. we will get the measures automatically without user interaction.

regards.

**Comment by kovacsv** [comment]
Yepp, @paireks is right, it's pretty hard to it right. Although the problem space is very exciting, I don't think I'll have time for this in the near future. The easiest way would be to utilize an already existing JavaScript or C++ library to do the job, but I don't know if such library exists.

**Comment by jlserrano** [comment]
Tks.

very kind of you.

best regards.
