### ISSUE TITLE
Make the engine usable from TypeScript (to use from React, Vue, Angular)

### ISSUE THREAD

**Issue by kovacsv** [kovacsv/Online3DViewer#329]
This issue is about making the `online-3d-viewer` package usable from TypeScript without rewriting it entirely. I'm not sure if it's possible, so it needs some investigation.

**Comment by callum-gander** [comment]
Typescript does allow partial adoption and not all files have to be ts files. Maybe it would mostly be a case of just turning the `EmbeddedViewer` and `Viewer` objects into .ts files, properly typing them and their inputs for their methods and exposing them to the client as a separate types package, like `npm i --save-dev @types/online-3d-viewer` as mentioned in #326. However, I'm not sure whether this is possible

**Comment by kovacsv** [comment]
@callum-gander I'm not sure if it's possible, but I'm thinking about a very first step where we don't modify any code, just adding a TypeScript interface to the library to avoid warnings when using it (maybe a `.d.ts` file or something). Do you know if it's possible?

**Comment by callum-gander** [comment]
Sorry for the delayed reply on this. Yes, it does seem possible, see here https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html. It looks like you need to add some additional dependencies but it doesn't state that you'd need to convert all your JS to TS. That was always one of the selling points for TS, you can incrementally adopt it. For example, on my company's project, we've been incrementally changing important files to TS to guarantee type safety but less important one's we've left as JS for now. I'm happy to do a pull request to generate the .d.ts file if you like and see if this removes the warnings?

**Comment by kovacsv** [comment]
I'm happy to se how does this work, so if you have some time a PR is welcome!

**Comment by callum-gander** [comment]
Sure! I'll try get around to it this weekend, if not then next weekend

**Comment by callum-gander** [comment]
#348 should resolve this. If anyone else interested in this functionality could potentially try out the pull request, that'd help a lot
