### ISSUE TITLE
Possibility to open * .ply files or convert them with vertex color

### ISSUE THREAD

**Issue by batalex2021** [kovacsv/Online3DViewer#33]
Hi Viktor,
i used your code to open ply files but it is not supported. I just tried to convert it to * .obj it works but no texture color. Can you help me ?
thanks thanks thanks

**Comment by kovacsv** [comment]
Please send me an example file so I can investigate why the texture is missing.

**Comment by batalex2021** [comment]
i sent you the file to email thanks

**Comment by kovacsv** [comment]
The version released today is able to open ply files as well.
