### ISSUE TITLE
Faces selection from STEP geometry 

### ISSUE THREAD

**Issue by yvanblanchard** [kovacsv/Online3DViewer#333]
Hello,

Could you please indicate the few steps to follow, and maybe serach keywords for existing APIs, for selecting faces from solid (if imported from exact geom as STEP format), in order to perform some analysis.
Example: highlight the face with color, compute and center of gravity, area, get mesh triangles (after geometry tesselation), etc.

Moreover, do you have a kind of tutorial about how to integrate a C++ lib , with emscripten for javascript usage, to be used with Online3DViewer website ?

Thank you,
Yvan

**Comment by kovacsv** [comment]
A face in a STEP file can result in a bunch of triangles, and at the moment this information is lost during export, so there is no way to tell which triangles are originated from the same face. I don't think it's possible in the near future.

About the C++ library integration one good example is https://github.com/kovacsv/occt-import-js, but I don't have any tutorial in mind that helps the process.

**Comment by yvanblanchard** [comment]
Thank you very much for your help @kovacsv kovac
For getting the traingles linked to a solid face, I guess I would have to modify the occt-import lib (that do the tri_ck, but only for colored face).
