### ISSUE TITLE
Running website KO (only logo display in browser)

### ISSUE THREAD

**Issue by yvanblanchard** [kovacsv/Online3DViewer#335]
Hello,

I built both engine and website for production (on same PC), but when testing (using Firefox, on Win10) I only get the logo on the page.
What could be wrong ?

Thank you,
Yvan.

Picture:
![image](https://user-images.githubusercontent.com/63931618/206199619-df806cf7-44f5-4d65-9802-e142787ecd5c.png)

**Comment by yvanblanchard** [comment]
Here is my "npm start" console output:
![image](https://user-images.githubusercontent.com/63931618/206199821-2c737c10-0907-4f20-940d-ccbcbe322136.png)

**Comment by kovacsv** [comment]
Did you read the documentation? https://github.com/kovacsv/Online3DViewer/wiki/Set-Up-the-Development-Environment

**Comment by yvanblanchard** [comment]
Hello @kovacsv ,

I tried to build the website from another from scratch, using brand new repo code, but I miss the tree view and panels on the left, toolbars on top,.. (but I can upload a model and view it):
![image](https://github.com/kovacsv/Online3DViewer/assets/63931618/97990ba1-4d81-44e8-8017-ffdc3e6a2aa4)

I tried to build website, but it seems this mechanism changed (no more build scripts):
![image](https://github.com/kovacsv/Online3DViewer/assets/63931618/40bb6bb5-c554-402f-b3fb-f43e91940a74)

What is missing here at my side ?
Sorry for this simple question.

Thank you

**Comment by kovacsv** [comment]
There is no command named `build`. Please follow the documentation I commented earlier in this issue.

**Comment by yvanblanchard** [comment]
Thank you !
I used : `npm run build_website`
Then running `http://localhost:8080/website`, and it works fine
Sorry again for my dummy question.
