### ISSUE TITLE
Browser compatibility problem

### ISSUE THREAD

**Issue by Leo0724** [kovacsv/Online3DViewer#342]
Does it support Firefox?

I use Chrome, which is fine, but Firefox doesn't work.

![Firefox](https://user-images.githubusercontent.com/28991877/209643312-a2cab56c-2ab1-43a7-8e01-fa35484b3a2f.png)

**Comment by Leo0724** [comment]
I am using Firefox  52.9.0 (32-bit).

**Comment by kovacsv** [comment]
Firefox 52 is more than 4 years old, there is no plan to support such an old browser. If possible, try to update to the latest version.

**Comment by Leo0724** [comment]
Because some of our systems have to use these older browsers, how can I solve this problem? Please provide some ideas, thank you

**Comment by kovacsv** [comment]
You can try out some esbuild settings to target old browsers: https://esbuild.github.io/getting-started/#bundling-for-the-browser, but there is no guarantee that it will work. You can also get the 2018 version of Online 3D Viewer.
