### ISSUE TITLE
Open from your Device using the URL 

### ISSUE THREAD

**Issue by ricaun** [kovacsv/Online3DViewer#343]
**Open from your Device using the URL**

There is a way to load a file from the device/computer using the URL using something like this: 
* `https://3dviewer.net/#file=C:/Users/user/Downloads/House.bim`

I tried to use the #model key but looks like it only works with online files.

**Comment by kovacsv** [comment]
Yes, it works only for online files. This is how browsers work, it would be a huge security issue if websites would be able to load files from a computer by just opening an url.

**Comment by ricaun** [comment]
You are right make sense.
But if I copy the html, and open the html in a browser, I suppose gonna be possible to open the file, everything is in the same machine.
Gonna try and see if works.

**Comment by ricaun** [comment]
CORS still trigger, for security reason.

I was looking in the https://github.com/kovacsv/Online3DViewer/tree/master/sandbox samples and by looking in the source code I wander if is possible to create some `FileSource.Blob` format.

So the I could be able to update the viewer with something like this:
```js
viewer.LoadModelFromBlob('House.bin',[...]);
```
I believe that the only thing that is needed to load a file in the viewer, the name of the file and the content (buffer array).

**Comment by ricaun** [comment]
I was able to make work the blob: https://github.com/ricaun/Online3DViewer/tree/load_blob

```js
viewer.LoadModelFromBlob (
    'Cube.bim', '{"schema_version":"1.0.0","meshes":[{"mesh_id":0,"coordinates":[0.0,0.0,0.0,10.0,0.0,0.0,10.0,0.0,10.0,0.0,0.0,10.0,0.0,10.0,0.0,10.0,10.0,0.0,10.0,10.0,10.0,0.0,10.0,10.0],"indices":[0,1,2,0,2,3,0,1,4,1,4,5,0,4,3,4,3,7,1,2,5,2,5,6,2,3,7,2,6,7,4,5,7,5,6,7]}],"elements":[{"mesh_id":0,"vector":{"x":100.0,"y":100.0,"z":100.0},"rotation":{"qx":0.0,"qy":0.0,"qz":0.0,"qw":1.0},"guid":"8501a5e3-4709-47d8-bd5d-33d745a435d5","type":"Brick","color":{"r":0,"g":0,"b":200,"a":255},"info":{"Name":"Cube"}}]}'
);
```

Here is my sample code to load a text in the viewer: https://github.com/ricaun/Online3DViewer/blob/load_blob/sandbox/embed_selfhost_code_blob.html

At the moment only works with string content and only supports one `blob`, but could be scaled easily.

If you have any suggestions please let me know so I could make a proper PR.

**Comment by kovacsv** [comment]
It can be done much easier without modifying the code. You can manually create a File object, and pass it to the `LoadModelFromFileList` function.

```js
let jsonContent = '{"schema_version":"1.0.0","meshes":[...';
let fileList = [
    new File ([jsonContent], 'Cube.bim')
];
viewer.LoadModelFromFileList (fileList);
```

**Comment by ricaun** [comment]
I forgot to answer and thanks victor thats helps alot.
