### ISSUE TITLE
Adding a comprehensive documentation site/extending 3dviewer.net

### ISSUE THREAD

**Issue by callum-gander** [kovacsv/Online3DViewer#345]
There are two main points to this
1. I think having a bit more of a comprehensive guide and documentation for helping users using different frameworks to setup this package would be really helpful for newcomers 
2. Along with this, I think providing some code examples for ways they may want to use this package would be really helpful as well

I think the current website is great for seeing how the full site works and seeing a running example but isn't great for seeing how to setup the engine. I personally had some difficulty with this when setting it up. I also think that the current github docs aren't adequate and could be improved. Additionally, I think that putting the online 3d viewer examples in a separate repo may harm the discoverability and ease of use of those examples. Most packages have a dedicated documentation website where you can see the code running in a codesandbox or something similar. I think the Tanstack Tables docs are a great example of this https://tanstack.com/table/v8/docs/examples/react/column-visibility. 

Most providers offer some sort of free deployment for open source documentation. I'd be happy to set this up and work on it. Specifically, it'd be good to have examples for Next, Vue and Sveltekit maybe? Not 100% sure. Both Nextra and Docusaurus look good for this. We could also take all the example in the online-3d-viewer-examples repo and set them up as codesandboxes so people could instantly see them work and play around with them as needed. What do you think?

**Comment by kovacsv** [comment]
As a first step I started to extend the code with jsdoc style comments. The generated documentation can be found here: https://kovacsv.github.io/Online3DViewer.

I think this can be extended by example codes. Using a live code playground is a good idea, we could start with the examples in the sandbox folder: https://github.com/kovacsv/Online3DViewer/tree/master/sandbox

**Comment by callum-gander** [comment]
This is much better than before. What are you using to turn the JSDoc style comments into this documentation? I'm wondering where I would be adding the live code playground examples to?

**Comment by kovacsv** [comment]
Parsing is done by jsdoc, and a script converts it to this documentation.

I would add a new page for examples under the Home link:
1. Create a new page (e.g. `docs/source/Examples.html`).
2. Add it to the config file (`docs/source/config.json`).
3. Run `npm run docs`, and it should appear in the documentation (in theory 🙂).

**Comment by callum-gander** [comment]
Sounds good! Just to check as well, there isn't currently a link to the docs from ttps://kovacsv.hu/3dviewer.net/, is there? From a UX perspective, what do you think about putting "DOCS" next to the icons in the top right corner rather than adding another icon there, so as to differentiate it and make it very clear where they are?

An examples page sounds good, I can definitely add that. What I was thinking is that Judging from issues like #350 and #318 and to help people coming from a lot of new frameworks that might be interested in this package, it might be worth having a Getting Started Page, where we provide some codesandboxes showing how to set it up for say, React/Next, Angular, Svelte, Vue and Vanilla JS. I think this could help increase adoption of the package. Then, we also have the Examples section which shows how to use specific action in Vanilla JS with the examples you've already done in `sandbox`. What do you think? If you're alright with this, I'll do this over the next few weeks

**Comment by kovacsv** [comment]
I prefer not to put a direct link on the website for the documentation. Most of the users are non-programmers, so for them it doesn't make much sense. There is a GitHub link, who is interested can find the doc from the main readme file.

About the examples: Thanks for the cooperation, sounds great! I prefer [jsfiddle](https://jsfiddle.net), but let me know if you have other options in mind.

**Comment by kovacsv** [comment]
https://kovacsv.github.io/Online3DViewer
