### ISSUE TITLE
STEP assembly import: displayed bodies names are not retrieved

### ISSUE THREAD

**Issue by yvanblanchard** [kovacsv/Online3DViewer#347]
After importing an assembly as STEP file, the displayed bodies/meshes names are all "no name". If I open this model in a CAD software (SW, CATIA), the bodies have a correct name.

![image](https://user-images.githubusercontent.com/63931618/211191141-05e7c273-f567-4af8-8775-6ea0a7b078f8.png)

**Comment by kovacsv** [comment]
Please attach files to help checking what the issue is.
