### ISSUE TITLE
Failed to load glTF files with invalid texture coordinates

### ISSUE THREAD

**Issue by zen253230** [kovacsv/Online3DViewer#349]
[Blootooth earpiece.zip](https://github.com/kovacsv/Online3DViewer/files/10369120/Blootooth.earpiece.zip)
[Unicycle.zip](https://github.com/kovacsv/Online3DViewer/files/10369122/Unicycle.zip)
[Wall desk speakers.zip](https://github.com/kovacsv/Online3DViewer/files/10369123/Wall.desk.speakers.zip)

Hello,
I'd be very happy if you had just some time to investigate why these files don't load into the viewer.
I know you don't bother with invalid files, but I believe these files are not because they load just fine with other gltf loaders
Anyway thank you very much for the hard work you've accomplished !

**Comment by kovacsv** [comment]
The are definitely invalid glTF files. On the other hand it was an easy fix to read them despite the invalid texture coordinates, so they will work in the next release.
