### ISSUE TITLE
how to run this app?

### ISSUE THREAD

**Issue by longtran84** [kovacsv/Online3DViewer#350]

**Comment by callum-gander** [comment]
If you're vanilla JS and HTML, you can use some of the examples found here https://github.com/kovacsv/Online3DViewer/tree/master/sandbox. If you're using anything with npm (react, etc.), you can download the package from here (https://www.npmjs.com/package/online-3d-viewer) and you can see examples of how to use it here (https://github.com/kovacsv/Online3DViewerExamples)
