### ISSUE TITLE
Huge npm module size

### ISSUE THREAD

**Issue by callum-gander** [kovacsv/Online3DViewer#357]
As you can see from the below bundle analyzer result, online-3d-viewer takes up maybe a 1/5th of my total bundle load. Is there anyway to minize the bundle size? 

![Screenshot_20230203_155642](https://user-images.githubusercontent.com/29778187/216649227-6d191e63-dbeb-4479-925e-a8b319ff2e25.png)

**Comment by kovacsv** [comment]
What does the size mean? The module and all dependencies or only the module? Is it the size of the source, or with all the other files (like images)? Is it the size of the module folder in `node_modules`?

**Comment by callum-gander** [comment]
This is the size of the online-3d-viewer node_module that's sent to the client, with the necessary dependencies to run clientside, which seems to primarily be three.js. One not insubstantial chunk sent that doesn't need to be is the three/examples folder, I'm not sure if there's some way for you to control that being outputted when three.js is built? The second is just the sheer size of three.module.js in three/build. So I obviously don't understand the much of the inner workings of this package, I'm presuming you use it to do a lot of the geometry and rendering clientside so it can't be removed but can this module be minified at all? The below shows a clearer image of everything the online-3d-viewer module that is sent client side in red

![Uploading Screenshot_20230206_104756.png…]()

**Comment by callum-gander** [comment]
Any update on this?

**Comment by kovacsv** [comment]
three.js is essential to make the library work, so i don't see any easy way to lower the package size at the moment.

**Comment by Symbian9** [comment]
> three.js is essential to make the library work, so i don't see any easy way to lower the package size at the moment.

@kovacsv Guess, it is not about removing `three.js`, but about removing its examples folder, as @callum-gander said above:

> One not insubstantial chunk sent that doesn't need to be is the **three/examples folder**, I'm not sure if there's some way for you to control that being outputted when three.js is built?

**Comment by kovacsv** [comment]
Yes, but i don't know any way to affect the size of a referenced package.
