### ISSUE TITLE
password protection for models | simple login form

### ISSUE THREAD

**Issue by bewegende-Architektur** [kovacsv/Online3DViewer#361]
Hey there :)

when hosting Online3DViewer with npm the whole folder-structure is hosted including the assets folder. Is there some alternative to htaccess or similar to make a simple login form? The idea is to share models with a customer. Thanks in advance!

Greetings,
Chris

**Comment by kovacsv** [comment]
Hey, password protection is out of the scope of Online3DViewer since it's the responsibility of the server that hosts the model. If you are using the npm package, you probably host your model, so you can make the entire page password protected.

**Comment by bewegende-Architektur** [comment]
Thanks for your quick reply! Yes, i would like to host the models via npm too. What could be an easy approach to protect the whole hosted content? I know that this is more a nodejs specific question.

**Comment by kovacsv** [comment]
I would make the entire page password protected that embeds the viewer, but the soultion depends on your server configuration, the security level you would like to reach and several factors. Unfortunately I don't think I can help you any more with that.

**Comment by bewegende-Architektur** [comment]
Ok, thank you very much anyway :)

Wish you a nice weekend,
Chris
