### ISSUE TITLE
Sharing link broken due to missed slash before hash parameters

### ISSUE THREAD

**Issue by Symbian9** [kovacsv/Online3DViewer#364]
**Describe the bug**

Sharing link generates without `/` before `model=`: https://3dviewer.net#model=https://raw.githubusercontent.com/fougue/mayo/develop/tests/inputs/cube.iges

As a result it may not be recognized as a valid. For example, on Mastodon such URL splits as next:

- [https://3dviewer.net](https://3dviewer.net/)#model=[https://raw.githubusercontent.com/fougue/mayo/develop/tests/inputs/cube.iges](https://raw.githubusercontent.com/fougue/mayo/develop/tests/inputs/cube.iges)

**To Reproduce**
1. Generate share with `/` before `model=`.

**Expected behavior**

Generated URL should look like this: https://3dviewer.net/#model=https://raw.githubusercontent.com/fougue/mayo/develop/tests/inputs/cube.iges

**Screenshots**

![Screenshot_2023-02-25_13-42-33](https://user-images.githubusercontent.com/13188580/221355010-c3b6a521-00c0-4064-94b3-5487db638161.png) 
![Screenshot_2023-02-25_13-45-07](https://user-images.githubusercontent.com/13188580/221355091-f819853e-cbd6-40c7-b63d-3d4c95bfab78.png)

**Comment by kovacsv** [comment]
Good point, although both urls are valid, twitter works the same way, and recognizes only the `/#` pattern.

**Comment by Symbian9** [comment]
Another case: Mastodon fails to recognize URL parameters separate with `$` and just splits then out of the rest

- Correct: https://twitter.com/hn_frontpage/status/1629504187049336833
- Correct: https://bird.makeup/users/hn_frontpage/statuses/1629504187049336833
- Broken: https://fosstodon.org/@hn_frontpage@bird.makeup/109926148384975150
