### ISSUE TITLE
Texture map options not parsed from mtl file

### ISSUE THREAD

**Issue by Erik8309** [kovacsv/Online3DViewer#371]
**Describe the bug**
I want to apply options to my material in accordance with the mtl specification. 
So for instance I have this material definition in my mtl file:

```
newmtl Herman_Miller_-_Seat_Fabric_8T07_Crossing_Pumpkin
Kd 1 1 1
d 1.000000
map_Kd -s 10 10 10 leather.mpc
```

The line with map_Kd points to the texture map and its options. However the texture is only read if there are no options in front of the texture. When adding options, the texture file cannot be found.
![image](https://user-images.githubusercontent.com/5773133/226921795-39471ce1-9cdc-4113-af02-c3ad131a912e.png)

**To Reproduce**
Take any mtl and try to add a texture with scale or any other options.

**Expected behavior**
That the texture is read and scaled accordingly (or any other options applied). 
I have tested it with blender and the texture with its options is read there. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5773133/226922097-c54921b5-b21c-4e8e-9e72-c32b8e7b9021.png)

**Comment by kovacsv** [comment]
Could you please attach an example model (with obj, mtl and textures)?

**Comment by kovacsv** [comment]
Thanks for the report. It's fixed and should work from the next release.
