### ISSUE TITLE
How can I config the rotation?

### ISSUE THREAD

**Issue by nnlinh97** [kovacsv/Online3DViewer#372]
Can I rotate from top to 90 degree not 180

**Comment by kovacsv** [comment]
Could you please explain in more detail what you would like to achieve?

**Comment by nnlinh97** [comment]
I have a 3D model of a house, i want to rotate it from top to ground, i want to block rotate below the ground

**Comment by kovacsv** [comment]
Have you tried these buttons in the toolbar?
![image](https://user-images.githubusercontent.com/2034315/227443277-dc96c207-e846-42c0-b516-76744b15c42b.png)
