### ISSUE TITLE
Get normal map

### ISSUE THREAD

**Issue by davidscheid** [kovacsv/Online3DViewer#373]
Hell everyone,

is there a possible solution to get a normal map from the Online 3D Viewer? Is it possible to get such information from the source code?

**Comment by davidscheid** [comment]
I would like to get a normal map from a current snapshot. So that different normals are visiulized in different colors. Are information like normals, depths and edges stored in the source code and can be recomputed? E.g. is it possible to fall back to these information of the 3D model or is this software solution only for visualizing without further exploring the model in such a way?

**Comment by kovacsv** [comment]
Thanks for the answer. At the moment it's outside of the scope of this viewer.
