### ISSUE TITLE
Failed to load file for import simple React App

### ISSUE THREAD

**Issue by yafimski** [kovacsv/Online3DViewer#374]
Seems fine to me. The problem is probably that you are running the webpage locally, and not on a web server. In this case some calls are blocked by the CORS policy.

Try to run a local webserver, and it should work. If you haven't done this before, run the following commands:
```
npm install -g http-server
http-server
```

And then open localhost:8080 in your browser.

![image](https://user-images.githubusercontent.com/2034315/140318500-f39e2151-e41b-4a32-a9f8-b72b29f10ceb.png)

_Originally posted by @kovacsv in https://github.com/kovacsv/Online3DViewer/issues/165#issuecomment-960886654_
            
                    
Hi,
trying to use the viewer in a simple React app.
When running in dev at `http://localhost:3000/`, it says "Failed to load file for import", and when running via `http-server` the page doesn't even try to render the viewer.

Any suggestions on a tutorial I can follow?
Thanks

**Comment by kovacsv** [comment]
Check the react example: https://github.com/kovacsv/Online3DViewerExamples/tree/main/use_as_react_component

**Comment by yafimski** [comment]
Hi, thanks :) 
Did that actually over the weekend. Having trouble understanding what this means:

> Secondly, on order for this package to work in your project, make sure you have the libs folder in your public folder, as shown in this repo. These are the external packages used by Online-3D-Viewer to load the different types of 3D file client side. THE PACKAGE WILL NOT WORK WITHOUT THESE PRESENT.

I see it in the Online3DViewer repo but not in this repo.
How can I install the files in the lib..?

**Comment by kovacsv** [comment]
They are in the `node_modules` folder, just copy them to a publicly accessible location and reference them from there.

**Comment by kovacsv** [comment]
Close due to inactivity.
