### ISSUE TITLE
Failed to import model (failed to load occt-import-js)

### ISSUE THREAD

**Issue by GitHubDragonFly** [kovacsv/Online3DViewer#376]
Hi Viktor.

I went about experimenting and creating a simple online viewer by using the Online 3D Viewer engine.
This viewer can be seen here: `https://githubdragonfly.github.io/viewers/templates/Quick%20Viewer.html`

Its code is available in the repository but narrows down to the following for the import:

```
 <script src="https://cdn.jsdelivr.net/npm/online-3d-viewer@0.8.22/build/o3dv.min.js"></script>
 <script>
    // Set the external libraries location
    OV.SetExternalLibLocation( 'https://cdn.jsdelivr.net/npm/online-3d-viewer@0.8.22/libs' );

    // Init all the 3d viewer elements.
    OV.Init3DViewerElements();
 </script>
```

It all seems to be functional apart from the error mentioned in the subject line which is populated in the viewer window.

Firefox browser console shows the following error:
`GEThttps://cdn.jsdelivr.net/npm/online-3d-viewer@0.8.22/libs/loaders/occt-import-js-worker.js   Not same-origin`

Just curious if there is anything you could suggest about making this work.

Thank you.

**Comment by kovacsv** [comment]
It seems that `jsdelivr` doesn't provide the right CORS headers. To resolve this, you can host all the JS files in your server.

**Comment by GitHubDragonFly** [comment]
Thank you.

I will just include occt-import-js in the same manner as in my other viewer.

**Comment by CJJ-183** [comment]
> Hi Viktor.
> 
> I went about experimenting and creating a simple online viewer by using the Online 3D Viewer engine. This viewer can be seen here: https://githubdragonfly.github.io/viewers/templates/Mobile/Quick%20Viewer.html
> 
> Its code is available in the repository but narrows down to the following for the import:
> 
> ```
>  <script src="https://cdn.jsdelivr.net/npm/online-3d-viewer@0.8.22/build/o3dv.min.js"></script>
>  <script>
>     // Set the external libraries location
>     OV.SetExternalLibLocation( 'https://cdn.jsdelivr.net/npm/online-3d-viewer@0.8.22/libs' );
> 
>     // Init all the 3d viewer elements.
>     OV.Init3DViewerElements();
>  </script>
> ```
> 
> It all seems to be functional apart from the error mentioned in the subject line which is populated in the viewer window.
> 
> Firefox browser console shows the following error: `GEThttps://cdn.jsdelivr.net/npm/online-3d-viewer@0.8.22/libs/loaders/occt-import-js-worker.js Not same-origin`
> 
> Just curious if there is anything you could suggest about making this work.
> 
> Thank you.

The libs folder contains some files, but I don't know them where come from. I do it like this 

<img width="1344" height="878" alt="Image" src="https://github.com/user-attachments/assets/599ba444-1921-4fed-8601-05ed22d88830" /> but it does't work.

**Comment by GitHubDragonFly** [comment]
You should check the code of my viewer [here](https://github.com/GitHubDragonFly/GitHubDragonFly.github.io/blob/main/viewers/templates/Mobile/Quick%20Viewer.html).

At least in my code that line is not necessary any longer (see lines 402-403 in the code).

**Comment by CJJ-183** [comment]
<img width="2816" height="1808" alt="Image" src="https://github.com/user-attachments/assets/63003492-5b6d-40bf-b6c4-5ac444cde59b" />

**Comment by GitHubDragonFly** [comment]
@CJJ-183 there is a simpler way of importing, at least for my code.

This is what my "importmap" looks like now:

'''js
    <script type="importmap">
      {
        "imports": {
          "three": "https://cdn.jsdelivr.net/npm/three@0.178.0/build/three.module.min.js",
          "three/addons/": "https://cdn.jsdelivr.net/npm/three@0.178.0/examples/jsm/",
          "three/examples/jsm/": "https://cdn.jsdelivr.net/npm/three@0.178.0/examples/jsm/",
          "fflate": "https://cdn.jsdelivr.net/npm/three@0.178.0/examples/jsm/libs/fflate.module.js",
          "o3dv": "https://cdn.jsdelivr.net/npm/online-3d-viewer@0.16.0"
        }
      }
    </script>
'''
