### ISSUE TITLE
Error when loading gtlf file (buffer is missing)

### ISSUE THREAD

**Issue by yvanblanchard** [kovacsv/Online3DViewer#378]
Hello,

When loading this gtlf file (with texture files), I got an error (using online viewer version).
Thank you.

![image](https://user-images.githubusercontent.com/63931618/230006623-3109ecdc-ad05-4afc-a11b-d02eed9b765b.png)

[mandalorian_helmet.zip](https://github.com/kovacsv/Online3DViewer/files/11156073/mandalorian_helmet.zip)

**Comment by kovacsv** [comment]
Drop all the required files together to make it work. Or just drop the attached zip file that contains all the dependencies. 🙂
