### ISSUE TITLE
Sidebar.js typo

### ISSUE THREAD

**Issue by digitalbirth** [kovacsv/Online3DViewer#381]
IsPanelsle looks like a typo might be wrong

    this.panelSet.AddPanel (this.settingsPanel);
        this.panelSet.ShowPanel (this.detailsPanel);
    }

    IsPanelsle ()
    {
        return this.panelSet.IsPanelsVisible ();
    }

    IsPanelsVisible ()
    {
        return this.panelSet.IsPanelsVisible ();
    }`

**Comment by kovacsv** [comment]
Good catch, thanks!
