### ISSUE TITLE
Names of Model Structure does not match

### ISSUE THREAD

**Issue by ahunneman** [kovacsv/Online3DViewer#383]
See screenshot below, eDrawings vs Online3DViewer

![2023-04-07 07_58_20-eDrawings](https://user-images.githubusercontent.com/108230387/230551271-d5edfbcc-2d1a-476a-97e5-f1cda729bf6b.png)

**Comment by kovacsv** [comment]
Could you please attach the file?

**Comment by ahunneman** [comment]
Great job, thanks a lot!
