### ISSUE TITLE
the real dimension of the imported model

### ISSUE THREAD

**Issue by CoderDotJs** [kovacsv/Online3DViewer#389]
how can i get the actual dimension of the imported model, the dimension which is used while creating the model?

**Comment by kovacsv** [comment]
What do you mean by actual dimension? How it differs from the dimensions shown in the website?

**Comment by CoderDotJs** [comment]
![230904428-5058936a-b493-4155-b428-a1e2e35db10a](https://user-images.githubusercontent.com/75421185/233637110-59ea7679-b7ad-4ffd-a061-5ee2ef4c326a.png)
Every model has a dimension like the above picture, i just want to get those dimensions

**Comment by kovacsv** [comment]
I extended this example with bounding box and size calculation:
https://github.com/kovacsv/Online3DViewer/blob/dev/sandbox/embed_selfhost_calculate.html

**Comment by CoderDotJs** [comment]
Thanks, it worked!
