### ISSUE TITLE
3MF lattices structures rendering

### ISSUE THREAD

**Issue by yvanblanchard** [kovacsv/Online3DViewer#390]
hello,
Is it possible to handle the lattices rendering in the viewer, through 3MF format ? (Light representation of lattices as lineic/beam skeleton).
thank you

**Comment by kovacsv** [comment]
Could you please explain your request in more details or provide an example?

**Comment by yvanblanchard** [comment]
Sorry for the lack of informations.

The idea would be to handle lattices model with lighter size (compared to STL or OBJ).
See example below:
![image](https://user-images.githubusercontent.com/63931618/233706287-6626ef2d-843b-4bf6-aa7a-83de35f03d50.png)

The 3MF offers the possibility to model the lattices "beams" using a specific way, explain here:
https://github.com/3MFConsortium/spec_beamlattice/blob/master/3MF%20Beam%20Lattice%20Extension.md

So I was wondering if your viewer engine could import and efficiently render such lattices structure (without lagging, or with minimal memory footprint).

**Comment by kovacsv** [comment]
Thanks for the explanation. Currently this kind of geometry generation or visualization is outside of the scope of Online 3D Viewer.
