### ISSUE TITLE
how to call an OBJ object automatically by parameters

### ISSUE THREAD

**Issue by sebazzz6** [kovacsv/Online3DViewer#395]
hello everyone: my question is that in previous versions I could integrate obj images into Loader.Load traces. in this version how can i do it?

**Comment by kovacsv** [comment]
Could you please explain in more details what you are planning to achieve?

**Comment by sebazzz6** [comment]
I'm sorry, I already found that in the url you can send the path of the files to show the images directly in the viewer (separated by commas).
Thanks so much
