### ISSUE TITLE
Smooth normals for rendering

### ISSUE THREAD

**Issue by yvanblanchard** [kovacsv/Online3DViewer#396]
Hello,

Could it be possible to smooth / average normals vectors of meshes (at vertices) for better rendering ?

Like this: 
(left = existing, right = example of viewer with averaged normals):

![image](https://github.com/kovacsv/Online3DViewer/assets/63931618/cd13148e-737f-413b-ad83-3bcae052017e)

**Comment by kovacsv** [comment]
The philosophy behind the viewer is to show exactly the same model that is coming from the external file. If it doesn't contain smoothed normals, the viewer should not do this automatically.
