### ISSUE TITLE
amf format support

### ISSUE THREAD

**Issue by oblacko** [kovacsv/Online3DViewer#397]
Thank you for your work, wonderful library! Help me with advice on how to add .amf format import

**Comment by kovacsv** [comment]
Seems like three.js has an amf loader:
https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/AMFLoader.js

So probably it's very easy to add the same way as the 3mf loader, not sure about the quality though.
https://github.com/kovacsv/Online3DViewer/blob/8cb4bd284b1e8d9c8af4e6831b18854da527d105/source/engine/import/importerthree.js#L381

I will take a look.

**Comment by oblacko** [comment]
Спасибо !!!

**Comment by oblacko** [comment]
Thank you very much !!!
