### ISSUE TITLE
Window tweaking in embedded viewer

### ISSUE THREAD

**Issue by rafael-vm** [kovacsv/Online3DViewer#398]
Dear Kovacs:
First I want to thank you for your wonderful library. I am at a Brazilian Federal University, and we are using it to power our Brazilian Fauna Virtual Anatomic Collection (located at http://200.17.71.18); I hope that´s ok to show up the open3dviewer logo, let me know if don´t.
I tweaked a bit the viewer, but I couldn´t make it to resize to accomodate my select boxes. Can you advice how to do it?
Also (I can open another Issue to request it) that is a way to show slicer markups at the viewer?
Best regards, thank you again, sincerely,
Rafael

**Comment by kovacsv** [comment]
Hey Rafael,

Yes, it's completely fine to use the logo. For the slicer markups, please create a separate issue.

About the resizing issue: For your use case probably would be a better fit to not use the entire website, but only the engine that can show 3D models ([see the documentation here](https://kovacsv.github.io/Online3DViewer/index.html)). If you would like to use the entire webpage, the best is if you insert it as an iframe to the page, so all the resizing can work the same way as if it would be a single-page application.

**Comment by rafael-vm** [comment]
Dear Kovacs, thank you for the suggestion about the iframe, I will try it.
I tried use the engine (read all the docs), but get stuck at the adaptation in my page. Also the funcionalities of the website are ok for the collection. Only feature that I will try to change is that the dowload button be active only for registered users, but I will get there.
I will open the issue about markups.
Best to you, thanks for the quick answer,
Rafael

**Comment by paireks** [comment]
@rafael-vm just wanted to say that it's a really cool usage, and I think it might be even cooler to attach some data to specific bones, so as you click on them some properties could show up :) You could even attach some links (like e.g. wikipedia link or to some document) as a property. Here is some explanation how this workflow could look like: https://github.com/paireks/dotbim/blob/master/LinkingData.md
Obviously I'd love to recommend to do it with .bim format, but I think you should be able to do something similiar with .gltf as well :)

**Comment by rafael-vm** [comment]
@paireks Thank you fou your compliment and suggestions. That´s ultimately our goal: show up altogether with the bones their topographic features. Linking with external sources is really a good suggestion of yours. Currently we use an extension package inside Slicer3D to export the bones volumes we create, is for this extension authors that I will ask for this feature.
All the best!
