### ISSUE TITLE
The same CAD model looks more realistic in other web viewers. Can you tell me if there is a better way to achieve the same effect in an online 3D viewer?

### ISSUE THREAD

**Issue by heningyuan6256** [kovacsv/Online3DViewer#402]
**Describe the bug**

The same CAD model looks more realistic in other web viewers. Can you tell me if there is a better way to achieve the same effect in an online 3D viewer?
**Screenshots**
<img width="926" alt="au3M7zNw9d" src="https://github.com/kovacsv/Online3DViewer/assets/64188102/aabcadbc-a193-4811-8fac-d3ceb1a0fa7d">
<img width="751" alt="KEYtB0NiyP" src="https://github.com/kovacsv/Online3DViewer/assets/64188102/6962a32e-1d81-45ce-9737-dcddc66771fe">

**Comment by N3GIS** [comment]
[](https://assetstore.unity.com/packages/tools/modeling/cad-server-pro-245967)
You can take a look at this product, the effect should meet your needs, the following is the online demo link
[](https://n3gis.github.io/CADServerPro.html)
![1686379890951](https://github.com/kovacsv/Online3DViewer/assets/7942057/d3f51c5a-097d-4410-bcee-d908dc924fad)

**Comment by kovacsv** [comment]
What do you mean by "more realistic"? What are you missing?

**Comment by heningyuan6256** [comment]
> What do you mean by "more realistic"? What are you missing?

我希望渲染效果像下面的链接这样
https://n3gis.github.io/CADServerPro.html

**Comment by kovacsv** [comment]
This level of visualization is outside the scope of this viewer. (The link crashes on a high-end iPhone though.)

**Comment by N3GIS** [comment]
We are about to release the use of three.js library to load CAD models, three.js performance and loading speed will be better, and will be better compatible with mobile phones, please wait patiently for the release of our three.js version.
