### ISSUE TITLE
Support new DropBox sharing url format

### ISSUE THREAD

**Issue by ElvaresJr** [kovacsv/Online3DViewer#408]
Something has changed on Dropbox hosting? I used to upload the GLTF file to Dropbox and then easily opened it with the copied link. Know, I see that the link format has changed and it does not work anymore.

**Comment by kovacsv** [comment]
Seems like other have issues with it, too. 😄
https://www.dropboxforum.com/t5/Create-upload-and-share/New-URLs-for-shared-links-affecting-3rd-party-integrations/td-p/695197

**Comment by imsso-bmed** [comment]
i have same problem - and I share an example url for test 
https://www.dropbox.com/scl/fi/yrvudeiz73ug53wks8y7o/230712_-LDLT_web.glb?rlkey=6yq1jb5slgyldbssci8wxdifg&dl=0

**Comment by kovacsv** [comment]
Thanks, @imsso-bmed it helped figuring out what the problem is.

**Comment by kovacsv** [comment]
Fixed, will be available in the next release.

**Comment by imsso-bmed** [comment]
Hi, thank you for fast feedback!
and I am wondering when and how can I use this new dropbox url import function!
I tried importing 3d model from dropbox link as before, but it does not work so,
I was wondering should I download git zip file or just wair for the release of new version.
