### ISSUE TITLE
Picking elements

### ISSUE THREAD

**Issue by dimvasdim** [kovacsv/Online3DViewer#409]
I used the engine in order to visualize an obj file that I have, but in the documentation I can only see how to load a model. Is there a function that I can use in order to color the element that I pick in the viewer? In the live demo website I can see that this is possible, but as I am trying to integrate this library to an angular project, it would be very useful if there was a function that I could use. Also, I believe that a function of type pickElement(guid) that can pick and zoom to an element based on the global id would be very useful for a lot of people.

**Comment by kovacsv** [comment]
You can set the `defaultColor` when embedding to whatever you want. Please note this affects only the polygons that has no material information (e.g. for stl files, or obj files without mtl). Please check the documentation for details: https://kovacsv.github.io/Online3DViewer/Page_Usage.html

**Comment by dimvasdim** [comment]
> You can set the `defaultColor` during embedding. Please note this affects only the polygons that has no material information (e.g. for stl files, or obj files without mtl). Please check the documentation for details: https://kovacsv.github.io/Online3DViewer/Page_Usage.html

The defaultColor is about the color of the model. I would like to color only the meshes that a user picks and if able to select them by using their global ids.

**Comment by kovacsv** [comment]
No out of the box solution at the moment, but you can try to use some functions of the Viewer class, like:
- `GetMeshUserDataUnderMouse`,
- `GetMeshIntersectionUnderMouse`,
- `SetMeshesHighlight`.

**Comment by kovacsv** [comment]
I close this due inactivity.
