### ISSUE TITLE
Can this be implemented using Wasm?

### ISSUE THREAD

**Issue by long0419** [kovacsv/Online3DViewer#412]
Can this be implemented using Wasm?

**Comment by kovacsv** [comment]
Could you please provide some details?

**Comment by long0419** [comment]
ui element realize the 3d model .

**Comment by GitHubDragonFly** [comment]
@long0419 are you looking for functionality similar to this:

https://mrdoob.github.io/model-tag/

**Comment by kovacsv** [comment]
I close this due to inactivity.
