### ISSUE TITLE
Use the viewer in react and open a ply file,got problem

### ISSUE THREAD

**Issue by YiChenCityU** [kovacsv/Online3DViewer#413]
I use the viewer in react like this:
 ```
 <div className="online_3d_viewer"
                 style={{ width: '800px', height: '600px' }}
                 /*
                 model="../texturedMesh.obj, ../texturedMesh.mtl, ../texture_1001.png">
           */
                model="../linjia00300000.ply">
 </div>
```
I am sure when I use texturedMesh model, it can show right. But when I change the mode to ply file , I got Failed to import model. (The model contains no vertices.) I have tested the ply file in the https://3dviewer.net/ website, it has no problem to show. Could you help me? Thanks very much.

**Comment by kovacsv** [comment]
Can you share me the full example? Are you sure that the file exists on the given location?

**Comment by kovacsv** [comment]
I close this due to inactivity.
