### ISSUE TITLE
CAFVB is now fully functional

### ISSUE THREAD

**Issue by rafael-vm** [kovacsv/Online3DViewer#416]
Dear Kovacs, we talked a while ago about adapting your viewer to our Brazilian Fauna Virtual Animal Collection (Issue #398). After spending sooome time do gut you wonderful js and css, I was able to translate it to portuguese, properly fit the viewer to an Iframe, as well to knockout some buttons and functions I didn´t want. Thank you for the help. Me and my students are thrilled with adding new animals to the collection. Give us a visit if you have the time.
([http://200.17.71.18/)])
Best regards,
Rafael

**Comment by rafael-vm** [comment]
p.s. I couldn´t find a way to make 'plane list' and 'ortographic view' the default options. Any suggestions?

**Comment by kovacsv** [comment]
Thank you for sharing, great job!
