### ISSUE TITLE
How to read a 3d model from a Blob object?

### ISSUE THREAD

**Issue by PedroUrday** [kovacsv/Online3DViewer#418]
The Blob object is obtained decrypting a file that comes from the server.
The model can be in any format supported by this library. How to specify the format. It can be .glb, .3mf, etc.
The use case is to prevent someone stoles the 3d models.

**Comment by kovacsv** [comment]
Here you can find an example of loading models from a url without a file name: https://github.com/kovacsv/Online3DViewer/blob/master/sandbox/embed_selfhost_noextension.html

**Comment by kovacsv** [comment]
I close this due to inactivity.
