### ISSUE TITLE
Opening a file from a file sharing site like dropbox

### ISSUE THREAD

**Issue by digitalbirth** [kovacsv/Online3DViewer#422]
Hi, I run a file share site called filerun, (great software)

I am trying to understand how the load by url works as it works with dropbox and can't see why it shouldn't with filerun.

I have set the file as force open in browser so it direct downloads there is two modes but neither work.

This is a link to the sample helmet model.

https://3dviewer.net/#model=https://protected.digitalbirth.com.au/wl/?id=zd0B3sDOGXcddtIeIlqXM06HR5CvWLsO&fmode=download

https://3dviewer.net/#model=https://protected.digitalbirth.com.au/wl/?id=zd0B3sDOGXcddtIeIlqXM06HR5CvWLsO&fmode=open

Does it need the file extension in the url link?

source/engine/io/fileutils.js

Is it this file that manages the import and url breakdown, or are there others?

Thanks

**Comment by kovacsv** [comment]
The file format is detected from the file name (more specificly from the extension) so it needs to be in the url, like in the dropbox case.
