### ISSUE TITLE
Fbx model missing some feature

### ISSUE THREAD

**Issue by HNQX** [kovacsv/Online3DViewer#433]
**Describe the bug**

I have a house model, subffix fbx. It goes well in 3d viewer application(on windows 10), like:
![the result](https://52152121.xyz:802/s/zogw8m2u.png)

But on o3dv, some windows of the house model miss, look like below:
![bad result](https://52152121.xyz:802/s/oiv29d9h.png)

**To Reproduce**
Here is the model file ,plz help me check out, thank u!!!
Model  [LINK](https://52152121.xyz:802/s/hoceewfz.fbx)

PS;
I tried more online viewer ,and they have the same issue
- autodesk viewer
[https://viewer.autodesk.com/](https://viewer.autodesk.com/)

- kodbox upload fbx viewer
[https://demo.kodcloud.com/#](https://demo.kodcloud.com/#)

**Comment by GitHubDragonFly** [comment]
My FBX viewer which is three.js based shows the same.

Assimp on the other hand does show it properly.

Here is re-exported version of your model, which is bigger in size but does show properly in Online 3D Viewer.

[hoceewfz.zip](https://github.com/kovacsv/Online3DViewer/files/13443124/hoceewfz.zip)

**Comment by GitHubDragonFly** [comment]
Just to mention that I used my Assimp Viewer to load the original file, export it to OBJ format and then load this OBJ file and export it to FBX.

**Comment by GitHubDragonFly** [comment]
Here is another FBX version of your file, this time imported as a GLB file into the Blender and then exported as FBX.

It is far smaller, even a little bit smaller than the original file.

You should check both versions just to make sure that your mesh names are still correct.

[hoceewfz-blender-export.zip](https://github.com/kovacsv/Online3DViewer/files/13445442/hoceewfz-blender-export.zip)

**Comment by HNQX** [comment]
> Here is another FBX version of your file, this time imported as a GLB file into the Blender and then exported as FBX.
> 
> It is far smaller, even a little bit smaller than the original file.
> 
> You should check both versions just to make sure that your mesh names are still correct.
> 
> [hoceewfz-blender-export.zip](https://github.com/kovacsv/Online3DViewer/files/13445442/hoceewfz-blender-export.zip)

Thanks so much!
It's very nice of you helping me

**Comment by HNQX** [comment]
> Assimp Viewer

How to get the  GLB file before imported into Blender?
Just rename the fbx file or convert using some model convert tool?

**Comment by GitHubDragonFly** [comment]
See the picture below, which shows export options available in the Assimp Viewer.

You might need to use this viewer multiple times to get a certain format. You could also use other of my viewers since they have some export options available as well.

Your original FBX file did load in the Assimp Viewer properly but was causing errors during some exports.

So I just used OBJ + MTL export first and that worked fine. You can then reload these OBJ + MTL exported files into the Assimp Viewer or even OBJ Viewer and then export the model to GLB.

Just experiment with all these viewers to see what works for you.

**Comment by GitHubDragonFly** [comment]
I think that my explanation above was actually related to me trying to re-export your FBX file to FBX format again.

Just load your FBX file into the Assimp Viewer and then try straight GLB export (it should work).
