### ISSUE TITLE
Show Edges in 3D

### ISSUE THREAD

**Issue by Emilien-Etadam** [kovacsv/Online3DViewer#44]
Hi, 
Is there a way to show the edges with a black line ?

![2021-04-03_15-55-47](https://user-images.githubusercontent.com/56485277/113480572-324ee000-9495-11eb-9c79-6b9486c645e7.png)

**Comment by kovacsv** [comment]
At the moment it's not possible.

**Comment by X-Ryl669** [comment]
You can probably add this by rendering twice, once like it's done currently, and a second time with wireframe mode only (it would also draw hidden edges).

**Comment by X-Ryl669** [comment]
Tried it and it works:
```diff
diff --git a/source/viewer/viewer.js b/source/viewer/viewer.js
index e5acfe0..5dad2d3 100644
--- a/source/viewer/viewer.js
+++ b/source/viewer/viewer.js
@@ -230,6 +230,9 @@ OV.Viewer = class
         for (let i = 0; i < meshes.length; i++) {
             let mesh = meshes[i];
             this.scene.add (mesh);
+            let edges = new THREE.EdgesGeometry(mesh.geometry);
+            let lines = new THREE.LineSegments(edges, new THREE.LineBasicMaterial( { color: 0xFF0000 }));
+            this.scene.add (lines);
         }
         this.Render ();
     }
```

**Comment by kovacsv** [comment]
Thanks for the example code, @X-Ryl669. It works great, and your code can be used as a workaround until it will be part of the core feature set.

Here are my results with your code:
![image](https://user-images.githubusercontent.com/2034315/114922735-5236ba00-9e2c-11eb-8ab4-9006651adaab.png)

**Comment by Emilien-Etadam** [comment]
Look great ! how can I do this (without coding knowledge) ?

**Comment by kovacsv** [comment]
Unfortunately I don't think it's possible without coding knowledge.

**Comment by Emilien-Etadam** [comment]
I did it ! It's quite simple. Just add 3 lines at the right place. But the result is not what I expect, it show all edges :
![2021-04-19_21-08-49](https://user-images.githubusercontent.com/56485277/115290238-9c34de00-a153-11eb-9259-a81988d039ea.png)

But I think the problem come from STL file (if I upload STL files on grabcad it does not shoe edges)

**Comment by kovacsv** [comment]
STL files doesn't contain edges, so it's up to the visualizer to draw them or not. The trick that was mentioned before are just using a helper to show the edges, and it depends on the angle of polygons if an edge is visible or not. Fortunately there is a second parameter for `EdgesGeometry` that defines the threshold angle. Playing with this value maybe you can get the result you want.

```js
let edges = new THREE.EdgesGeometry(mesh.geometry, 30);
let lines = new THREE.LineSegments(edges, new THREE.LineBasicMaterial( { color: 0xFF0000 }));
this.scene.add (lines);
```

**Comment by Emilien-Etadam** [comment]
it works ! Thanks.
![2021-04-20_08-57-32](https://user-images.githubusercontent.com/56485277/115351401-80165880-a1b6-11eb-9304-7e557299f0a6.png)
