### ISSUE TITLE
Can I use a custom name for the material (.mtl) file?

### ISSUE THREAD

**Issue by jacksonkr** [kovacsv/Online3DViewer#457]
I have found that I can customize the .obj and texture (.png) filenames but not the .mtl file. If the material is named anything other than model.mtl then my material will not show up on the object.

here's my current `LoadModelFromUrlList`

```
viewer.LoadModelFromUrlList ([
    `${folder}/wood-chair.obj`,
    `${folder}/model.mtl`, // must be called model.mtl ??
    `${folder}/wood-chair_desert-fabric_texgen_0.png`, // textures have to match model.mtl
    `${folder}/wood-chair_desert-fabric_texgen_1.png`, // colors
    `${folder}/wood-chair_desert-fabric_texgen_2.png`
]);
```

===

I had just switch from Brave browser to Firefox and this was a caching issue. Easiest way to fix is open the page you're working on in a private window.

**Comment by jacksonkr** [comment]
@jlpoolen I highly suggest you post this question over at stackoverflow.com. You'll get a better response and you can leave your post-hijacking days behind!

**Comment by jlpoolen** [comment]
**Answer [theorectical]**: three.js documentation suggests MTL will be loaded as part of the OBJ loader, I have yet to test.  In theory it should.

https://threejs.org/docs/#examples/en/loaders/MTLLoader "A loader for loading an .mtl resource, used internally by OBJLoader."
See also: https://threejs.org/docs/#examples/en/loaders/OBJLoader
