### ISSUE TITLE
Local server Share URL has: 3dviewer.net included

### ISSUE THREAD

**Issue by jlpoolen** [kovacsv/Online3DViewer#458]
I installed this _super_ project on my server and find that if I want to share my model, it appears as if the model has to be processed through your domain:  **3dviewer.net**

Here are the steps I went through:

1) visit my local URL at salemdata.us:
![firefox_2024-04-05_10-35-36](https://github.com/kovacsv/Online3DViewer/assets/227313/d80fb5d2-ef38-4f6d-8011-1f6c2cbc7849)

2) Loaded a file from my desktop:
![firefox_2024-04-05_10-36-15](https://github.com/kovacsv/Online3DViewer/assets/227313/2c4de432-6690-441b-8042-c7665bab3559)

3) Tried to share -- got error message that model has to be loaded via a URL:
![firefox_2024-04-05_10-37-05](https://github.com/kovacsv/Online3DViewer/assets/227313/b9cded0f-353c-4ee4-9d7a-489cea3f1dfe)

4a) Staged my file on my server and then used a URL to load into my instance of Online 3D Viewer:
![firefox_2024-04-05_10-39-08](https://github.com/kovacsv/Online3DViewer/assets/227313/fa75d701-43e0-49a3-8e6d-71b7500c0158)

4b) File from my URL appears fine:
![firefox_2024-04-05_10-39-26](https://github.com/kovacsv/Online3DViewer/assets/227313/f23b5d63-2db6-478e-a2ea-93f99661b721)

5) Tried to share. Found the value using the 1st option "Sharing Link" contains a link to 3dviewer.net:
![firefox_2024-04-05_10-40-22](https://github.com/kovacsv/Online3DViewer/assets/227313/74c1e1a0-274c-43e4-b3bd-a34dbd64f47f)

6) Found the value using the 2nd options (with & with the "Use customized settings" checked):
![firefox_2024-04-05_10-44-13](https://github.com/kovacsv/Online3DViewer/assets/227313/3e57813d-53fc-4d1b-b299-244e91fd7bc2)

The value of the "Sharing Link" field is:
`https://3dviewer.net/#model=https://salemdata.us/models/faceplate_202403090853-Body_FaceplatePocket-WeepHole.stl`
 The value of the Embedded code with "Use customized settings" checked is:
`
    <iframe width="640" height="480" style="border:1px solid #eeeeee;" src="https://3dviewer.net/embed.html#model=https://salemdata.us/models/faceplate_202403090853-Body_FaceplatePocket-WeepHole.stl$camera=-13.64159,49.85545,47.28317,20.00000,5.00000,-20.00000,0.00000,1.00000,0.00000,45.00000$projectionmode=perspective$envsettings=fishermans_bastion,off$backgroundcolor=255,255,255,255$defaultcolor=200,200,200$defaultlinecolor=100,100,100$edgesettings=off,0,0,0,1"></iframe>`

 The value of the Embedded code with "Use customized settings" **UN**checked is:

`<iframe width="640" height="480" style="border:1px solid #eeeeee;" src="https://3dviewer.net/embed.html#model=https://salemdata.us/models/faceplate_202403090853-Body_FaceplatePocket-WeepHole.stl"></iframe>`

In all cases, it looks as though any "shares" generate URLs that point to the domain: 3dviewer.net

Question:  Is there a way to run this viewer on one's server without having "Share" URLs including reference to "**3dviewer.net**"?  I would like to be able to share privately without a call to  3dviewer.net .

Thank you.

[Edited: revised Steps 3 & 4 to include error message when attempting to share a locally loaded file.]

**Comment by kovacsv** [comment]
The sharing url is hard-coded in the code. You can make a fork and update this the way you need. You probably only need to modify this file: https://github.com/kovacsv/Online3DViewer/blob/master/source/website/sharingdialog.js

**Comment by jlpoolen** [comment]
> I installed this _super_ project on my server and find that if I want to share my model, it appears as if the model has to be processed through your domain: **3dviewer.net**
>    ...
> 
> Thank you.
> 
> [Edited: revised Steps 3 & 4 to include error message when attempting to share a locally loaded file.]

I should have indicated how I set up the server so others reading this Issue can duplicate:

1) in directory /usr/local/src:
` git clone https://github.com/kovacsv/Online3DViewer.git`
2) in my Apache's htdocs directory, create a link to the project.  The manner of accessing the project is critical:
```/var/www/salemdata.us/htdocs # ln -s /usr/local/src/Online3DViewer 3dviewer
/var/www/salemdata.us/htdocs # ln -s /usr/local/src/Online3DViewer/website 3dviewerB
```
Note: I linked to the top of the project, e.g. /usr/local/src/Online3DViewer, and then the URL to invoke the project correctly is my server + "3dviewer/website", e.g. https://salemdata.us/3dviewer/website/.  I wanted to shorten the URL and remove a directory, so I tried to link directly to the directory "website" with the creation of the link "3dviewerB" that would be accessed with https://salemdata.us/3dviewerB/ and the unfortunate result was a corrupted page:

![2024-04-06_12-07](https://github.com/kovacsv/Online3DViewer/assets/227313/b507e08d-c3de-4570-b810-24dd3a6241ef)

So, it is necessary to point to the top of the project, and then include in the URL "website".  At least for now.  I'm still exploring this project and I am very impressed with what @kovacsv has created (one-time Patreon minimal donation forthcoming).  I followed his suggestion, but rather than fork the project, I just copied what I had staged into a separate directory and changed my soft links.  When I started to try and remove the "website" directory in the link, I ran into trouble and got the corrupted page above, so I thought I should share my efforts here so someone else trying to accomplish what I am does not encounter the same problem.  I'm not familiar with Node, so what may be standard operating procedure for a developer using Node.js is something I have to grapple with.

**Comment by kovacsv** [comment]
Please find the setup instructions in the [developer documentation](https://kovacsv.github.io/Online3DViewer/Page_EnvironmentSetup.html).

After the code modification you need to call `npm run create_package`. This will generate the entire package in the `build` folder and this is what you can publish on a web server.

**Comment by jlpoolen** [comment]
> Please find the setup instructions in the [developer documentation](https://kovacsv.github.io/Online3DViewer/Page_EnvironmentSetup.html).
> 
> After the code modification you need to call `npm run create_package`. This will generate the entire package in the `build` folder and this is what you can publish on a web server.

Thank you. 

Here's the replacement I made:
```
janus /usr/local/src/Online3DViewerJLP # date
Sun Apr  7 06:37:11 PM PDT 2024
janus /usr/local/src/Online3DViewerJLP # diff source/website/sharingdialog.js  /usr/local/src/Online3DViewer/source/website/sharingdialog.js 
46c46
<             return 'https://salemdata.us/3dviewer/#' + hashParameters;
---
>             return 'https://3dviewer.net/#' + hashParameters;
83c83
<             embeddingCode += ' src="https://salemdata.us/3dviewer/embed.html#' + hashParameters + '">';
---
>             embeddingCode += ' src="https://3dviewer.net/embed.html#' + hashParameters + '">';
janus /usr/local/src/Online3DViewerJLP # 
```
I ran  `npm run create_package` and then I created this softlink that points to the correct directory:
`
ln -s /usr/local/src/Online3DViewerJLP/build/package/website /var/www/salemdata.us/htdocs/3dviewer`

Also, in the "built" website directory, there is no ".htaccess" with redirects, so the ".htaccess" file I found under [PROJECT]./website/.htaccess appears to be a file used solely for your development/deployment.

Closing this ticket as I have a working solution that is easily created.  Thank you, again.
