### ISSUE TITLE
Use CDN for third-party libraries

### ISSUE THREAD

**Issue by kovacsv** [kovacsv/Online3DViewer#463]
To reduce server cost and increase portability.

**Comment by kovacsv** [comment]
Except web-ifc for now: #464.

**Comment by ETNyx** [comment]
Hello @kovacsv , is it possible to force viewer use locally libs like in 0.12.0 instead of CDN?

Reasoning:
- Company policy restrict to use CDN
- Offline use
- Additional problems using CSP (Content Security Policy)

**Comment by kovacsv** [comment]
@ETNyx for the official version I prefer to use them from CDN to reduce server costs. It's possible to create your own version though by replacing library loading with the previous version, but currently we don't plan to officially support this method in the future.

**Comment by ETNyx** [comment]
Ok, you mean make own fork? I already solved it for myself.

Maybe look to install guide, i think it's quite confusing for newcomers like myself:

https://kovacsv.github.io/Online3DViewer/Page_Usage.html
```js
window.addEventListener ('load', () => {
    // tell the engine where to find the libs folder
    OV.SetExternalLibLocation ('libs'); //<--------------------------
    // init all viewers on the page
    OV.Init3DViewerElements ();
});
```

Anyway thanks, your work is awesome :+1:
