### ISSUE TITLE
Loading FCStd model hangs without throwing an error

### ISSUE THREAD

**Issue by GitHubDragonFly** [kovacsv/Online3DViewer#465]
@kovacsv kudos to you on this latest update.

It appears to have resolved what I mentioned in https://github.com/kovacsv/Online3DViewer/issues/376.

Currently, the only model format that does not load in my [Quick Viewer](https://githubdragonfly.github.io/viewers/templates/Mobile/Quick%20Viewer.html) is FCStd as mentioned in the subject line. The viewer's code can be seen [here](https://github.com/GitHubDragonFly/GitHubDragonFly.github.io/blob/main/viewers/templates/Mobile/Quick%20Viewer.html).

I do not consider this an issue, especially since it is related to the way I use the engine but posting it here out of curiosity.
This can be closed at any time.

Just some off-topic notes:
- GLTF models could benefit from keeping their original material side:
  - In particular, the [Littlest Tokyo](https://github.com/mrdoob/three.js/blob/dev/examples/models/gltf/LittlestTokyo.glb) model will not show properly in Online 3D Viewer
- Eventually, adding currently missing GLTF extensions will get this library to catch up to a degree with three.js
- Rhino 3DM library and format are a bit tricky when it comes to exporting and loading textures but for those who might be interested here are links to my custom [3DM Exporter](https://github.com/GitHubDragonFly/GitHubDragonFly.github.io/blob/main/viewers/static/jsm/exporters/3DMExporter.js) and a modified [3DM Loader](https://github.com/GitHubDragonFly/GitHubDragonFly.github.io/blob/main/viewers/static/jsm/loaders/3DMLoader.js) which work together to actually export and also show textures - their functionality can be tested with my viewers. Not sure if any of this could be easily implemented in O3DV engine.

**Comment by kovacsv** [comment]
For me fcstd loading works perfectly in your viewer.
![image](https://github.com/kovacsv/Online3DViewer/assets/2034315/1fbff0cc-d61e-45fd-99a2-5c8654f51aa7)

**Comment by GitHubDragonFly** [comment]
Cool, thank you for letting me know.

It might be my code that is tripping Firefox browser somehow, on 2 different computers - Windows and Debian Linux.

Just tried it in Chrome and it works, just like your picture shows.

I will close this issue.
