### ISSUE TITLE
Possible to change the SVG icon ?

### ISSUE THREAD

**Issue by yvanblanchard** [kovacsv/Online3DViewer#468]
I tried to replace the SVG icon of website by mine, but nothing appears.
Is there any thing to change/prepare for this ?

`<svg class="logo_image"><use href="assets/images/3dviewer_net_logo_text.svg#logo"></use></svg>`

Thank you.

**Comment by kovacsv** [comment]
The svg icon is tricky since it has to support both light and dark modes. You need an svg like this to make it work:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg id="logo" version="1.1" viewBox="0 0 60 60" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
...
</svg>
```
