### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by SuyashJain067** [kovacsv/Online3DViewer#474]
Hi Team,

I made some changes to the code in GitHub and want to deploy it to my Linux server. Can you please guide me on how to deploy it to the server?

I have added my model to the project and am using 3DViewer in an iframe for the browser. Could you please explain how to deploy the code?

After build index.html not generated due to that code is not working on server.

Thank you.

**Comment by kovacsv** [comment]
The developer documentation contains several information in regards of code structure and building: https://kovacsv.github.io/Online3DViewer/
