### ISSUE TITLE
too many ads on the website

### ISSUE THREAD

**Issue by CHUCKECHEESETubeYT** [kovacsv/Online3DViewer#479]
I'm experiencing some ads on the website which causes some problems opening 3D models, is there some sort of third-party tool causing these ads to pop up? Cuz if so, we need to fix it! It's causing issues opening models
![Screenshot_20240616-175102_Chrome](https://github.com/kovacsv/Online3DViewer/assets/104458607/1ef5bdf0-891b-4ae0-b17c-f0a236aa3017)
![Screenshot_20240616-175029_Chrome](https://github.com/kovacsv/Online3DViewer/assets/104458607/f2e7f36a-c822-4938-9ec9-8a650543eb50)

**Comment by kovacsv** [comment]
Ads were displaying by mistake, not they are gone. Thanks for the report.

**Comment by CHUCKECHEESETubeYT** [comment]
![Screenshot_20240617-190852_Chrome](https://github.com/kovacsv/Online3DViewer/assets/104458607/4185c583-46df-4d33-a651-2f4b193e3bd3)
There's still one more being shown on the main menu
