### ISSUE TITLE
'Embedding Online 3D Viewer in an iframe is not supported' in the new version

### ISSUE THREAD

**Issue by rafael-vm** [kovacsv/Online3DViewer#484]
Dear Kovacks:

I´m Rafael, from CAVFB, which uses your website for showing 3d models from Brazilian wild animals [CAVFB](http://200.17.71.18/), hope you remember.
I´m actually using an IFrame to embed your website framework inside the CAVFB website, which was your suggestion.
But after I fetched the last version of Online3Dviewer I noticed that this is not supported anymore. Any suggestion about how I should proceed now? I´m a bit stucked.
Thanks in advance, best regards,
Rafael

**Comment by rafael-vm** [comment]
Dear Kovacs:
I did manage to figure out. Just did comment out the js part the detect window position. Sorry to bother.
Best regards, 
Rafael

**Comment by JohnHenryGaspay** [comment]
Hi @kovacsv I am also trying to use this app using iframe, is this still possible?
