### ISSUE TITLE
stp step and File volume

### ISSUE THREAD

**Issue by smallyaohailu** [kovacsv/Online3DViewer#49]
hello，Thank you very much for your team's excellent product. 
Is our software support step ?
Can we calculate the volume of 3D files?

**Comment by smallyaohailu** [comment]
Does the file support splitting

**Comment by kovacsv** [comment]
Unfortunately it's not possible at he moment.

**Comment by smallyaohailu** [comment]
Will it be supported in the future ，thank you very much!

**Comment by smallyaohailu** [comment]
1.Can we calculate the volume of 3D files? 
2.Is our software support step ?
3.Does the file support splitting?

thank you!

**Comment by kovacsv** [comment]
I don't know if these will be supported in the future. It depends on the incoming number of requests. Surface and volume calculation was already requested before in #34, and now I've created a separate issue for step file import: #50.

I'm not sure about slicing. Could you please clarify a bit what would you like to achieve?

**Comment by kovacsv** [comment]
I close this. because it is separated now in two issues.
