### ISSUE TITLE
Define file urls as location hash - how?

### ISSUE THREAD

**Issue by hinxx** [kovacsv/Online3DViewer#5]
Hi Viktor,

very impressive work!!

I have a question about this statement: Define file urls as location hash

Does it mean to specify which file to load from URL?
How can I do this? 
Do you have an example?

Cheers,
Hinko

**Comment by kovacsv** [comment]
Hi Hinko!

You can define a url or a file rleative location as browser hash.

Here is an example:
http://3dviewer.net#https://cdn.rawgit.com/kovacsv/Online3DViewer/9e9ca71d/website/testfiles/cube.3ds

Regards,
Viktor

**Comment by hinxx** [comment]
Works great .. thanks!

**Comment by wuyuzhang** [comment]
Hi Viktor,

Really nice work.

Just one question:
how to use browser hash to open multiple files for obj format?

Thanks,
Yuzhang

**Comment by kovacsv** [comment]
Unfortunately it is not possible at the moment to show multiple files.

**Comment by kovacsv** [comment]
Thanks for the idea, I added an example in the dev branch, so it will be available soon. I've called it location hash because this is the name of it: https://www.w3schools.com/jsref/prop_loc_hash.asp :)

**Comment by hg42** [comment]
it's also very difficult today, because of all those security related restrictions.
I couldn't convince Firefox or Chrome to load a local file://... URL after the hash.

I cannot really understand why, because drag and drop or file selection works. I assume the permissions are different in these cases?

I also tried everything from https://www.viewstl.com/local_url/
I guess you should add something like this to your docs or simply a reference to that page.
However, it didn't help me.

Note, I always use the most recent versions of these browsers (FF=nightly 66.0a1, chrome=stable 71.0.3578.98)
I also tried other browsers like Midori, Falkon etc., but they either use the same security model or they lack support for the necessary 3D features etc.

**Comment by hg42** [comment]
there are a lot of tips to workaround this, I tried these:

```
google-chrome --disable-web-security "https://3dviewer.net#$url"
google-chrome --allow-file-access-from-files --allow-file-access --allow-cross-origin-auth-prompt "https://3dviewer.net#$url"
chromium --disable-web-security "https://3dviewer.net#$url"
chromium --disable-web-security "http://www.viewstl.com/viewstl.php?url=$url"
chromium --allow-file-access-from-files --allow-file-access --allow-cross-origin-auth-prompt "https://3dviewer.net#$url"
chromium --out-of-blink-cors "https://3dviewer.net#$url"
```

however with current browsers this didn't work. But I am sure it worked some time ago.

I created a little electron app and got it to load the file. But it's not completely ready yet...

**Comment by hg42** [comment]
I once tried it with a local 3dviewer (loaded via file://) but it didn't work.
But that was before knowing the command line options mentioned above.

After testing several combinations of these options, I need only one to load local files from a viewer loaded from local files:

`chromium --allow-file-access-from-files "file:///z/3D-print/Online3DViewer/website/index.html#file:///z/3D-print/things/test/test-jscad/output.stl"`

So my first requirement is satisfied.

Now I need to figure out how to autoload the stl file while ideally keeping all view parameters like angles, zoom factor, etc.
In general this should work with a relative hash url. But how to set it on the existing tab?

**Comment by ApetweBc** [comment]
Does using the hash only works with .3ds file. I tried uploading Stl file from Amazon or from my local server but both failed. Error "No readable file found You can only open 3ds, obj, Stl and off files". The files work in drag and drop thou. What do you think?

**Comment by kovacsv** [comment]
Seems working for me: http://3dviewer.net/#https://cdn.rawgit.com/kovacsv/Online3DViewer/9e9ca71d/website/testfiles/objects_ascii.stl

Can you send the link what doesn't work for you?

**Comment by ApetweBc** [comment]
Working will all the other formats locally but I can't get it to work from Amazon S3. Looking at your URL, there are no dashes. My amazon URL is ''https://stltestingw.s3-us-west-2.amazonaws.com/3Dimplantfilestl.stl''

**Comment by kovacsv** [comment]
I think it is a cross origin request issue. You have to allow CORS on your server.
