### ISSUE TITLE
Add support for poly.google

### ISSUE THREAD

**Issue by zen253230** [kovacsv/Online3DViewer#58]
Once again thank you for your fantastic job with so many new functions !

Until june 2021 there is this great resource at poly.google.com

Sadly I can't load files because of a missing buffer !

[archive.zip](https://github.com/kovacsv/Online3DViewer/files/6343356/archive.zip)
[archive(1).zip](https://github.com/kovacsv/Online3DViewer/files/6343357/archive.1.zip)

**Comment by kovacsv** [comment]
You have to import the gltf and the bin file together (drag and drop both files, or open with multiselect).

**Comment by zen253230** [comment]
Yes that's it !
Maybe you should add a message like "Please ensure you selected all needed files" or something like that.
Anyway your software is great !

**Comment by zen253230** [comment]
Did you try to open the file lighthouse from poly.google which I included. It doesn't seem to display anything even after multiple tries and no error message ?

**Comment by kovacsv** [comment]
Yes, that one seems to be an incorrect model. It also fails in the glTF validator: https://github.khronos.org/glTF-Validator I'll think about how to detect this situation.

**Comment by zen253230** [comment]
And yet I've downloaded it without modification. There are loads of models from poly.google.com which would be worth importing because they are well looking.
Please see what can be done. Thanks !

**Comment by kovacsv** [comment]
I've created a separate issue for this error:
Detect value not in range error in glTF #59
