### ISSUE TITLE
Some models are not rendered

### ISSUE THREAD

**Issue by mrtndimitrov** [kovacsv/Online3DViewer#6]
For example, the attached OBJ is not rendered but I can see it in 3D Builder. Thank you.

[1511427838.zip](https://github.com/kovacsv/Online3DViewer/files/1506380/1511427838.zip)

![image](https://user-images.githubusercontent.com/772355/33273887-3a006750-d397-11e7-94b9-dcb54f7287fc.png)

**Comment by kovacsv** [comment]
You have found a bug :) It seems that the Tr parameter handling is wrong. As a workaround you delete the Tr parameter from the mtl file.

**Comment by kovacsv** [comment]
Fix with JSModeler update in 690452b3df5fd110dcff516ce68f229d8f34ad09.
