### ISSUE TITLE
Hi-DPI aware

### ISSUE THREAD

**Issue by stopmotio** [kovacsv/Online3DViewer#60]
WebGL supports Hi-DPI but this program does not, making it look blurry on phones(which otherwise work flawlessly) and FHD laptops.

See [this page](https://www.khronos.org/registry/webgl/sdk/demos/google/high-dpi/index.html) for an example

**Comment by kovacsv** [comment]
Could you please attach a screenshot of the problem in the viewer?

**Comment by stopmotio** [comment]
Sure!
![Screenshot_20210421-163244.png](https://user-images.githubusercontent.com/21047900/115617290-3ebda000-a2bf-11eb-9245-8c6aa22c2353.png)
You can see the table is clearly not as crisp as the icons.

**Comment by stopmotio** [comment]
When will the commit make it to 3dviewer.net?

**Comment by kovacsv** [comment]
It will available in the next release. I plan to do it in the middle of next week.

**Comment by stopmotio** [comment]
Awesome! Thanks for the timely patch.

**Comment by kovacsv** [comment]
Done in release 0.7.8.
