### ISSUE TITLE
Mac OS with zsh - CompressFiles never ends

### ISSUE THREAD

**Issue by santerref** [kovacsv/Online3DViewer#66]
Thanks for this package, this is really great.

I am working on some improvements for a project of mine and I have found a problem with the build command.

The CompressFiles function freeze and never finish.

After doing some search, I have found that setting `shell = FALSE` for the function `RunCommand` fix the issue.

```python
def RunCommand (commands):
	process = subprocess.Popen (commands, stdout = subprocess.PIPE, stderr = subprocess.PIPE, shell = False)
	out, err = process.communicate ()
	if process.returncode != 0:
		print (out.decode ())
		print (err.decode ())
	return process.returncode
```

I am on Mac with iTerm2 and ZSH.

**Comment by santerref** [comment]
Yes ! When the value is `TRUE`, I always get this and it freezes:

<img width="440" alt="Screen Shot 2021-04-30 at 10 35 07 AM" src="https://user-images.githubusercontent.com/633244/116710507-d4cc8700-a99f-11eb-8273-96aac31b317b.png">

**Comment by kovacsv** [comment]
On Windows it works only with `shell = True` 😃 Otherwise it doesn't find the executable. So I think it has to be a platform (maybe shell) dependent solution.

**Comment by kovacsv** [comment]
Could you please try if this works for you?
```python
def RunCommand (commands):
	return os.system (" ".join (commands))
```

**Comment by kovacsv** [comment]
Done in release 0.7.8.
