### ISSUE TITLE
Visualizing model - doesn't load.

### ISSUE THREAD

**Issue by AlestarAndrei** [kovacsv/Online3DViewer#78]
I followed https://github.com/kovacsv/Online3DViewer/wiki/Use-the-Viewer-on-Your-Website

I did exactly this 4 steps and receive `threeGeometry.setAttribute is not a function` error.

I'm missing something ? 

I also tried to load a different version of three js library because I found that setAttribute was introduced from r110 https://github.com/mrdoob/three.js/wiki/Migration-Guide#r109--r110

**Comment by AlestarAndrei** [comment]
Yes I use this last release

![image](https://user-images.githubusercontent.com/24910903/121145442-a1570500-c847-11eb-95e5-590c9f411410.png)

**Comment by kovacsv** [comment]
Could you please attach the page with all the files where it can be reproduced?

**Comment by AlestarAndrei** [comment]
It seems was a conflict with some other library on that page.
I loaded this on an empty page (in order to send you an attached page) and it works.

Thanks for quick answer.
