### ISSUE TITLE
Show custom properties of the model and the meshes

### ISSUE THREAD

**Issue by paireks** [kovacsv/Online3DViewer#79]
Hey!

Great work!
I just wanted to say, that it would be really useful to make it possible to see the properties of geometry by click, not only the name (which is right now), but also some custom made properties. In both .glb/.gltf and in Rhino files you can attach some information to geometry, I don't know how it looks like in rest of the files.
The thing is that with such an approach you will allow some kind of BIM collaboration without this whole IFC bullshit ;)

Best!

**Comment by kovacsv** [comment]
glTF metadata and 3dm mesh properties are added. 3dm file-level properties doesn't work because of this bug:
https://github.com/mcneel/rhino3dm/issues/303

**Comment by kovacsv** [comment]
Done in 0.7.15.
