### ISSUE TITLE
Use arcball for intuitive rotation

### ISSUE THREAD

**Issue by rgov** [kovacsv/Online3DViewer#8]
The tool seems useful, thanks for it. But I'm having a hell of a time figuring out how to rotate my model to the orientation I want... the mouse X axis and Y axis seem bound to different rotation axes, but there's a third axis I can't figure out how to rotate along. Arcball rotation would be much more intuitive.

**Comment by kovacsv** [comment]
Fixed in 1902ca43c4e2e09ddf6c6abe00bd0e772acb7a3c.
