### ISSUE TITLE
Add support for IFC

### ISSUE THREAD

**Issue by runxel** [kovacsv/Online3DViewer#81]
It would be great to show an IFC file directly in the browser.
https://github.com/agviegas/web-ifc-viewer could be incorporated for that.

**Comment by kovacsv** [comment]
I've done some experiments with https://github.com/tomvandig/web-ifc and the result is very promising. Although web-ifc is a really great technology it's still in pre-alpha phase. It's great to see that its under heavy development, so I hope a more stable version will come out soon and we can use it in the viewer.

![image](https://user-images.githubusercontent.com/2034315/121796661-19904280-cc1b-11eb-886c-1881d9f580cb.png)

**Comment by kovacsv** [comment]
It's released as an experimental feature.
