### ISSUE TITLE
There is a problem with the mesh name

### ISSUE THREAD

**Issue by zhaoxiaomiao** [kovacsv/Online3DViewer#84]
The mesh name cannot be obtained on some models. The same model can be seen in some model viewers, but it is not available in the modification project, as shown in the following figure
![1](https://user-images.githubusercontent.com/12390272/122231769-48453c00-ceed-11eb-82d0-006154ce6418.png)
![2](https://user-images.githubusercontent.com/12390272/122231793-4f6c4a00-ceed-11eb-80a0-ffb9973e15c6.png)

**Comment by kovacsv** [comment]
Could you please attache the .glb file to reproduce the issue?

**Comment by zhaoxiaomiao** [comment]
下面这个模型也一样，mesh名称有问题，不能正常展示，模型结构是否可以以树结构展示？







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kovacsv/Online3DViewer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月16日(星期三) 晚上10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kovacsv/Online3DViewer] There is a problem with the mesh name (#84)





 
Could you please attache the .glb file to reproduce the issue?

**Comment by kovacsv** [comment]
Unfortunately the attachment didn't arrive. Please try to attach it on GitHub, and not in e-mail.

**Comment by zhaoxiaomiao** [comment]
This is the GLB 
[bucket.zip](https://github.com/kovacsv/Online3DViewer/files/6663889/bucket.zip)

**Comment by kovacsv** [comment]
There are no mesh names in the file, but in this case the name of the mesh node can be used in the viewer.

**Comment by kovacsv** [comment]
Fixed in release 0.7.14.
