### ISSUE TITLE
Model sectioning

### ISSUE THREAD

**Issue by zhaoxiaomiao** [kovacsv/Online3DViewer#91]
Whether you can add the function of model cutting, so that you can easily view the internal structure of the model.

**Comment by lichangyuan1993** [comment]
I strongly agree that the model sectioning feature is very necessary.

**Comment by yvanblanchard** [comment]
Here is a simple code (clipping with caps):
https://github.com/daign/clipping-with-caps

**Comment by yvanblanchard** [comment]
Another example:
https://gkjohnson.github.io/three-mesh-bvh/example/bundle/clippedEdges.html

**Comment by kovacsv** [comment]
Duplicate, I close this one.
