### ISSUE TITLE
The model is not very realistic

### ISSUE THREAD

**Issue by zhaoxiaomiao** [kovacsv/Online3DViewer#93]
The rendering effect is a little fuzzy, especially the display effect of some metal models is not ideal, not only some fuzzy, but also no metal texture, for example, the following two pictures, the first is the website display effect, the second is the real effect of the model, these two pictures are from the same GLB model
![1](https://user-images.githubusercontent.com/12390272/124351622-02e37700-dc2e-11eb-8f71-16f6f2b1b1b4.png)
![2](https://user-images.githubusercontent.com/12390272/124351629-0bd44880-dc2e-11eb-95c4-6803bc84409e.png)

**Comment by kovacsv** [comment]
@zhaoxiaomiao could you please attach the model so I can check it after fixing #99?

**Comment by zhaoxiaomiao** [comment]
![demo](https://user-images.githubusercontent.com/12390272/126332237-361482ec-74b0-4990-aa18-4c6181b1758d.png)
[HTW730.zip](https://github.com/kovacsv/Online3DViewer/files/6848595/HTW730.zip)

**Comment by zhaoxiaomiao** [comment]
> @zhaoxiaomiao能否请您附上模型，以便我在修复#99后检查它？

![demo](https://user-images.githubusercontent.com/12390272/126332415-ac1631f4-2948-4dc2-9a9e-b094e8f3ee10.png)
[HTW730.zip](https://github.com/kovacsv/Online3DViewer/files/6848603/HTW730.zip)

**Comment by kovacsv** [comment]
Done in 0.7.17.
