### ISSUE TITLE
Uncaught TypeError when using .glb

### ISSUE THREAD

**Issue by nikita-fuchs** [kovacsv/Online3DViewer#96]
Hello everybody, whenever I try drag-n-dropping my `.glb` files, I'm getting the following error:
`Uncaught TypeError: First argument to DataView constructor must be an ArrayBuffer`
Here is an example file:
https://www117.zippyshare.com/v/6r3UmJnL/file.html

**Comment by kovacsv** [comment]
Thanks for the report. The file refers to a texture buffer that doesn't exists. I've modified the code to handle this situation, so it should work in the next release.

![model_gltf_doll_dress glb](https://user-images.githubusercontent.com/2034315/125316274-4332ab80-e338-11eb-9c83-4f9cc60600d8.png)

**Comment by nikita-fuchs** [comment]
awesome, thank you very much ! Any idea on https://github.com/kovacsv/Online3DViewer/issues/97 already maybe ?

**Comment by kovacsv** [comment]
Done in 0.7.16.
