### ISSUE TITLE
Add support for GLB Draco Mesh Compression

### ISSUE THREAD

**Issue by Darkblader24** [kovacsv/Online3DViewer#97]
Hello! 

Draco mesh compression can be used to greatly reduce the file size (>50%) of GLB and GLTF files. You can export files with this compression from Blender, but they don't load in this 3D viewer. Adding support for this compression would be great!

Here is an example file using this compression (no textures): 
[Shirt Draco Mesh Compression.zip](https://github.com/kovacsv/Online3DViewer/files/6802230/Shirt.Draco.Mesh.Compression.zip)

**Comment by kovacsv** [comment]
Done in 0.7.16.
