### ISSUE TITLE
Use Physically Based Rendering when possible

### ISSUE THREAD

**Issue by kovacsv** [kovacsv/Online3DViewer#99]
glTF files usually come with PBR materials. It would be great to use PBR rendering in this case.

**Comment by kovacsv** [comment]
Before:
![old](https://user-images.githubusercontent.com/2034315/126209382-1286e439-2068-4ac4-b98e-f22bd2c14339.png)

After:
![new](https://user-images.githubusercontent.com/2034315/126209390-08037904-f245-4ea1-ae12-9455b546d7a3.png)

**Comment by kovacsv** [comment]
Done in 0.7.17.

**Comment by ColourfulU** [comment]
Is Physically Based Rendering enabled by default? Is there an option to turn it on or off?
